In [15]:
import torch
import numpy as np
import pandas as pd
import plotly.express as px
from transformers import AutoTokenizer, AutoModelForCausalLM
from scipy.spatial.distance import mahalanobis
from scipy.linalg import inv, LinAlgError
from sklearn.decomposition import PCA
from sklearn.metrics import davies_bouldin_score
from joblib import Parallel, delayed
import os
import time
TOPICS = {
    "Baseline": None,

    # =========================
    # IMMIGRATION
    # =========================
    "imm_unauth": "unauthorized and undocumented immigrants",
    "birthright": "birthright citizenship",
    "illeg_child": "children of undocumented immigrants",
    "border_wall": "a wall along the U.S.–Mexico border",
    "spend_border": "whether to increase or decrease funding for border security",

    # =========================
    # LABOR / FAMILY POLICY
    # =========================
    "paid_leave": "paid parental or family leave",
    "job_gov_guar": "whether the government should guarantee a job to everyone",
    "min_wage": "whether to change the minimum wage",
    "ft_union": "labor unions",

    # =========================
    # INSTITUTIONS / ACCOUNTABILITY / MEDIA
    # =========================
    "trump_corr": "whether Donald Trump was involved in political corruption",
    "journ_access": "whether journalists should have broad access to government officials and information",
    "checks_power": "to what degree the branches of government should limit each other’s power",
    "rus_interf": "how serious a problem Russian interference in U.S. elections is",

    # =========================
    # ELECTIONS / DEMOCRACY
    # =========================
    "voter_id": "whether voters should be required to show identification to vote",
    "felon_vote": "whether people with felony convictions should have the right to vote",

    # =========================
    # ECONOMY (RETROSPECTIVE)
    # =========================
    "econ_now": "how good or bad the current national economy is",

    # =========================
    # GUNS
    # =========================
    "gun_bkg_chk": "whether background checks should be required for gun purchases",
    "ar_ban": "whether assault weapons should be banned",
    "gun_imp": "to what degree gun regulation is an important political issue",

    # =========================
    # CRIME / POLICING / ORDER
    # =========================
    "death_pen": "whether the death penalty should be used for serious crimes",
    "police_force": "to what degree police should be allowed to use force",
    "urban_unrest": "how serious a problem urban unrest and protests are",
    "ft_police": "the police",

    # =========================
    # ABORTION / COURTS
    # =========================
    "abortion": "whether abortion should be legal",
    "scotus_abort": "the Supreme Court decisions related to abortion",

    # =========================
    # HEALTH
    # =========================
    "govt_health": "whether the government should provide health insurance",
    "obamacare": "whether the Affordable Care Act should be kept, expanded, or repealed",
    "vax_school": "whether children should be required to be vaccinated to attend school",

    # =========================
    # EDUCATION / SPENDING
    # =========================
    "spend_school": "to what degree the federal government should spend money on public schools",

    # =========================
    # REDISTRIBUTION / WELFARE / TAX
    # =========================
    "spend_welfare": "to what degree the federal government should spend money on welfare programs",
    "spend_poor": "to what degree the federal government should spend money to help the poor",
    "svc_spend": "to what degree the government should spend money on public services",
    "millionaire_tax": "whether to tax on millionaires",

    # =========================
    # RACE / DIVERSITY
    # =========================
    "assist_black": "to what degree the government should help Black Americans",
    "black_favor": "whether Black people should get special favor",
    "diversity": "to what degree diversity benefits the country",

    # =========================
    # LGBTQ (SEXUAL ORIENTATION / GENDER IDENTITY)
    # =========================
    "trans_bath": "whether transgender people should be allowed to use bathrooms matching their gender identity",
    "trans_military": "whether transgender people should be allowed to serve in the U.S. military",
    "lg_job": "whether gay and lesbian people should be protected from job discrimination",
    "lg_marry": "whether same-sex couples should be allowed to marry legally",
    "lg_refuse_service": "whether businesses should be allowed to refuse service to same-sex couples",

    # =========================
    # CLIMATE / ENVIRONMENT
    # =========================
    "clim_imp": "how important climate change is as an issue",
    "env_bus": "the tradeoff between environmental protection and business interests",
    "ghg_emiss": "whether to regulate greenhouse gas emissions",

    # =========================
    # DEFENSE / FOREIGN POLICY
    # =========================
    "def_spend": "to what degree the government should spend money on national defense",
    "mil_force": "whether the United States should use military force in foreign  countries",

    # =========================
    # TRADE
    # =========================
    "free_trade": "whether to free trade agreements with other countries",
    "intl_trade_job": "whether international trade helps or hurts jobs in the United States",

    # =========================
    # FEELING THERMOMETERS (IDENTITY / GROUP AFFECT)
    # =========================
    "ft_trans": "transgender people",
    "ft_fem": "feminists",
    "ft_sci": "scientists",
}

SYSTEM_MSG = (
    "You are simulating the public stance of U.S. politicians.\n\n"
)

# ==========================================
# 1. CONFIGURATION
# ==========================================
# A100 40GB can handle large batches for 8B models
BATCH_SIZE = 128
MODEL_PATH = "/project/jevans/maxzhuyt/models/Meta-Llama-3.1-8B-Instruct"
NOMINATE_CSV = "/project/jevans/maxzhuyt/data/HS116_members_fullname.csv"

# Topics: Core + Bipartisan/Horseshoe Candidates

# ==========================================
# 2. MODEL LOADER & EXTRACTION (GPU)
# ==========================================
def load_model(path):
    print(f"Loading model from: {path}...")
    dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    tokenizer = AutoTokenizer.from_pretrained(path, use_fast=True, local_files_only=True)
    
    # CRITICAL: Left padding allows batching without destroying the last token position
    tokenizer.padding_side = 'left' 
    tokenizer.truncation_side = "left"

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.pad_token_id = tokenizer.eos_token_id
    
    model = AutoModelForCausalLM.from_pretrained(
        path, dtype=dtype, device_map="auto", local_files_only=True, attn_implementation="eager"
    )
    model.generation_config.pad_token_id = tokenizer.pad_token_id
    return model, tokenizer

@torch.no_grad()
def extract_heads_batched(model, tokenizer, texts, batch_size=32):
    """
    Optimized extraction for A100.
    """
    model.eval()
    L = model.config.num_hidden_layers
    H = model.config.num_attention_heads
    D_head = model.config.hidden_size // H
    
    activations = []
    
    # Pre-allocate hook containers
    layer_outputs = [None] * L
    
    def get_hook(layer_idx):
        def hook(module, input, output):
            # Input[0] shape: [Batch, Seq, Hidden]
            # Reshape to [Batch, Seq, Heads, Head_Dim]
            # We immediately move to CPU to free VRAM for the next batch
            reshaped = input[0].detach().view(input[0].shape[0], input[0].shape[1], H, D_head)
            layer_outputs[layer_idx] = reshaped[:, -1, :, :].float().cpu().numpy()
        return hook

    # Register hooks once
    hooks = []
    for li in range(L):
        hooks.append(model.model.layers[li].self_attn.o_proj.register_forward_hook(get_hook(li)))

    print(f"  > Extracting with Batch Size {batch_size}...")
    
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        
        # Fast Tokenization
        formatted_batch = [
            tokenizer.apply_chat_template([{"role": "system", "content": SYSTEM_MSG}, {"role": "user", "content": t}], tokenize=False, add_generation_prompt=True)
            for t in batch
        ]
        
        enc = tokenizer(
            formatted_batch, return_tensors="pt", padding=True, truncation=True, max_length=128
        ).to(model.device)
        
        # Forward pass triggers hooks
        model(**enc)
        
        # Stack layers: [Batch, Layers, Heads, Dim]
        batch_acts = np.stack(layer_outputs, axis=1)
        activations.append(batch_acts)

    for h in hooks: h.remove()
    return np.concatenate(activations, axis=0)

# ==========================================
# 3. PARALLEL METRICS ENGINE (CPU)
# ==========================================
def calculate_metrics_for_single_head(head_data, party_labels):
    """
    Calculates all 5 metrics for a SINGLE head.
    This function will be mapped across 1024 heads in parallel.
    """
    # Filter Valid Data
    valid_mask = np.isin(party_labels, [100, 200])
    X = head_data[valid_mask]
    y = party_labels[valid_mask]
    
    # Centering for PCA/Covariance
    X_centered = X - np.mean(X, axis=0)
    
    results = {}
    
    # --- BLOCK A: PCA BASED METRICS (3 in 1) ---
    # We run PCA once to get eigenvalues, used for Dispersion, PC1, and Intrinsic Dim
    try:
        pca = PCA(n_components=10) # We only need top eigenvalues
        pca.fit(X_centered)
        evals = pca.explained_variance_
        
        # 3. Total Dispersion (Sum of variance/eigenvalues)
        results['Total_Dispersion'] = np.sum(evals)
        
        # 4. Explained Variance Ratio of PC1
        results['PC1_Ratio'] = pca.explained_variance_ratio_[0]
        
        # 5. Intrinsic Dimensionality (Participation Ratio)
        sum_evals = np.sum(evals)
        sum_sq_evals = np.sum(evals**2)
        if sum_sq_evals > 0:
            results['Intrinsic_Dim'] = (sum_evals**2) / sum_sq_evals
        else:
            results['Intrinsic_Dim'] = 0.0
            
    except Exception:
        results['Total_Dispersion'] = 0.0
        results['PC1_Ratio'] = 0.0
        results['Intrinsic_Dim'] = 0.0

    # --- BLOCK B: CLUSTER METRICS ---
    
    # 2. Davies-Bouldin Index
    # (Lower is better separation, so higher polarization means LOWER score usually)
    try:
        if len(np.unique(y)) > 1:
            results['Davies_Bouldin'] = davies_bouldin_score(X, y)
        else:
            results['Davies_Bouldin'] = 10.0 # Bad score
    except:
        results['Davies_Bouldin'] = 10.0

    # 1. Mahalanobis Distance
    try:
        dems = X[y == 100]
        reps = X[y == 200]
        
        if len(dems) > 5 and len(reps) > 5:
            # Pooled Covariance with regularization
            cov_pool = (np.cov(dems, rowvar=False) + np.cov(reps, rowvar=False)) / 2
            cov_pool += np.eye(cov_pool.shape[0]) * 1e-6 # Regularize
            
            inv_cov = inv(cov_pool)
            mu_d, mu_r = np.mean(dems, axis=0), np.mean(reps, axis=0)
            results['Mahalanobis'] = mahalanobis(mu_d, mu_r, inv_cov)
        else:
            results['Mahalanobis'] = 0.0
    except (LinAlgError, ValueError):
        results['Mahalanobis'] = 0.0
        
    return results

# ==========================================
# 4. MAIN EXECUTION LOOP
# ==========================================

# Setup
model, tokenizer = load_model(MODEL_PATH)

df_nom = pd.read_csv(NOMINATE_CSV)
df_nom = df_nom[df_nom['party_code'].isin([100, 200])].dropna(subset=['bioname'])
party_labels = df_nom['party_code'].values

full_results = []

print(f"\nStarting Optimized Pipeline on A100 (Batch Size {BATCH_SIZE})")
print(f"Parallel processing enabled for metrics calculation.")

for topic_name, topic_desc in TOPICS.items():
    t0 = time.time()
    print(f"\n--- Topic: {topic_name} ---")
    
    # 1. Generate Prompts
    prompts = []
    for name in df_nom['bioname']:
        if topic_desc:
            user_msg = (
                f"Context: United States, in 2020.\n\n"
                f"Generate a statement by {name} expressing this politician’s position on {topic_desc}."
            )
        else:
            user_msg = (
                f"Context: United States, in 2020.\n\n"
                f"Generate a statement by {name}."
            )
        prompts.append(user_msg)
        
    # 2. Extract Heads (GPU Bound)
    # Shape: [N, 32, 32, 128]
    X_heads = extract_heads_batched(model, tokenizer, prompts, batch_size=BATCH_SIZE)
    
    # 3. Parallel Metrics (CPU Bound)
    # Flatten L and H to iterate easily: List of (1024) arrays of shape (N, 128)
    N, L, H, D = X_heads.shape
    flat_heads = [X_heads[:, l, h, :] for l in range(L) for h in range(H)]
    
    print("  > Computing metrics for 1024 heads (Parallel)...")
    
    # Uses all available CPU cores
    metrics_flat = Parallel(n_jobs=-1)(
        delayed(calculate_metrics_for_single_head)(head_data, party_labels) 
        for head_data in flat_heads
    )
    
    # 4. Aggregation & Storage
    # Reshape back to (32, 32) grids for visualization
    metric_grids = {k: np.zeros((L, H)) for k in metrics_flat[0].keys()}
    
    idx = 0
    for l in range(L):
        for h in range(H):
            m = metrics_flat[idx]
            for key in m:
                metric_grids[key][l, h] = m[key]
            idx += 1
            
    # Calculate Averages/Max for Summary
    summary = {"Topic": topic_name}
    for key, grid in metric_grids.items():
        summary[f"Avg_{key}"] = np.mean(grid)
        summary[f"Max_{key}"] = np.max(grid)
        # Store the full grid for heatmaps later
        summary[f"Grid_{key}"] = grid
        
    full_results.append(summary)
    print(f"  > Done in {time.time() - t0:.1f}s. Avg Mahalanobis: {summary['Avg_Mahalanobis']:.4f}")

# ==========================================
# 5. VISUALIZATION
# ==========================================
df_res = pd.DataFrame(full_results)

Loading model from: /project/jevans/maxzhuyt/models/Meta-Llama-3.1-8B-Instruct...

Loading checkpoint shards: 100%|██████████| 4/4 [00:06<00:00,  1.65s/it]

Starting Optimized Pipeline on A100 (Batch Size 128)
Parallel processing enabled for metrics calculation.

--- Topic: Baseline ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 13.3s. Avg Mahalanobis: 1.7423

--- Topic: imm_unauth ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.6s. Avg Mahalanobis: 1.8204

--- Topic: birthright ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.5s. Avg Mahalanobis: 1.7835

--- Topic: illeg_child ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.7s. Avg Mahalanobis: 1.8166

--- Topic: border_wall ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.8052

--- Topic: spend_border ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.7566

--- Topic: paid_leave ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.7s. Avg Mahalanobis: 1.8490

--- Topic: job_gov_guar ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.0s. Avg Mahalanobis: 1.7758

--- Topic: min_wage ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.8s. Avg Mahalanobis: 1.7913

--- Topic: ft_union ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.5s. Avg Mahalanobis: 1.7925

--- Topic: trump_corr ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.9s. Avg Mahalanobis: 1.8147

--- Topic: journ_access ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.2s. Avg Mahalanobis: 1.7373

--- Topic: checks_power ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.4s. Avg Mahalanobis: 1.6614

--- Topic: rus_interf ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.3s. Avg Mahalanobis: 1.7470

--- Topic: voter_id ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.7859

--- Topic: felon_vote ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.2s. Avg Mahalanobis: 1.8162

--- Topic: econ_now ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.7399

--- Topic: gun_bkg_chk ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.0s. Avg Mahalanobis: 1.8627

--- Topic: ar_ban ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.8s. Avg Mahalanobis: 1.8765

--- Topic: gun_imp ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.8110

--- Topic: death_pen ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.7537

--- Topic: police_force ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.7468

--- Topic: urban_unrest ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.7662

--- Topic: ft_police ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.5s. Avg Mahalanobis: 1.7759

--- Topic: abortion ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.7s. Avg Mahalanobis: 1.8042

--- Topic: scotus_abort ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.9s. Avg Mahalanobis: 1.8087

--- Topic: govt_health ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.9s. Avg Mahalanobis: 1.7936

--- Topic: obamacare ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.4s. Avg Mahalanobis: 1.8329

--- Topic: vax_school ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.2s. Avg Mahalanobis: 1.7388

--- Topic: spend_school ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.3s. Avg Mahalanobis: 1.7578

--- Topic: spend_welfare ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.3s. Avg Mahalanobis: 1.7801

--- Topic: spend_poor ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.4s. Avg Mahalanobis: 1.7927

--- Topic: svc_spend ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.3s. Avg Mahalanobis: 1.7396

--- Topic: millionaire_tax ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.8s. Avg Mahalanobis: 1.8055

--- Topic: assist_black ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.8539

--- Topic: black_favor ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.9s. Avg Mahalanobis: 1.8043

--- Topic: diversity ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.9s. Avg Mahalanobis: 1.7833

--- Topic: trans_bath ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.4s. Avg Mahalanobis: 1.8400

--- Topic: trans_military ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.4s. Avg Mahalanobis: 1.8418

--- Topic: lg_job ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.2s. Avg Mahalanobis: 1.8838

--- Topic: lg_marry ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.2s. Avg Mahalanobis: 1.8431

--- Topic: lg_refuse_service ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.3s. Avg Mahalanobis: 1.8280

--- Topic: clim_imp ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.0s. Avg Mahalanobis: 1.8355

--- Topic: env_bus ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.1s. Avg Mahalanobis: 1.7583

--- Topic: ghg_emiss ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.8s. Avg Mahalanobis: 1.8146

--- Topic: def_spend ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.3s. Avg Mahalanobis: 1.7203

--- Topic: mil_force ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.3s. Avg Mahalanobis: 1.7412

--- Topic: free_trade ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.0s. Avg Mahalanobis: 1.7251

--- Topic: intl_trade_job ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 9.2s. Avg Mahalanobis: 1.7312

--- Topic: ft_trans ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.5s. Avg Mahalanobis: 1.8776

--- Topic: ft_fem ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.4s. Avg Mahalanobis: 1.7976

--- Topic: ft_sci ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.4s. Avg Mahalanobis: 1.7662

In [16]:
df_res = pd.DataFrame(full_results)

In [17]:
import plotly.graph_objects as go
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
def adjust_text_positions(x, y, text_list, max_iterations=100, step_size=0.01):
    """
    Iteratively moves text away from:
      1. Its own data point (repulsion)
      2. Other text labels (collision avoidance)
    Returns optimized x_text, y_text arrays.
    """
    n = len(x)
    # Start text positions exactly at data points
    tx = np.array(x, dtype=float)
    ty = np.array(y, dtype=float)
    
    # Normalize coordinates to 0-1 scale for consistent 'force' calculations
    # We will map them back later.
    x_min, x_max = np.min(x), np.max(x)
    y_min, y_max = np.min(y), np.max(y)
    x_range = x_max - x_min
    y_range = y_max - y_min
    
    # Avoid division by zero
    if x_range == 0: x_range = 1
    if y_range == 0: y_range = 1
    
    tx_norm = (tx - x_min) / x_range
    ty_norm = (ty - y_min) / y_range
    x_norm = (np.array(x) - x_min) / x_range
    y_norm = (np.array(y) - y_min) / y_range

    for _ in range(max_iterations):
        # Calculate forces
        grad_x = np.zeros(n)
        grad_y = np.zeros(n)
        
        for i in range(n):
            # 1. Force pushing text away from its own data point
            # We want it slightly offset, not ON TOP
            dist_self_x = tx_norm[i] - x_norm[i]
            dist_self_y = ty_norm[i] - y_norm[i]
            dist_sq = dist_self_x**2 + dist_self_y**2
            
            # If too close to dot, push away (standard radius)
            target_radius = 0.04 # 4% of plot width
            if dist_sq < target_radius**2:
                 # Push randomly if exactly on top, otherwise radially
                if dist_sq == 0:
                    grad_x[i] += (np.random.random() - 0.5) * 0.1
                    grad_y[i] += (np.random.random() - 0.5) * 0.1
                else:
                    force = (target_radius - np.sqrt(dist_sq)) 
                    grad_x[i] += force * (dist_self_x / np.sqrt(dist_sq))
                    grad_y[i] += force * (dist_self_y / np.sqrt(dist_sq))

            # 2. Force pushing text away from OTHER labels
            for j in range(n):
                if i == j: continue
                
                diff_x = tx_norm[i] - tx_norm[j]
                diff_y = ty_norm[i] - ty_norm[j]
                dist_sq = diff_x**2 + diff_y**2
                
                # Collision radius (approximate text box size)
                min_dist = 0.05 # 5% of plot width
                
                if dist_sq < min_dist**2:
                     if dist_sq == 0:
                        grad_x[i] += (np.random.random() - 0.5) * 0.1
                        grad_y[i] += (np.random.random() - 0.5) * 0.1
                     else:
                        force = (min_dist - np.sqrt(dist_sq)) * 2 # Stronger force for text collision
                        grad_x[i] += force * (diff_x / np.sqrt(dist_sq))
                        grad_y[i] += force * (diff_y / np.sqrt(dist_sq))
                        
        # Apply movements
        tx_norm += grad_x * step_size
        ty_norm += grad_y * step_size
        
        # Clamp to 0-1 to keep inside plot (optional)
        tx_norm = np.clip(tx_norm, 0, 1)
        ty_norm = np.clip(ty_norm, 0, 1)

    # Convert back to original scale
    final_tx = tx_norm * x_range + x_min
    final_ty = ty_norm * y_range + y_min
    
    return final_tx, final_ty

def plot(df_plot):
    # Run the physics engine to get new coordinates for the TEXT ONLY
    # (Assuming adjust_text_positions is defined in your environment)
    new_x, new_y = adjust_text_positions(
        df_plot["Avg_Mahalanobis"].values, 
        df_plot["Avg_Total_Dispersion"].values, 
        df_plot["Topic"].values,
        max_iterations=200, 
        step_size=0.5
    )

    df_plot['text_x'] = new_x
    df_plot['text_y'] = new_y

    # --- 3. PLOTTING (Using Graph Objects for Layering) ---

    fig = go.Figure()

    # Layer 1: The Dots (Markers)
    unique_topics = df_plot['Topic'].unique()
    colors = px.colors.qualitative.Plotly 

    for i, topic in enumerate(unique_topics):
        df_sub = df_plot[df_plot['Topic'] == topic]
        color = colors[i % len(colors)]
        
        fig.add_trace(go.Scatter(
            x=df_sub['Avg_Mahalanobis'],
            y=df_sub['Avg_Total_Dispersion'],
            mode='markers',
            name=topic,
            # Pass Intrinsic Dim as custom data for the hover
            customdata=df_sub['Avg_Intrinsic_Dim'], 
            marker=dict(
                size=14,  # FIXED SIZE for visualization
                color=color,
                opacity=0.85,
                line=dict(width=1, color='DarkSlateGrey')
            ),
            hovertemplate=(
                "<b>%{text}</b><br>" +
                "Polarization: %{x:.4f}<br>" +
                "Intensity: %{y:.2f}<br>" +
                "Intrinsic Dim: %{customdata:.2f}<br>" + # Added here
                "<extra></extra>" 
            ),
            text=df_sub['Topic']
        ))

    # Layer 2: The Lines (Connecting dots to labels)
    for i, row in df_plot.iterrows():
        fig.add_trace(go.Scatter(
            x=[row['Avg_Mahalanobis'], row['text_x']],
            y=[row['Avg_Total_Dispersion'], row['text_y']],
            mode='lines',
            line=dict(color='grey', width=0.3),
            showlegend=False,
            hoverinfo='skip'
        ))

    # Layer 3: The Text (at new optimized positions)
    fig.add_trace(go.Scatter(
        x=df_plot['text_x'],
        y=df_plot['text_y'],
        mode='text',
        text=df_plot['Topic'],
        textfont=dict(size=11, color='black'),
        showlegend=False,
        hoverinfo='skip'
    ))

    # --- 4. LAYOUT & ANNOTATIONS ---

    fig.update_layout(
        title="<b>What Politicans Say about Everyday Topics</b><br>X: Polarization | Y: Total Disagreement",
        template="plotly_white",
        height=800,
        width=1000,
        xaxis_title="Polarization (Mahalanobis Distance)",
        yaxis_title="Total Discourse Disagreement (Dispersion)",
        showlegend=True
    )

    # Add Quadrants
    mid_x = df_plot['Avg_Mahalanobis'].median()
    mid_y = df_plot['Avg_Total_Dispersion'].median()

    fig.add_hline(y=mid_y, line_dash="dot", line_color="grey", opacity=0.5)
    fig.add_vline(x=mid_x, line_dash="dot", line_color="grey", opacity=0.5)

    # Add Quadrant Labels (Watermarks)
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].max(), y=df_plot['Avg_Total_Dispersion'].max(),
                    text="<b>High Polarization<br>High Variance</b>", showarrow=False, align="right", opacity=0.3,
                    xref="x", yref="y", xanchor="right", yanchor="top")
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].min(), y=df_plot['Avg_Total_Dispersion'].max(),
                    text="<b>Low Polarization<br>High Variance</b>", showarrow=False, align="left", opacity=0.3,
                    xref="x", yref="y", xanchor="left", yanchor="top")
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].max(), y=df_plot['Avg_Total_Dispersion'].min(),
                    text="<b>High Polarization<br>Low Variance</b>", showarrow=False, align="right", opacity=0.3,
                    xref="x", yref="y", xanchor="right", yanchor="bottom")
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].min(), y=df_plot['Avg_Total_Dispersion'].min(),
                    text="<b>Low Polarization<br>Low Variance</b>", showarrow=False, align="left", opacity=0.3,
                    xref="x", yref="y", xanchor="left", yanchor="bottom")

    fig.show()
    fig.write_html("us_cultural_geometry_all.html", include_plotlyjs="cdn")

In [18]:
plot(df_res)

In [19]:
df_res

,Topic,Avg_Total_Dispersion,Max_Total_Dispersion,Grid_Total_Dispersion,Avg_PC1_Ratio,Max_PC1_Ratio,Grid_PC1_Ratio,Avg_Intrinsic_Dim,Max_Intrinsic_Dim,Grid_Intrinsic_Dim,Avg_Davies_Bouldin,Max_Davies_Bouldin,Grid_Davies_Bouldin,Avg_Mahalanobis,Max_Mahalanobis,Grid_Mahalanobis,text_x,text_y
0,Baseline,0.047658,1.387509,"[[0.0005941286217421293, 1.7847796698333696e-0...",0.431750,0.947555,"[[0.1026478260755539, 0.17366264760494232, 0.9...",3.595447,9.322110,"[[8.071420669555664, 5.656852722167969, 1.1524...",9.784196,38.962363,"[[10.713334338130528, 10.213109056063004, 32.9...",1.742303,2.734938,"[[1.297426727558818, 0.6436987625692131, 0.190...",1.733407,0.047658
1,imm_unauth,0.025412,0.815556,"[[1.93697887880262e-05, 2.454397690598853e-05,...",0.379067,0.892721,"[[0.09939506649971008, 0.6425905823707581, 0.8...",3.958459,9.607149,"[[8.002354621887207, 1.5098295211791992, 1.206...",7.887046,30.418443,"[[13.097787468712657, 10.108387830447315, 20.3...",1.820362,2.728656,"[[0.674533106974823, 0.44379014107771114, 0.14...",1.830654,0.024731
2,birthright,0.025352,0.834381,"[[3.131995981675573e-05, 2.3274738850886934e-0...",0.386380,0.901198,"[[0.08284518122673035, 0.6163932681083679, 0.8...",3.914912,9.568889,"[[8.534846305847168, 1.5693951845169067, 1.280...",8.718097,31.322303,"[[12.825210765451795, 9.435209463549949, 13.64...",1.783516,2.777187,"[[0.7733861378325337, 0.47390507778262697, 0.2...",1.793586,0.025433
3,illeg_child,0.029972,0.976445,"[[2.038319689745549e-05, 2.411310742900241e-05...",0.400106,0.917224,"[[0.09910338371992111, 0.6317772269248962, 0.8...",3.809451,9.513084,"[[8.019198417663574, 1.536874771118164, 1.1998...",7.716233,24.755611,"[[13.050365265330207, 9.87556210752656, 19.184...",1.816621,2.754288,"[[0.6861284852529614, 0.4500053155688136, 0.15...",1.825399,0.030153
4,border_wall,0.032572,1.196606,"[[6.063900400476996e-06, 2.596677586552687e-05...",0.398038,0.971956,"[[0.3604753315448761, 0.6265034079551697, 0.97...",3.820195,9.563842,"[[3.212019205093384, 1.557142972946167, 1.0551...",8.359323,23.014879,"[[11.164987589465785, 9.364784536960917, 10.78...",1.805198,2.769580,"[[0.3619386973605039, 0.45704631708487903, 0.1...",1.809131,0.031294
5,spend_border,0.023667,0.851360,"[[5.388631052483106e-06, 2.6470048396731727e-0...",0.383813,0.971407,"[[0.35020822286605835, 0.6348047256469727, 0.9...",3.911231,9.594017,"[[3.3033437728881836, 1.5374172925949097, 1.05...",8.731610,23.342132,"[[10.781268008471029, 9.272498602104898, 10.81...",1.756592,2.726768,"[[0.35949118393181106, 0.4569953483459465, 0.1...",1.759441,0.022424
6,paid_leave,0.019677,0.684278,"[[1.6045252777985297e-05, 2.860807944671251e-0...",0.366038,0.914819,"[[0.10040593892335892, 0.6743094325065613, 0.8...",4.038879,9.541095,"[[7.813446521759033, 1.4319865703582764, 1.223...",7.476192,37.319657,"[[11.321281271213909, 9.490259123622698, 23.46...",1.849040,2.798931,"[[0.6753289483994628, 0.4488995848335882, 0.17...",1.857936,0.019677
7,job_gov_guar,0.025874,0.842723,"[[5.784145741927205e-06, 2.5718809411046095e-0...",0.383822,0.973026,"[[0.34024110436439514, 0.6275244951248169, 0.9...",3.927313,9.600849,"[[3.4832119941711426, 1.5574824810028076, 1.05...",8.243511,44.083817,"[[11.547556269153565, 9.092248584730246, 10.44...",1.775823,2.703181,"[[0.3535567044569992, 0.46263836457499347, 0.1...",1.783484,0.026443
8,min_wage,0.021385,0.800602,"[[1.2617268112080637e-05, 3.3692107535898685e-...",0.372432,0.930449,"[[0.13106130063533783, 0.7141687273979187, 0.9...",3.998114,9.593244,"[[6.596046447753906, 1.3524714708328247, 1.120...",8.138109,33.723942,"[[9.86671041196184, 9.15545967369736, 11.39842...",1.791260,2.720502,"[[0.6353513998087199, 0.45614209926056454, 0.2...",1.798753,0.021988
9,ft_union,0.025730,0.888272,"[[4.1560862882761285e-05, 2.325317109352909e-0...",0.384846,0.935298,"[[0.07728436589241028, 0.5990427732467651, 0.8...",3.921824,9.560122,"[[8.615865707397461, 1.6154125928878784, 1.279...",8.421900,27.618786,"[[12.696556749196374, 9.4085570748373, 18.8068...",1.792478,2.725250,"[[0.8211638510522383, 0.49715459536521917, 0.1...",1.799002,0.026697
10,trump_corr,0.034118,1.135990,"[[6.9441989580809604e-06, 3.161785934935324e-0...",0.402404,0.972476,"[[0.29008749127388, 0.68069988489151, 0.972476...",3.802828,9.540348,"[[3.8840136528015137, 1.4288617372512817, 1.04...",7.048917,22.624871,"[[10.297273331989977, 9.367023386960048, 8.999...",1.814654,2.723695,"[[0.44826793249694974, 0.4630616698165723, 0.2...",1.816798,0.035204
11,journ_access,0.024609,0.894632,"[[3.118649601674406e-06, 1.6123845853144303e-0...",0.380107,0.968254,"[[0.18235979974269867, 0.5166677832603455, 0.9...",3.947253,9.596963,"[[5.625801086425781, 1.927033543586731, 1.0609...",8.615296,29.417355,"[[11.88519153513312, 11.149906175984572, 24.68...",1.737253,2.699476,"[[0.309405217122374, 0.423656822095901, 0.1300...",1.739882,0.023540
12,checks_power,0.021717,0.792949,"[[1.5919799807306845e-06, 1.988819713005796e-0...",0.373699,0.979333,"[[0.19415779411792755, 0.6176232099533081, 0.9...",4.024445,9.568583,"[[6.072155475616455, 1.6028536558151245, 1.037...",9.027179,29.306009,"[[9.570508901496423, 9.840035609374072, 8.5479...",1.661446,2.613513,"[[0.27995896793789427, 0.4257514379232205, 0.2...",1.661446,0.020598
13,rus_interf,0.030365,1.106107,"[[1.7940797079063486e-06, 1.5805275324964896e-...",0.392324,0.977395,"[[0.1909070760011673, 0.512164294719696, 0.977...",3.880009,9.588292,"[[5.89962100982666, 1.9586217403411865, 1.0417...",8.305994,33.122366,"[[9.963295853905375, 11.47680038425912, 9.6347...",1.747015,2.664178,"[[0.30148235758525416, 0.4263481212293585, 0.1...",1.755504,0.030699
14,voter_id,0.020934,0.758443,"[[2.9317902772163507e-06, 1.8803488273988478e-...",0.374091,0.960822,"[[0.16825367510318756, 0.54316246509552, 0.960...",3.980074,9.581177,"[[6.1433634757995605, 1.800561785697937, 1.078...",8.382960,22.130172,"[[13.195672420886858, 9.479529852101985, 18.79...",1.785853,2.714000,"[[0.29952783683987444, 0.4505053279373396, 0.1...",1.778992,0.020221
15,felon_vote,0.026053,0.898643,"[[3.5442301395960385e-06, 1.517672626505373e-0...",0.385653,0.966474,"[[0.19312505424022675, 0.48426496982574463, 0....",3.896687,9.501941,"[[5.509015083312988, 2.0688445568084717, 1.064...",7.425496,28.316185,"[[11.374531073974097, 10.978968967377087, 25.6...",1.816200,2.757857,"[[0.3314989884252814, 0.4317587466152931, 0.13...",1.820162,0.027055
16,econ_now,0.026269,1.006157,"[[5.658194368152181e-06, 2.6555702788755298e-0...",0.382868,0.973715,"[[0.34727948904037476, 0.6369892358779907, 0.9...",3.923747,9.609169,"[[3.3256449699401855, 1.5332481861114502, 1.05...",9.070725,24.764952,"[[11.044426468450373, 9.23527295972614, 10.181...",1.739906,2.727966,"[[0.36094862472885897, 0.45784561187924794, 0....",1.742813,0.027842
17,gun_bkg_chk,0.021121,0.772987,"[[5.857956693944288e-06, 2.590954682091251e-05...",0.371237,0.971974,"[[0.3647579848766327, 0.6237745881080627, 0.97...",3.997513,9.511414,"[[3.209433078765869, 1.568054437637329, 1.0549...",7.207960,22.411637,"[[11.240016207503729, 9.206191699077547, 10.79...",1.862673,2.803569,"[[0.35534009278731804, 0.4618626690749532, 0.1...",1.853799,0.021043
18,ar_ban,0.024071,0.868422,"[[1.3586850400315598e-05, 3.339662725920789e-0...",0.375196,0.928286,"[[0.13501203060150146, 0.7058539986610413, 0.9...",3.992704,9.494901,"[[6.6273345947265625, 1.367407202720642, 1.126...",7.172856,32.818926,"[[9.87936705648744, 9.2039883868499, 12.231082...",1.876521,2.812957,"[[0.6474497081316914, 0.45617442105224587, 0.1...",1.881053,0.023108
19,gun_imp,0.024582,0.841996,"[[2.9083034860377666e-06, 1.9339475329616107e-...",0.382881,0.960706,"[[0.1659712791442871, 0.5449243187904358, 0.96...",3.933775,9.568027,"[[6.131180763244629, 1.79714834690094, 1.07754...",7.923069,22.111932,"[[13.729475366269408, 9.574528515771444, 18.60...",1.811032,2.765317,"[[0.28668017235403753, 0.44939631794175866, 0....",1.818057,0.025483
20,death_pen,0.024079,0.866415,"[[2.7130681701237336e-06, 1.8867340259021148e-...",0.382362,0.962086,"[[0.16999351978302002, 0.5425742268562317, 0.9...",3.927944,9.586828,"[[6.005618095397949, 1.8006553649902344, 1.074...",8.606789,23.174872,"[[13.723439756977184, 9.471055776155012, 18.71...",1.753714,2.690963,"[[0.2798262527821356, 0.45269070823806007, 0.1...",1.752886,0.025193
21,police_force,0.022871,0.804305,"[[2.730449068621965e-06, 1.888609585876111e-05...",0.377082,0.962563,"[[0.16922591626644135, 0.5365079045295715, 0.9...",3.973455,9.610135,"[[6.039585590362549, 1.824636459350586, 1.0737...",8.581466,22.100371,"[[13.945473416646173, 9.497455122241508, 19.17...",1.746760,2.719909,"[[0.2778862834267668, 0.45527898563738295, 0.1...",1.752989,0.023670
22,urban_unrest,0.022217,0.863996,"[[5.284599865262862e-06, 2.5562807422829792e-0...",0.373503,0.972889,"[[0.35122349858283997, 0.6253414154052734, 0.9...",4.010588,9.668515,"[[3.2245094776153564, 1.564583659172058, 1.053...",8.361076,22.548666,"[[11.004260837761429, 9.326681125452344, 10.73...",1.766181,2.702336,"[[0.35037524972804657, 0.4580146819372612, 0.1...",1.764010,0.023859
23,ft_police,0.027261,1.002753,"[[4.057457044837065e-05, 2.2991984224063344e-0...",0.392749,0.935211,"[[0.07668562978506088, 0.5963419675827026, 0.8...",3.859323,9.608687,"[[8.622700691223145, 1.6233434677124023, 1.303...",8.871620,37.424029,"[[12.621536410736608, 9.673821223751089, 19.64...",1.775911,2.743293,"[[0.8237750178026679, 0.4927278492495377, 0.16...",1.763976,0.027746
24,abortion,0.032865,1.057970,"[[1.6911297279875726e-05, 2.8308455512160435e-...",0.401642,0.925919,"[[0.10060839354991913, 0.6717314720153809, 0.8...",3.805975,9.503211,"[[7.825969219207764, 1.4363796710968018, 1.227...",8.420710,38.348718,"[[11.241182459162072, 9.767055152227627, 23.52...",1.804190,2.729864,"[[0.6857544927400032, 0.449211377968518, 0.170...",1.801329,0.033925
25,scotus_abort,0.028969,1.008793,"[[9.286479325965047e-06, 3.452778037171811e-05...",0.402203,0.960638,"[[0.17670786380767822, 0.7131237983703613, 0.9...",3.803105,9.495669,"[[5.401723861694336, 1.3580939769744873, 1.066...",8.173680,24.196469,"[[9.310122335173837, 9.385545407014334, 8.6123...",1.808701,2.825768,"[[0.5640390588084496, 0.4571169284478878, 0.27...",1.819725,0.028799
26,govt_health,0.027320,0.995910,"[[9.192512152367271e-06, 3.498853766359389e-05...",0.391971,0.961124,"[[0.18323950469493866, 0.7171524167060852, 0.9...",3.866098,9.516212,"[[5.326966285705566, 1.3510159254074097, 1.065...",8.069312,23.361673,"[[9.366684444040073, 9.573563999590359, 8.8761...",1.793619,2.722737,"[[0.5625444008266697, 0.45425273927506155, 0.2...",1.786631,0.028061
27,obamacare,0.023027,0.876757,"[[1.2684164403253817e-06, 1.9583538232836872e-...",0.374060,0.979279,"[[0.2165163904428482, 0.6211954951286316, 0.97...",3.987169,9.512447,"[[5.3529887199401855, 1.591002345085144, 1.037...",7.693022,23.716503,"[[9.025821768888479, 9.760498182048284, 8.4185...",1.832869,2.837065,"[[0.26647742907633093, 0.42331357964024574, 0....",1.839590,0.023760
28,vax_school,0.020081,0.703005,"[[3.503614379951614e-06, 1.54613680933835e-05,...",0.371036,0.967771,"[[0.19158753752708435, 0.4819708466529846, 0.9...",4.007481,9.600602,"[[5.534343719482422, 2.082228899002075, 1.0620...",8.267914,35.645180,"[[11.643863988155626, 10.984004719335939, 25.9...",1.738791,2.677220,"[[0.32606364697996504, 0.43259583337043556, 0....",1.747253,0.020426
29,spend_school,0.021460,0.809505,"[[1.9000134443558636e-06, 1.6433083146694116e-...",0.375762,0.979131,"[[0.19238048791885376, 0.5402869582176208, 0.9...",3.963619,9.607778,"[[5.882139682769775, 1.8462255001068115, 1.038...",8.255704,24.778114,"[[10.129188561629817, 11.243449310421626, 9.60...",1.757754,2.704366,"[[0.30530805725394855, 0.4200680664477974, 0.1...",1.748618,0.021815
30,spend_welfare,0.023418,0.885826,"[[1.850218495746958e-06, 1.632171915844083e-05...",0.380714,0.978896,"[[0.1885007917881012, 0.5345645546913147, 0.97...",3.935075,9.596958,"[[6.0256757736206055, 1.8670849800109863, 1.03...",8.250167,28.371809,"[[10.12862121472005, 11.399043585554324, 9.507...",1.780082,2.701145,"[[0.3052595458315693, 0.41780343906195266, 0.1...",1.771740,0.022665
31,spend_poor,0.022631,0.881684,"[[1.56456474087463e-06, 2.011177275562659e-05,...",0.376006,0.978928,"[[0.18990039825439453, 0.6274124383926392, 0.9...",3.969202,9.593259,"[[6.249236106872559, 1.5773450136184692, 1.038...",7.798514,21.295807,"[[9.504272158172151, 9.965756769441095, 8.5814...",1.792660,2.707140,"[[0.2799926067971095, 0.4232977089527478, 0.21...",1.782303,0.023229
32,svc_spend,0.025716,0.949625,"[[3.500976163195446e-06, 1.5844394511077553e-0...",0.393909,0.967942,"[[0.19189298152923584, 0.5016502737998962, 0.9...",3.850271,9.616318,"[[5.458713531494141, 1.9893046617507935, 1.061...",8.635956,33.607067,"[[11.375004733277134, 11.321554228443134, 23.8...",1.739577,2.678922,"[[0.33100288235365816, 0.4233857453880906, 0.1...",1.745932,0.026500
33,millionaire_tax,0.022429,0.849353,"[[1.3377796676650178e-05, 3.3598429581616074e-...",0.377434,0.928253,"[[0.13684304058551788, 0.7058113217353821, 0.9...",3.967509,9.595161,"[[6.501305103302002, 1.3679825067520142, 1.126...",7.965515,27.938125,"[[9.828829314493257, 9.165138052918257, 11.852...",1.805544,2.780393,"[[0.6500556361503026, 0.4594420987892211, 0.20...",1.808392,0.021291
34,assist_black,0.032139,1.274407,"[[5.829183464811649e-06, 2.6230074581690133e-0...",0.395458,0.974654,"[[0.3556487560272217, 0.6306036114692688, 0.97...",3.845118,9.559222,"[[3.2112154960632324, 1.5472919940948486, 1.04...",6.763574,22.535219,"[[10.645603191635816, 9.209558671628912, 10.43...",1.853854,2.753869,"[[0.3712311746622517, 0.4613902936082504, 0.18...",1.856360,0.031065
35,black_favor,0.029204,0.854931,"[[9.279053301725071e-06, 3.4107306419173256e-0...",0.413753,0.961123,"[[0.18313893675804138, 0.7035840749740601, 0.9...",3.700118,9.433973,"[[5.302655220031738, 1.376558780670166, 1.0655...",6.592614,27.708941,"[[9.460792008933803, 9.581141207153028, 9.1011...",1.804285,2.723185,"[[0.5589669645896277, 0.46051563449340716, 0.2...",1.795878,0.028838
36,diversity,0.024302,0.936203,"[[9.174575097858906e-06, 3.535136056598276e-05...",0.376575,0.962118,"[[0.1870085448026657, 0.7228159308433533, 0.96...",3.982601,9.678030,"[[5.264114856719971, 1.3409512042999268, 1.063...",7.695245,25.475276,"[[9.389752764751407, 9.59491406104178, 8.90216...",1.783329,2.722165,"[[0.5609647282164721, 0.4481215329863322, 0.26...",1.793682,0.023888
37,trans_bath,0.028208,0.887997,"[[1.4374591046362184e-06, 1.969265031220857e-0...",0.392886,0.979037,"[[0.2091204971075058, 0.6273892521858215, 0.97...",3.834516,9.519260,"[[5.680170059204102, 1.5726648569107056, 1.037...",6.787040,21.941875,"[[9.244045706007487, 9.413375890040715, 8.5554...",1.840021,2.746969,"[[0.2782376795636381, 0.4248222413023387, 0.22...",1.843435,0.029242
38,trans_military,0.037917,1.290055,"[[1.0247138106933562e-06, 2.4249768102890812e-...",0.408654,0.961641,"[[0.36377596855163574, 0.6814725399017334, 0.9...",3.753603,9.450102,"[[3.62282657623291, 1.4520418643951416, 1.0665...",7.110183,36.369918,"[[11.106945057713247, 9.180040658641364, 9.171...",1.841814,2.738623,"[[0.18476474699926648, 0.4157413628644856, 0.2...",1.835031,0.037192
39,lg_job,0.038472,1.204815,"[[3.3793462534958962e-06, 1.5513569451286457e-...",0.409941,0.967057,"[[0.18254408240318298, 0.49668535590171814, 0....",3.711012,9.259749,"[[5.814991474151611, 2.0095577239990234, 1.063...",6.447903,27.131339,"[[12.030008256706616, 10.98004769947386, 25.37...",1.883839,2.757041,"[[0.3144863630542862, 0.43009583783463057, 0.1...",1.875377,0.038126
40,lg_marry,0.032455,1.071810,"[[2.8021138405165402e-06, 1.9053350115427747e-...",0.396173,0.962539,"[[0.16656500101089478, 0.5392372608184814, 0.9...",3.835214,9.511324,"[[6.204270839691162, 1.8134546279907227, 1.074...",7.117930,22.123337,"[[13.767465705217074, 9.355155261535096, 18.58...",1.843074,2.747387,"[[0.2855668882137497, 0.4577732133972912, 0.14...",1.851007,0.033136
41,lg_refuse_service,0.032093,1.051356,"[[1.8556827399152098e-06, 1.602451993676368e-0...",0.391190,0.978223,"[[0.192109614610672, 0.5260753631591797, 0.978...",3.862428,9.486054,"[[5.906894683837891, 1.8982605934143066, 1.040...",6.823556,30.659773,"[[10.272950469635216, 11.457001703122, 9.53391...",1.828013,2.722183,"[[0.30176688916683014, 0.4222171290051414, 0.1...",1.825417,0.033163
42,clim_imp,0.032024,1.173354,"[[7.5278258009348065e-06, 3.098340312135406e-0...",0.400699,0.971671,"[[0.3128409683704376, 0.6699128746986389, 0.97...",3.810750,9.509732,"[[3.6435341835021973, 1.455571174621582, 1.050...",7.296988,22.563092,"[[10.741985329345658, 9.253481517180088, 8.858...",1.835516,2.723213,"[[0.4419106734109767, 0.4639695656896881, 0.24...",1.827551,0.031526
43,env_bus,0.025421,0.997896,"[[5.7523479881638195e-06, 2.702122219488956e-0...",0.388041,0.973801,"[[0.3607326149940491, 0.6472526788711548, 0.97...",3.895967,9.604535,"[[3.198345899581909, 1.5060926675796509, 1.051...",8.467678,22.478902,"[[11.182530599872305, 9.087829462044484, 10.77...",1.758308,2.722292,"[[0.35635949977278225, 0.4577203910185289, 0.1...",1.757049,0.026529
44,ghg_emiss,0.025755,0.876454,"[[1.2785500075551681e-05, 3.418413325562142e-0...",0.383554,0.929377,"[[0.13176020979881287, 0.71687912940979, 0.929...",3.926666,9.529681,"[[6.650828838348389, 1.3470689058303833, 1.123...",7.792564,33.937192,"[[9.93503196826169, 9.346317138682798, 11.4327...",1.814586,2.750471,"[[0.6362254875960676, 0.45378643029187893, 0.2...",1.805613,0.024617
45,def_spend,0.022673,0.822885,"[[3.48407252204197e-06, 1.6007972590159625e-05...",0.379546,0.967847,"[[0.18188020586967468, 0.5011129975318909, 0.9...",3.948885,9.630182,"[[5.769799709320068, 1.9924018383026123, 1.061...",8.984374,26.754954,"[[12.08746523226838, 11.416842048449219, 23.96...",1.720307,2.668189,"[[0.31530808075293587, 0.4259615435425924, 0.1...",1.712836,0.023281
46,mil_force,0.029667,1.104165,"[[1.836891442508204e-06, 1.6035482985898852e-0...",0.400768,0.976078,"[[0.19037029147148132, 0.5298465490341187, 0.9...",3.804866,9.516433,"[[5.985666275024414, 1.882015347480774, 1.0446...",9.356407,37.671142,"[[10.005034139798937, 11.504956817943409, 9.91...",1.741231,2.707168,"[[0.3046946878084352, 0.420773505463656, 0.192...",1.734760,0.028899
47,free_trade,0.024190,0.880683,"[[6.668550668109674e-06, 3.138215470244177e-05...",0.388355,0.972799,"[[0.29586175084114075, 0.6802919507026672, 0.9...",3.882416,9.615048,"[[3.7708075046539307, 1.4309754371643066, 1.04...",9.124732,26.365295,"[[10.64371317505406, 9.251949015876269, 8.8775...",1.725123,2.713119,"[[0.431685748053691, 0.4628459115227862, 0.237...",1.716880,0.024610
48,intl_trade_job,0.034337,1.362772,"[[3.4689212498051347e-06, 1.5752189938211814e-...",0.404382,0.966123,"[[0.17646385729312897, 0.5053104758262634, 0.9...",3.787069,9.484663,"[[5.875414848327637, 1.9677989482879639, 1.065...",9.314196,41.601747,"[[12.388023506012718, 11.454345099822145, 26.7...",1.731186,2.717328,"[[0.3098216726953322, 0.4220216157284876, 0.13...",1.727084,0.033344
49,ft_trans,0.040814,1.197736,"[[3.8899408536963165e-05, 2.354241587454453e-0...",0.407275,0.928754,"[[0.07711529731750488, 0.6074524521827698, 0.8...",3.750261,9.495549,"[[8.62661361694336, 1.588810682296753, 1.30316...",6.434642,30.008645,"[[12.672762978811905, 9.608019805456118, 19.06...",1.877632,2.793604,"[[0.8131192537149828, 0.4959838333805375, 0.16...",1.868886,0.040609
50,ft_fem,0.041223,1.269046,"[[5.0335158448433504e-05, 2.340918217669241e-0...",0.410275,0.943262,"[[0.0817711353302002, 0.5838194489479065, 0.78...",3.752512,9.533710,"[[8.464189529418945, 1.6743913888931274, 1.484...",7.335004,26.629448,"[[11.414453459432472, 9.535838706898545, 19.35...",1.797567,2.673523,"[[0.8779097806159355, 0.514204116482375, 0.202...",1.790078,0.040618

In [45]:
# Drop topics that are strongly related to the 2020 election cycle. 
DROP_TOPICS = {
    "rus_interf",
    "urban_unrest",
    "econ_now",
    "trump_corr",
    "border_wall"
}

df_res = df_res[~df_res["Topic"].isin(DROP_TOPICS)]
# delete all topics with "ft" in the name

In [46]:
df_res

,Topic,Avg_Total_Dispersion,Max_Total_Dispersion,Grid_Total_Dispersion,Avg_PC1_Ratio,Max_PC1_Ratio,Grid_PC1_Ratio,Avg_Intrinsic_Dim,Max_Intrinsic_Dim,Grid_Intrinsic_Dim,Avg_Davies_Bouldin,Max_Davies_Bouldin,Grid_Davies_Bouldin,Avg_Mahalanobis,Max_Mahalanobis,Grid_Mahalanobis,text_x,text_y
0,Baseline,0.047658,1.387509,"[[0.0005941286217421293, 1.7847796698333696e-0...",0.431750,0.947555,"[[0.1026478260755539, 0.17366264760494232, 0.9...",3.595447,9.322110,"[[8.071420669555664, 5.656852722167969, 1.1524...",9.784196,38.962363,"[[10.713334338130528, 10.213109056063004, 32.9...",1.742303,2.734938,"[[1.297426727558818, 0.6436987625692131, 0.190...",1.733407,0.047658
1,imm_unauth,0.025412,0.815556,"[[1.93697887880262e-05, 2.454397690598853e-05,...",0.379067,0.892721,"[[0.09939506649971008, 0.6425905823707581, 0.8...",3.958459,9.607149,"[[8.002354621887207, 1.5098295211791992, 1.206...",7.887046,30.418443,"[[13.097787468712657, 10.108387830447315, 20.3...",1.820362,2.728656,"[[0.674533106974823, 0.44379014107771114, 0.14...",1.830654,0.024731
2,birthright,0.025352,0.834381,"[[3.131995981675573e-05, 2.3274738850886934e-0...",0.386380,0.901198,"[[0.08284518122673035, 0.6163932681083679, 0.8...",3.914912,9.568889,"[[8.534846305847168, 1.5693951845169067, 1.280...",8.718097,31.322303,"[[12.825210765451795, 9.435209463549949, 13.64...",1.783516,2.777187,"[[0.7733861378325337, 0.47390507778262697, 0.2...",1.793586,0.025433
3,illeg_child,0.029972,0.976445,"[[2.038319689745549e-05, 2.411310742900241e-05...",0.400106,0.917224,"[[0.09910338371992111, 0.6317772269248962, 0.8...",3.809451,9.513084,"[[8.019198417663574, 1.536874771118164, 1.1998...",7.716233,24.755611,"[[13.050365265330207, 9.87556210752656, 19.184...",1.816621,2.754288,"[[0.6861284852529614, 0.4500053155688136, 0.15...",1.825399,0.030153
5,spend_border,0.023667,0.851360,"[[5.388631052483106e-06, 2.6470048396731727e-0...",0.383813,0.971407,"[[0.35020822286605835, 0.6348047256469727, 0.9...",3.911231,9.594017,"[[3.3033437728881836, 1.5374172925949097, 1.05...",8.731610,23.342132,"[[10.781268008471029, 9.272498602104898, 10.81...",1.756592,2.726768,"[[0.35949118393181106, 0.4569953483459465, 0.1...",1.759441,0.022424
6,paid_leave,0.019677,0.684278,"[[1.6045252777985297e-05, 2.860807944671251e-0...",0.366038,0.914819,"[[0.10040593892335892, 0.6743094325065613, 0.8...",4.038879,9.541095,"[[7.813446521759033, 1.4319865703582764, 1.223...",7.476192,37.319657,"[[11.321281271213909, 9.490259123622698, 23.46...",1.849040,2.798931,"[[0.6753289483994628, 0.4488995848335882, 0.17...",1.857936,0.019677
7,job_gov_guar,0.025874,0.842723,"[[5.784145741927205e-06, 2.5718809411046095e-0...",0.383822,0.973026,"[[0.34024110436439514, 0.6275244951248169, 0.9...",3.927313,9.600849,"[[3.4832119941711426, 1.5574824810028076, 1.05...",8.243511,44.083817,"[[11.547556269153565, 9.092248584730246, 10.44...",1.775823,2.703181,"[[0.3535567044569992, 0.46263836457499347, 0.1...",1.783484,0.026443
8,min_wage,0.021385,0.800602,"[[1.2617268112080637e-05, 3.3692107535898685e-...",0.372432,0.930449,"[[0.13106130063533783, 0.7141687273979187, 0.9...",3.998114,9.593244,"[[6.596046447753906, 1.3524714708328247, 1.120...",8.138109,33.723942,"[[9.86671041196184, 9.15545967369736, 11.39842...",1.791260,2.720502,"[[0.6353513998087199, 0.45614209926056454, 0.2...",1.798753,0.021988
9,ft_union,0.025730,0.888272,"[[4.1560862882761285e-05, 2.325317109352909e-0...",0.384846,0.935298,"[[0.07728436589241028, 0.5990427732467651, 0.8...",3.921824,9.560122,"[[8.615865707397461, 1.6154125928878784, 1.279...",8.421900,27.618786,"[[12.696556749196374, 9.4085570748373, 18.8068...",1.792478,2.725250,"[[0.8211638510522383, 0.49715459536521917, 0.1...",1.799002,0.026697
11,journ_access,0.024609,0.894632,"[[3.118649601674406e-06, 1.6123845853144303e-0...",0.380107,0.968254,"[[0.18235979974269867, 0.5166677832603455, 0.9...",3.947253,9.596963,"[[5.625801086425781, 1.927033543586731, 1.0609...",8.615296,29.417355,"[[11.88519153513312, 11.149906175984572, 24.68...",1.737253,2.699476,"[[0.309405217122374, 0.423656822095901, 0.1300...",1.739882,0.023540
12,checks_power,0.021717,0.792949,"[[1.5919799807306845e-06, 1.988819713005796e-0...",0.373699,0.979333,"[[0.19415779411792755, 0.6176232099533081, 0.9...",4.024445,9.568583,"[[6.072155475616455, 1.6028536558151245, 1.037...",9.027179,29.306009,"[[9.570508901496423, 9.840035609374072, 8.5479...",1.661446,2.613513,"[[0.27995896793789427, 0.4257514379232205, 0.2...",1.661446,0.020598
14,voter_id,0.020934,0.758443,"[[2.9317902772163507e-06, 1.8803488273988478e-...",0.374091,0.960822,"[[0.16825367510318756, 0.54316246509552, 0.960...",3.980074,9.581177,"[[6.1433634757995605, 1.800561785697937, 1.078...",8.382960,22.130172,"[[13.195672420886858, 9.479529852101985, 18.79...",1.785853,2.714000,"[[0.29952783683987444, 0.4505053279373396, 0.1...",1.778992,0.020221
15,felon_vote,0.026053,0.898643,"[[3.5442301395960385e-06, 1.517672626505373e-0...",0.385653,0.966474,"[[0.19312505424022675, 0.48426496982574463, 0....",3.896687,9.501941,"[[5.509015083312988, 2.0688445568084717, 1.064...",7.425496,28.316185,"[[11.374531073974097, 10.978968967377087, 25.6...",1.816200,2.757857,"[[0.3314989884252814, 0.4317587466152931, 0.13...",1.820162,0.027055
17,gun_bkg_chk,0.021121,0.772987,"[[5.857956693944288e-06, 2.590954682091251e-05...",0.371237,0.971974,"[[0.3647579848766327, 0.6237745881080627, 0.97...",3.997513,9.511414,"[[3.209433078765869, 1.568054437637329, 1.0549...",7.207960,22.411637,"[[11.240016207503729, 9.206191699077547, 10.79...",1.862673,2.803569,"[[0.35534009278731804, 0.4618626690749532, 0.1...",1.853799,0.021043
18,ar_ban,0.024071,0.868422,"[[1.3586850400315598e-05, 3.339662725920789e-0...",0.375196,0.928286,"[[0.13501203060150146, 0.7058539986610413, 0.9...",3.992704,9.494901,"[[6.6273345947265625, 1.367407202720642, 1.126...",7.172856,32.818926,"[[9.87936705648744, 9.2039883868499, 12.231082...",1.876521,2.812957,"[[0.6474497081316914, 0.45617442105224587, 0.1...",1.881053,0.023108
19,gun_imp,0.024582,0.841996,"[[2.9083034860377666e-06, 1.9339475329616107e-...",0.382881,0.960706,"[[0.1659712791442871, 0.5449243187904358, 0.96...",3.933775,9.568027,"[[6.131180763244629, 1.79714834690094, 1.07754...",7.923069,22.111932,"[[13.729475366269408, 9.574528515771444, 18.60...",1.811032,2.765317,"[[0.28668017235403753, 0.44939631794175866, 0....",1.818057,0.025483
20,death_pen,0.024079,0.866415,"[[2.7130681701237336e-06, 1.8867340259021148e-...",0.382362,0.962086,"[[0.16999351978302002, 0.5425742268562317, 0.9...",3.927944,9.586828,"[[6.005618095397949, 1.8006553649902344, 1.074...",8.606789,23.174872,"[[13.723439756977184, 9.471055776155012, 18.71...",1.753714,2.690963,"[[0.2798262527821356, 0.45269070823806007, 0.1...",1.752886,0.025193
21,police_force,0.022871,0.804305,"[[2.730449068621965e-06, 1.888609585876111e-05...",0.377082,0.962563,"[[0.16922591626644135, 0.5365079045295715, 0.9...",3.973455,9.610135,"[[6.039585590362549, 1.824636459350586, 1.0737...",8.581466,22.100371,"[[13.945473416646173, 9.497455122241508, 19.17...",1.746760,2.719909,"[[0.2778862834267668, 0.45527898563738295, 0.1...",1.752989,0.023670
23,ft_police,0.027261,1.002753,"[[4.057457044837065e-05, 2.2991984224063344e-0...",0.392749,0.935211,"[[0.07668562978506088, 0.5963419675827026, 0.8...",3.859323,9.608687,"[[8.622700691223145, 1.6233434677124023, 1.303...",8.871620,37.424029,"[[12.621536410736608, 9.673821223751089, 19.64...",1.775911,2.743293,"[[0.8237750178026679, 0.4927278492495377, 0.16...",1.763976,0.027746
24,abortion,0.032865,1.057970,"[[1.6911297279875726e-05, 2.8308455512160435e-...",0.401642,0.925919,"[[0.10060839354991913, 0.6717314720153809, 0.8...",3.805975,9.503211,"[[7.825969219207764, 1.4363796710968018, 1.227...",8.420710,38.348718,"[[11.241182459162072, 9.767055152227627, 23.52...",1.804190,2.729864,"[[0.6857544927400032, 0.449211377968518, 0.170...",1.801329,0.033925
25,scotus_abort,0.028969,1.008793,"[[9.286479325965047e-06, 3.452778037171811e-05...",0.402203,0.960638,"[[0.17670786380767822, 0.7131237983703613, 0.9...",3.803105,9.495669,"[[5.401723861694336, 1.3580939769744873, 1.066...",8.173680,24.196469,"[[9.310122335173837, 9.385545407014334, 8.6123...",1.808701,2.825768,"[[0.5640390588084496, 0.4571169284478878, 0.27...",1.819725,0.028799
26,govt_health,0.027320,0.995910,"[[9.192512152367271e-06, 3.498853766359389e-05...",0.391971,0.961124,"[[0.18323950469493866, 0.7171524167060852, 0.9...",3.866098,9.516212,"[[5.326966285705566, 1.3510159254074097, 1.065...",8.069312,23.361673,"[[9.366684444040073, 9.573563999590359, 8.8761...",1.793619,2.722737,"[[0.5625444008266697, 0.45425273927506155, 0.2...",1.786631,0.028061
27,obamacare,0.023027,0.876757,"[[1.2684164403253817e-06, 1.9583538232836872e-...",0.374060,0.979279,"[[0.2165163904428482, 0.6211954951286316, 0.97...",3.987169,9.512447,"[[5.3529887199401855, 1.591002345085144, 1.037...",7.693022,23.716503,"[[9.025821768888479, 9.760498182048284, 8.4185...",1.832869,2.837065,"[[0.26647742907633093, 0.42331357964024574, 0....",1.839590,0.023760
28,vax_school,0.020081,0.703005,"[[3.503614379951614e-06, 1.54613680933835e-05,...",0.371036,0.967771,"[[0.19158753752708435, 0.4819708466529846, 0.9...",4.007481,9.600602,"[[5.534343719482422, 2.082228899002075, 1.0620...",8.267914,35.645180,"[[11.643863988155626, 10.984004719335939, 25.9...",1.738791,2.677220,"[[0.32606364697996504, 0.43259583337043556, 0....",1.747253,0.020426
29,spend_school,0.021460,0.809505,"[[1.9000134443558636e-06, 1.6433083146694116e-...",0.375762,0.979131,"[[0.19238048791885376, 0.5402869582176208, 0.9...",3.963619,9.607778,"[[5.882139682769775, 1.8462255001068115, 1.038...",8.255704,24.778114,"[[10.129188561629817, 11.243449310421626, 9.60...",1.757754,2.704366,"[[0.30530805725394855, 0.4200680664477974, 0.1...",1.748618,0.021815
30,spend_welfare,0.023418,0.885826,"[[1.850218495746958e-06, 1.632171915844083e-05...",0.380714,0.978896,"[[0.1885007917881012, 0.5345645546913147, 0.97...",3.935075,9.596958,"[[6.0256757736206055, 1.8670849800109863, 1.03...",8.250167,28.371809,"[[10.12862121472005, 11.399043585554324, 9.507...",1.780082,2.701145,"[[0.3052595458315693, 0.41780343906195266, 0.1...",1.771740,0.022665
31,spend_poor,0.022631,0.881684,"[[1.56456474087463e-06, 2.011177275562659e-05,...",0.376006,0.978928,"[[0.18990039825439453, 0.6274124383926392, 0.9...",3.969202,9.593259,"[[6.249236106872559, 1.5773450136184692, 1.038...",7.798514,21.295807,"[[9.504272158172151, 9.965756769441095, 8.5814...",1.792660,2.707140,"[[0.2799926067971095, 0.4232977089527478, 0.21...",1.782303,0.023229
32,svc_spend,0.025716,0.949625,"[[3.500976163195446e-06, 1.5844394511077553e-0...",0.393909,0.967942,"[[0.19189298152923584, 0.5016502737998962, 0.9...",3.850271,9.616318,"[[5.458713531494141, 1.9893046617507935, 1.061...",8.635956,33.607067,"[[11.375004733277134, 11.321554228443134, 23.8...",1.739577,2.678922,"[[0.33100288235365816, 0.4233857453880906, 0.1...",1.745932,0.026500
33,millionaire_tax,0.022429,0.849353,"[[1.3377796676650178e-05, 3.3598429581616074e-...",0.377434,0.928253,"[[0.13684304058551788, 0.7058113217353821, 0.9...",3.967509,9.595161,"[[6.501305103302002, 1.3679825067520142, 1.126...",7.965515,27.938125,"[[9.828829314493257, 9.165138052918257, 11.852...",1.805544,2.780393,"[[0.6500556361503026, 0.4594420987892211, 0.20...",1.808392,0.021291
34,assist_black,0.032139,1.274407,"[[5.829183464811649e-06, 2.6230074581690133e-0...",0.395458,0.974654,"[[0.3556487560272217, 0.6306036114692688, 0.97...",3.845118,9.559222,"[[3.2112154960632324, 1.5472919940948486, 1.04...",6.763574,22.535219,"[[10.645603191635816, 9.209558671628912, 10.43...",1.853854,2.753869,"[[0.3712311746622517, 0.4613902936082504, 0.18...",1.856360,0.031065
35,black_favor,0.029204,0.854931,"[[9.279053301725071e-06, 3.4107306419173256e-0...",0.413753,0.961123,"[[0.18313893675804138, 0.7035840749740601, 0.9...",3.700118,9.433973,"[[5.302655220031738, 1.376558780670166, 1.0655...",6.592614,27.708941,"[[9.460792008933803, 9.581141207153028, 9.1011...",1.804285,2.723185,"[[0.5589669645896277, 0.46051563449340716, 0.2...",1.795878,0.028838
36,diversity,0.024302,0.936203,"[[9.174575097858906e-06, 3.535136056598276e-05...",0.376575,0.962118,"[[0.1870085448026657, 0.7228159308433533, 0.96...",3.982601,9.678030,"[[5.264114856719971, 1.3409512042999268, 1.063...",7.695245,25.475276,"[[9.389752764751407, 9.59491406104178, 8.90216...",1.783329,2.722165,"[[0.5609647282164721, 0.4481215329863322, 0.26...",1.793682,0.023888
37,trans_bath,0.028208,0.887997,"[[1.4374591046362184e-06, 1.969265031220857e-0...",0.392886,0.979037,"[[0.2091204971075058, 0.6273892521858215, 0.97...",3.834516,9.519260,"[[5.680170059204102, 1.5726648569107056, 1.037...",6.787040,21.941875,"[[9.244045706007487, 9.413375890040715, 8.5554...",1.840021,2.746969,"[[0.2782376795636381, 0.4248222413023387, 0.22...",1.843435,0.029242
38,trans_military,0.037917,1.290055,"[[1.0247138106933562e-06, 2.4249768102890812e-...",0.408654,0.961641,"[[0.36377596855163574, 0.6814725399017334, 0.9...",3.753603,9.450102,"[[3.62282657623291, 1.4520418643951416, 1.0665...",7.110183,36.369918,"[[11.106945057713247, 9.180040658641364, 9.171...",1.841814,2.738623,"[[0.18476474699926648, 0.4157413628644856, 0.2...",1.835031,0.037192
39,lg_job,0.038472,1.204815,"[[3.3793462534958962e-06, 1.5513569451286457e-...",0.409941,0.967057,"[[0.18254408240318298, 0.49668535590171814, 0....",3.711012,9.259749,"[[5.814991474151611, 2.0095577239990234, 1.063...",6.447903,27.131339,"[[12.030008256706616, 10.98004769947386, 25.37...",1.883839,2.757041,"[[0.3144863630542862, 0.43009583783463057, 0.1...",1.875377,0.038126
40,lg_marry,0.032455,1.071810,"[[2.8021138405165402e-06, 1.9053350115427747e-...",0.396173,0.962539,"[[0.16656500101089478, 0.5392372608184814, 0.9...",3.835214,9.511324,"[[6.204270839691162, 1.8134546279907227, 1.074...",7.117930,22.123337,"[[13.767465705217074, 9.355155261535096, 18.58...",1.843074,2.747387,"[[0.2855668882137497, 0.4577732133972912, 0.14...",1.851007,0.033136
41,lg_refuse_service,0.032093,1.051356,"[[1.8556827399152098e-06, 1.602451993676368e-0...",0.391190,0.978223,"[[0.192109614610672, 0.5260753631591797, 0.978...",3.862428,9.486054,"[[5.906894683837891, 1.8982605934143066, 1.040...",6.823556,30.659773,"[[10.272950469635216, 11.457001703122, 9.53391...",1.828013,2.722183,"[[0.30176688916683014, 0.4222171290051414, 0.1...",1.825417,0.033163
42,clim_imp,0.032024,1.173354,"[[7.5278258009348065e-06, 3.098340312135406e-0...",0.400699,0.971671,"[[0.3128409683704376, 0.6699128746986389, 0.97...",3.810750,9.509732,"[[3.6435341835021973, 1.455571174621582, 1.050...",7.296988,22.563092,"[[10.741985329345658, 9.253481517180088, 8.858...",1.835516,2.723213,"[[0.4419106734109767, 0.4639695656896881, 0.24...",1.827551,0.031526
43,env_bus,0.025421,0.997896,"[[5.7523479881638195e-06, 2.702122219488956e-0...",0.388041,0.973801,"[[0.3607326149940491, 0.6472526788711548, 0.97...",3.895967,9.604535,"[[3.198345899581909, 1.5060926675796509, 1.051...",8.467678,22.478902,"[[11.182530599872305, 9.087829462044484, 10.77...",1.758308,2.722292,"[[0.35635949977278225, 0.4577203910185289, 0.1...",1.757049,0.026529
44,ghg_emiss,0.025755,0.876454,"[[1.2785500075551681e-05, 3.418413325562142e-0...",0.383554,0.929377,"[[0.13176020979881287, 0.71687912940979, 0.929...",3.926666,9.529681,"[[6.650828838348389, 1.3470689058303833, 1.123...",7.792564,33.937192,"[[9.93503196826169, 9.346317138682798, 11.4327...",1.814586,2.750471,"[[0.6362254875960676, 0.45378643029187893, 0.2...",1.805613,0.024617
45,def_spend,0.022673,0.822885,"[[3.48407252204197e-06, 1.6007972590159625e-05...",0.379546,0.967847,"[[0.18188020586967468, 0.5011129975318909, 0.9...",3.948885,9.630182,"[[5.769799709320068, 1.9924018383026123, 1.061...",8.984374,26.754954,"[[12.08746523226838, 11.416842048449219, 23.96...",1.720307,2.668189,"[[0.31530808075293587, 0.4259615435425924, 0.1...",1.712836,0.023281
46,mil_force,0.029667,1.104165,"[[1.836891442508204e-06, 1.6035482985898852e-0...",0.400768,0.976078,"[[0.19037029147148132, 0.5298465490341187, 0.9...",3.804866,9.516433,"[[5.985666275024414, 1.882015347480774, 1.0446...",9.356407,37.671142,"[[10.005034139798937, 11.504956817943409, 9.91...",1.741231,2.707168,"[[0.3046946878084352, 0.420773505463656, 0.192...",1.734760,0.028899
47,free_trade,0.024190,0.880683,"[[6.668550668109674e-06, 3.138215470244177e-05...",0.388355,0.972799,"[[0.29586175084114075, 0.6802919507026672, 0.9...",3.882416,9.615048,"[[3.7708075046539307, 1.4309754371643066, 1.04...",9.124732,26.365295,"[[10.64371317505406, 9.251949015876269, 8.8775...",1.725123,2.713119,"[[0.431685748053691, 0.4628459115227862, 0.237...",1.716880,0.024610
48,intl_trade_job,0.034337,1.362772,"[[3.4689212498051347e-06, 1.5752189938211814e-...",0.404382,0.966123,"[[0.17646385729312897, 0.5053104758262634, 0.9...",3.787069,9.484663,"[[5.875414848327637, 1.9677989482879639, 1.065...",9.314196,41.601747,"[[12.388023506012718, 11.454345099822145, 26.7...",1.731186,2.717328,"[[0.3098216726953322, 0.4220216157284876, 0.13...",1.727084,0.033344
49,ft_trans,0.040814,1.197736,"[[3.8899408536963165e-05, 2.354241587454453e-0...",0.407275,0.928754,"[[0.07711529731750488, 0.6074524521827698, 0.8...",3.750261,9.495549,"[[8.62661361694336, 1.588810682296753, 1.30316...",6.434642,30.008645,"[[12.672762978811905, 9.608019805456118, 19.06...",1.877632,2.793604,"[[0.8131192537149828, 0.4959838333805375, 0.16...",1.868886,0.040609
50,ft_fem,0.041223,1.269046,"[[5.0335158448433504e-05, 2.340918217669241e-0...",0.410275,0.943262,"[[0.0817711353302002, 0.5838194489479065, 0.78...",3.752512,9.533710,"[[8.464189529418945, 1.6743913888931274, 1.484...",7.335004,26.629448,"[[11.414453459432472, 9.535838706898545, 19.35...",1.797567,2.673523,"[[0.8779097806159355, 0.514204116482375, 0.202...",1.790078,0.040618
51,ft_sci,0.031472,1.114861,"[[5.060043986304663e-05, 2.3795957531547174e-0...",0.398684,0.929582,"[[0.08134536445140839, 0.5913048386573792, 0.7...",3.831941,9.512999,"[[8.4795503616333, 1.6488490104675293, 1.48347...",8.431786,40.887119,"[[11.407198863432486, 9.513216410453067, 19.62...",1.766211,2.674950,"[[0.8773437732929301, 0.5180607681792132, 0.19...",1.766259,0.030344

In [47]:
anes_path = "policy_polarization.csv"

df_anes = pd.read_csv(anes_path)
df_anes = df_anes.rename(columns={"issue": "Topic", "mahalanobis_distance": "ANES_Mahalanobis", "variance": "ANES_Variance"})
df_anes

,Topic,ANES_Mahalanobis,ANES_Variance,area,explanation
0,imm_unauth,1.007885,0.087450,Immigration,Policy preferences regarding unauthorized/undo...
1,birthright,1.036311,0.129074,Immigration,Support for birthright citizenship for childre...
2,paid_leave,0.713889,0.072350,Labor,Support for paid parental/family leave policie...
3,trump_corr,1.637288,0.093275,Institutions,Perceptions of corruption involving Donald Tru...
4,journ_access,0.834154,0.104073,Institutions,Support for press/journalist access to governm...
5,gun_bkg_chk,0.497340,0.050344,Guns,Support for background checks on gun purchases...
6,illeg_child,0.948134,0.075581,Immigration,Views on how the U.S. should handle children o...
7,death_pen,0.999484,0.147272,Crime,Support for the death penalty/capital punishme...
8,abortion,1.232532,0.132176,Abortion,Attitudes toward abortion legality and access.
9,scotus_abort,1.413303,0.120520,Abortion,Views on Supreme Court decisions and judicial ...
10,ar_ban,0.940938,0.157338,Guns,Support for banning assault rifles/assault wea...
11,econ_now,1.273292,0.076451,Economy,Evaluation of the current national economy (re...
12,voter_id,1.190985,0.104792,Elections,Support for voter identification requirements ...
13,felon_vote,0.820345,0.106281,Elections,Support for restoring or extending voting righ...
14,vax_school,0.404883,0.087412,Health,Support for school vaccination requirements fo...
15,spend_border,1.550767,0.113009,Immigration,Preferences for federal spending levels on bor...
16,spend_welfare,1.274814,0.094927,Redistribution,Preferences for federal spending on welfare pr...
17,spend_poor,1.176851,0.077242,Redistribution,Preferences for federal spending to aid the po...
18,spend_school,0.881059,0.077125,Education,Preferences for federal spending on public sch...
19,checks_power,0.226124,0.048869,Institutions,Views on checks and balances and whether branc...
20,border_wall,2.303004,0.169928,Immigration,Support for constructing a barrier/wall at the...
21,trans_bath,1.276135,0.161220,LGBTQ,Views on transgender bathroom access policies.
22,trans_military,1.205945,0.104121,LGBTQ,Views on transgender people serving in the U.S...
23,lg_job,0.602085,0.088672,LGBTQ,Views on legal protections against job discrim...
24,lg_marry,0.602085,0.088672,LGBTQ,Support for same-sex marriage / marriage right...
25,lg_refuse_service,1.243084,0.165661,LGBTQ,Views on refusing service to same-sex couples.
26,police_force,1.006237,0.055553,Policing,Support for police use of force / policing pra...
27,assist_black,1.623140,0.112476,Race,Support for government assistance to Black Ame...
28,black_favor,1.344375,0.135618,Race,Attitudes toward whether Black people should r...
29,diversity,0.858743,0.075308,Race,Attitudes toward diversity initiatives and/or ...
30,job_gov_guar,1.478903,0.105467,Labor,Support for a government-guaranteed job progra...
31,govt_health,1.556133,0.124644,Health,Support for government-provided health insuran...
32,obamacare,2.408148,0.151637,Health,Attitudes toward the Affordable Care Act (ACA/...
33,svc_spend,1.505273,0.089223,Redistribution,Preferences for government spending on service...
34,def_spend,1.060406,0.084489,Defense,Preferences for government spending on nationa...
35,urban_unrest,1.919903,0.147623,Policing,"Concern about urban unrest, protests, and diso..."
36,clim_imp,1.565396,0.114112,Climate,Importance assigned to climate change as an is...
37,rus_interf,1.716627,0.152379,Institutions,Concern about Russian interference in U.S. ele...
38,ft_trans,1.069882,0.076328,LGBTQ,Feeling thermometer rating toward transgender ...
39,ft_union,0.963094,0.057614,Labor,Feeling thermometer rating toward labor unions.
40,ft_fem,1.355457,0.071815,Gender,Feeling thermometer rating toward feminists.
41,ft_sci,0.922126,0.040673,Institutions,Feeling thermometer rating toward scientists.
42,ft_police,1.106227,0.063131,Policing,Feeling thermometer rating toward police.
43,env_bus,1.599410,0.109050,Climate,Tradeoff between environmental protection and ...
44,ghg_emiss,1.169356,0.097797,Climate,Support for regulating greenhouse gas emission...
45,gun_imp,0.274799,0.069836,Guns,Importance placed on gun regulation as a polit...
46,mil_force,0.349896,0.049060,ForeignPolicy,Support for the use of U.S. military force int...
47,millionaire_tax,0.918373,0.156521,Redistribution,Support for taxes targeting millionaires.
48,min_wage,1.008874,0.071326,Labor,Support for raising the minimum wage / minimum...
49,free_trade,0.284479,0.059593,Trade,Support for free trade policies and reducing t...
50,intl_trade_job,0.153209,0.065719,Trade,Beliefs about international trade’s impact on ...

## Comparing Party Polarization between LLM and ANES

In [34]:

# Keep only Topic + Avg_Mahalanobis from LLM results
# rename columns

df_llm = df_res[["Topic", "Avg_Mahalanobis", "Avg_Total_Dispersion"]].copy()

# Inner join ensures exact key matching
df_merged = df_llm.merge(
    df_anes,
    left_on="Topic",
    right_on="Topic",
    how="inner"
)

pearson_corr = df_merged["Avg_Mahalanobis"].corr(
    df_merged["ANES_Mahalanobis"],
    method="pearson"
)

print(f"Pearson correlation: {pearson_corr:.3f}")
spearman_corr = df_merged["Avg_Mahalanobis"].corr(
    df_merged["ANES_Mahalanobis"],
    method="spearman"
)

print(f"Spearman correlation: {spearman_corr:.3f}")
df_merged["LLM_rank"] = df_merged["Avg_Mahalanobis"].rank(ascending=False)
df_merged["ANES_rank"] = df_merged["ANES_Mahalanobis"].rank(ascending=False)

print(df_merged.sort_values("Avg_Mahalanobis", ascending=False).to_markdown())

Pearson correlation: 0.254
Spearman correlation: 0.178
|    | Topic             |   Avg_Mahalanobis |   Avg_Total_Dispersion |   ANES_Mahalanobis |   ANES_Variance | area           | explanation                                                                                       |   LLM_rank |   ANES_rank |
|---:|:------------------|------------------:|-----------------------:|-------------------:|----------------:|:---------------|:--------------------------------------------------------------------------------------------------|-----------:|------------:|
| 33 | lg_job            |           1.88384 |              0.0384717 |           0.602085 |       0.0886719 | LGBTQ          | Views on legal protections against job discrimination for gay/lesbian people.                     |          1 |        38.5 |
| 43 | ft_trans          |           1.87763 |              0.0408137 |           1.06988  |       0.0763283 | LGBTQ          | Feeling thermometer rating toward transgender people.                                             |          2 |        21   |
| 13 | ar_ban            |           1.87652 |              0.0240712 |           0.940938 |       0.157338  | Guns           | Support for banning assault rifles/assault weapons.                                               |          3 |        30   |
| 12 | gun_bkg_chk       |           1.86267 |              0.0211212 |           0.49734  |       0.0503443 | Guns           | Support for background checks on gun purchases (including universal background checks).           |          4 |        40   |
| 28 | assist_black      |           1.85385 |              0.0321392 |           1.62314  |       0.112476  | Race           | Support for government assistance to Black Americans / addressing racial inequality.              |          5 |         2   |
|  4 | paid_leave        |           1.84904 |              0.019677  |           0.713889 |       0.0723504 | Labor          | Support for paid parental/family leave policies for new parents and caregivers.                   |          6 |        37   |
| 34 | lg_marry          |           1.84307 |              0.0324549 |           0.602085 |       0.0886719 | LGBTQ          | Support for same-sex marriage / marriage rights for gay and lesbian couples.                      |          7 |        38.5 |
| 32 | trans_military    |           1.84181 |              0.0379166 |           1.20594  |       0.104121  | LGBTQ          | Views on transgender people serving in the U.S. military.                                         |          8 |        16   |
| 31 | trans_bath        |           1.84002 |              0.028208  |           1.27614  |       0.16122   | LGBTQ          | Views on transgender bathroom access policies.                                                    |          9 |        12   |
| 36 | clim_imp          |           1.83552 |              0.0320244 |           1.5654   |       0.114112  | Climate        | Importance assigned to climate change as an issue.                                                |         10 |         4   |
| 21 | obamacare         |           1.83287 |              0.0230267 |           2.40815  |       0.151637  | Health         | Attitudes toward the Affordable Care Act (ACA/‘Obamacare’).                                       |         11 |         1   |
| 35 | lg_refuse_service |           1.82801 |              0.0320925 |           1.24308  |       0.165661  | LGBTQ          | Views on refusing service to same-sex couples.                                                    |         12 |        14   |
|  0 | imm_unauth        |           1.82036 |              0.0254125 |           1.00789  |       0.0874501 | Immigration    | Policy preferences regarding unauthorized/undocumented immigrants.                                |         13 |        25   |
|  2 | illeg_child       |           1.81662 |              0.0299717 |           0.948134 |       0.0755809 | Immigration    | Views on how the U.S. should handle children of undocumented immigrants.                          |         14 |        29   |
| 11 | felon_vote        |           1.8162  |              0.0260528 |           0.820345 |       0.106281  | Elections      | Support for restoring or extending voting rights to people with felony convictions.               |         15 |        36   |
| 38 | ghg_emiss         |           1.81459 |              0.0257553 |           1.16936  |       0.097797  | Climate        | Support for regulating greenhouse gas emissions / carbon emissions.                               |         16 |        19   |
| 14 | gun_imp           |           1.81103 |              0.024582  |           0.274799 |       0.069836  | Guns           | Importance placed on gun regulation as a political issue.                                         |         17 |        44   |
| 19 | scotus_abort      |           1.8087  |              0.0289691 |           1.4133   |       0.12052   | Abortion       | Views on Supreme Court decisions and judicial intervention related to abortion.                   |         18 |         9   |
| 27 | millionaire_tax   |           1.80554 |              0.022429  |           0.918373 |       0.156521  | Redistribution | Support for taxes targeting millionaires.                                                         |         19 |        32   |
| 29 | black_favor       |           1.80428 |              0.0292043 |           1.34437  |       0.135618  | Race           | Attitudes toward whether Black people should receive favoritism in society/politics.              |         20 |        11   |
| 18 | abortion          |           1.80419 |              0.0328654 |           1.23253  |       0.132176  | Abortion       | Attitudes toward abortion legality and access.                                                    |         21 |        15   |
| 44 | ft_fem            |           1.79757 |              0.0412225 |           1.35546  |       0.0718147 | Gender         | Feeling thermometer rating toward feminists.                                                      |         22 |        10   |
| 20 | govt_health       |           1.79362 |              0.02732   |           1.55613  |       0.124644  | Health         | Support for government-provided health insurance (e.g., single payer, public provision).          |         23 |         5   |
| 25 | spend_poor        |           1.79266 |              0.0226309 |           1.17685  |       0.0772418 | Redistribution | Preferences for federal spending to aid the poor / anti-poverty programs.                         |         24 |        18   |
|  7 | ft_union          |           1.79248 |              0.0257303 |           0.963094 |       0.0576139 | Labor          | Feeling thermometer rating toward labor unions.                                                   |         25 |        28   |
|  6 | min_wage          |           1.79126 |              0.0213851 |           1.00887  |       0.0713263 | Labor          | Support for raising the minimum wage / minimum-wage policy changes.                               |         26 |        24   |
| 10 | voter_id          |           1.78585 |              0.0209336 |           1.19098  |       0.104792  | Elections      | Support for voter identification requirements (e.g., photo ID laws).                              |         27 |        17   |
|  1 | birthright        |           1.78352 |              0.0253518 |           1.03631  |       0.129074  | Immigration    | Support for birthright citizenship for children born in the U.S. to non-citizen parents.          |         28 |        23   |
| 30 | diversity         |           1.78333 |              0.0243022 |           0.858743 |       0.0753077 | Race           | Attitudes toward diversity initiatives and/or the importance of diversity.                        |         29 |        34   |
| 24 | spend_welfare     |           1.78008 |              0.0234181 |           1.27481  |       0.0949275 | Redistribution | Preferences for federal spending on welfare programs / public assistance.                         |         30 |        13   |
| 17 | ft_police         |           1.77591 |              0.0272611 |           1.10623  |       0.063131  | Policing       | Feeling thermometer rating toward police.                                                         |         31 |        20   |
|  5 | job_gov_guar      |           1.77582 |              0.0258743 |           1.4789   |       0.105467  | Labor          | Support for a government-guaranteed job program (public employment guarantee).                    |         32 |         8   |
| 45 | ft_sci            |           1.76621 |              0.0314719 |           0.922126 |       0.040673  | Institutions   | Feeling thermometer rating toward scientists.                                                     |         33 |        31   |
| 37 | env_bus           |           1.75831 |              0.0254214 |           1.59941  |       0.10905   | Climate        | Tradeoff between environmental protection and business regulation/deregulation.                   |         34 |         3   |
| 23 | spend_school      |           1.75775 |              0.0214599 |           0.881059 |       0.0771246 | Education      | Preferences for federal spending on public schools and K–12 education.                            |         35 |        33   |
|  3 | spend_border      |           1.75659 |              0.023667  |           1.55077  |       0.113009  | Immigration    | Preferences for federal spending levels on border security.                                       |         36 |         6   |
| 15 | death_pen         |           1.75371 |              0.0240788 |           0.999484 |       0.147272  | Crime          | Support for the death penalty/capital punishment for serious crimes.                              |         37 |        27   |
| 16 | police_force      |           1.74676 |              0.0228715 |           1.00624  |       0.0555525 | Policing       | Support for police use of force / policing practices.                                             |         38 |        26   |
| 40 | mil_force         |           1.74123 |              0.0296673 |           0.349896 |       0.0490599 | ForeignPolicy  | Support for the use of U.S. military force internationally.                                       |         39 |        42   |
| 26 | svc_spend         |           1.73958 |              0.0257164 |           1.50527  |       0.0892234 | Redistribution | Preferences for government spending on services (general service provision).                      |         40 |         7   |
| 22 | vax_school        |           1.73879 |              0.0200808 |           0.404883 |       0.0874123 | Health         | Support for school vaccination requirements for children attending school.                        |         41 |        41   |
|  8 | journ_access      |           1.73725 |              0.0246089 |           0.834154 |       0.104073  | Institutions   | Support for press/journalist access to government officials and government transparency norms.    |         42 |        35   |
| 42 | intl_trade_job    |           1.73119 |              0.0343374 |           0.153209 |       0.0657186 | Trade          | Beliefs about international trade’s impact on jobs (job creation/loss from trade).                |         43 |        46   |
| 41 | free_trade        |           1.72512 |              0.0241897 |           0.284479 |       0.0595934 | Trade          | Support for free trade policies and reducing trade barriers.                                      |         44 |        43   |
| 39 | def_spend         |           1.72031 |              0.0226734 |           1.06041  |       0.0844886 | Defense        | Preferences for government spending on national defense and the military.                         |         45 |        22   |
|  9 | checks_power      |           1.66145 |              0.0217173 |           0.226124 |       0.048869  | Institutions   | Views on checks and balances and whether branches of government should limit one another’s power. |         46 |        45   |

### Can we look at what subset correlate well and try to reverse engineer what might be the issue ...?

In [38]:
# Sample subsets and find best correlations
import random
random.seed(42)
np.random.seed(42)

n_iterations = 10000
sample_size = 25
results = []

for i in range(n_iterations):
    # Sample 20 random issues
    sampled_df = df_merged.sample(n=sample_size, random_state=i)
    
    # Calculate correlation
    pearson = sampled_df["Avg_Mahalanobis"].corr(sampled_df["ANES_Mahalanobis"], method="pearson")
    spearman = sampled_df["Avg_Mahalanobis"].corr(sampled_df["ANES_Mahalanobis"], method="spearman")
    
    results.append({
        'iteration': i,
        'pearson': pearson,
        'spearman': spearman,
        'topics': sampled_df['Topic'].tolist()
    })

# Convert to DataFrame and sort by Pearson correlation
df_results = pd.DataFrame(results)
df_results_sorted = df_results.sort_values('pearson', ascending=False)

# Get top 5
top_10 = df_results_sorted.head(10)

print("Top 10 iterations by Pearson correlation:")
for idx, row in top_10.iterrows():
    print(f"\nIteration {row['iteration']}: Pearson={row['pearson']:.3f}, Spearman={row['spearman']:.3f}")
    print(f"Topics: {', '.join(row['topics'])}")

Top 10 iterations by Pearson correlation:

Iteration 3741: Pearson=0.702, Spearman=0.675
Topics: intl_trade_job, felon_vote, vax_school, black_favor, def_spend, paid_leave, voter_id, trans_military, checks_power, spend_school, trans_bath, assist_black, ft_union, ft_fem, ft_police, diversity, free_trade, ft_sci, mil_force, abortion, lg_refuse_service, clim_imp, obamacare, imm_unauth, journ_access

Iteration 7023: Pearson=0.701, Spearman=0.724
Topics: checks_power, imm_unauth, spend_school, ft_fem, ft_police, clim_imp, def_spend, scotus_abort, min_wage, vax_school, ft_trans, trans_bath, ft_sci, mil_force, ft_union, illeg_child, lg_refuse_service, millionaire_tax, spend_poor, assist_black, trans_military, journ_access, spend_welfare, obamacare, free_trade

Iteration 1701: Pearson=0.696, Spearman=0.576
Topics: checks_power, ft_union, mil_force, abortion, voter_id, spend_school, assist_black, lg_refuse_service, ft_fem, journ_access, ft_sci, ar_ban, ghg_emiss, free_trade, felon_vote, job_gov_guar, vax_school, clim_imp, spend_poor, birthright, black_favor, imm_unauth, trans_bath, millionaire_tax, def_spend

Iteration 8997: Pearson=0.678, Spearman=0.695
Topics: imm_unauth, spend_poor, mil_force, checks_power, millionaire_tax, felon_vote, intl_trade_job, assist_black, spend_school, police_force, clim_imp, govt_health, vax_school, trans_bath, obamacare, ar_ban, journ_access, def_spend, lg_refuse_service, ft_police, diversity, birthright, trans_military, ft_union, free_trade

Iteration 8132: Pearson=0.676, Spearman=0.578
Topics: spend_poor, lg_refuse_service, ft_union, intl_trade_job, checks_power, ghg_emiss, trans_bath, police_force, obamacare, spend_welfare, imm_unauth, env_bus, diversity, scotus_abort, clim_imp, trans_military, ft_fem, abortion, black_favor, mil_force, illeg_child, vax_school, ft_police, ft_trans, free_trade

Iteration 7366: Pearson=0.673, Spearman=0.655
Topics: scotus_abort, diversity, mil_force, ft_trans, spend_school, millionaire_tax, min_wage, obamacare, govt_health, free_trade, lg_refuse_service, def_spend, ft_sci, checks_power, felon_vote, black_favor, voter_id, abortion, intl_trade_job, trans_military, journ_access, illeg_child, job_gov_guar, clim_imp, assist_black

Iteration 937: Pearson=0.671, Spearman=0.612
Topics: death_pen, ghg_emiss, min_wage, diversity, abortion, illeg_child, journ_access, spend_welfare, imm_unauth, voter_id, trans_bath, trans_military, birthright, intl_trade_job, obamacare, free_trade, scotus_abort, clim_imp, ft_union, spend_school, vax_school, assist_black, spend_poor, paid_leave, millionaire_tax

Iteration 1691: Pearson=0.671, Spearman=0.655
Topics: mil_force, abortion, clim_imp, diversity, lg_refuse_service, ft_police, checks_power, trans_bath, ghg_emiss, spend_poor, police_force, illeg_child, assist_black, voter_id, black_favor, imm_unauth, intl_trade_job, vax_school, free_trade, death_pen, ft_trans, job_gov_guar, def_spend, env_bus, spend_school

Iteration 2435: Pearson=0.664, Spearman=0.575
Topics: lg_refuse_service, trans_military, mil_force, scotus_abort, illeg_child, job_gov_guar, spend_welfare, trans_bath, voter_id, checks_power, ft_trans, intl_trade_job, journ_access, birthright, imm_unauth, ft_union, vax_school, ghg_emiss, ft_fem, free_trade, clim_imp, min_wage, lg_marry, police_force, spend_school

Iteration 4200: Pearson=0.656, Spearman=0.553
Topics: abortion, imm_unauth, spend_welfare, mil_force, millionaire_tax, ft_fem, clim_imp, diversity, ghg_emiss, free_trade, min_wage, checks_power, trans_bath, ft_union, ft_sci, police_force, svc_spend, spend_poor, birthright, vax_school, env_bus, black_favor, def_spend, intl_trade_job, obamacare

In [35]:
def compare_standardized_columns(df, col1, col2, group_by='area'):
    """
    Demean and standardize two columns separately, calculate their difference,
    and group by specified column.
    
    Parameters:
    - df: DataFrame containing the data
    - col1: First column name to standardize
    - col2: Second column name to standardize
    - group_by: Column name to group results by (default 'area')
    
    Returns:
    - Modified DataFrame with normalized columns and difference
    """
    # Create a copy to avoid modifying original
    df_work = df.copy()
    
    # Demean and standardize each column separately
    mean1 = df_work[col1].mean()
    std1 = df_work[col1].std()
    mean2 = df_work[col2].mean()
    std2 = df_work[col2].std()
    
    col1_norm = col1 + '_norm'
    col2_norm = col2 + '_norm'
    
    df_work[col1_norm] = (df_work[col1] - mean1) / std1
    df_work[col2_norm] = (df_work[col2] - mean2) / std2
    
    # Calculate difference between standardized columns
    df_work['diff'] = df_work[col1_norm] - df_work[col2_norm]
    
    # Calculate mean differences by group
    group_diff = df_work.groupby(group_by).agg({
        'diff': ['mean', 'count']
    }).round(4)
    
    group_diff.columns = ['mean_diff', 'n_topics']
    group_diff = group_diff.sort_values('mean_diff', ascending=False)
    
    print(f"Standardized Differences by {group_by}:")
    print(group_diff)
    
    print("\nDetailed breakdown:")
    print(df_work[['Topic', group_by, col1_norm, col2_norm, 'diff']].sort_values('diff', ascending=False).to_markdown())
    
    return df_work

# Compare Avg_Total_Dispersion (LLM) with ANES_Variance
df_merged = compare_standardized_columns(df_merged, 'Avg_Mahalanobis', 'ANES_Mahalanobis', group_by='area')

Standardized Differences by area:
                mean_diff  n_topics
area
Guns               2.2399         3
LGBTQ              1.3205         6
Trade              0.4599         2
ForeignPolicy      0.4402         1
Elections          0.2223         2
Labor              0.1659         4
Race              -0.1165         3
Immigration       -0.2141         4
Abortion          -0.3796         2
Education         -0.4103         1
Gender            -0.6406         1
Institutions      -0.6758         3
Redistribution    -0.7144         4
Policing          -0.7302         2
Climate           -0.7316         3
Crime             -0.7631         1
Health            -1.0616         3
Defense           -1.6063         1

Detailed breakdown:
|    | Topic             | area           |   Avg_Mahalanobis_norm |   ANES_Mahalanobis_norm |        diff |
|---:|:------------------|:---------------|-----------------------:|------------------------:|------------:|
| 33 | lg_job            | LGBTQ          |             1.90278    |            -0.980125    |  2.88291    |
| 12 | gun_bkg_chk       | Guns           |             1.45571    |            -1.21666     |  2.67237    |
| 14 | gun_imp           | Guns           |             0.364932   |            -1.71921     |  2.08414    |
| 34 | lg_marry          | LGBTQ          |             1.04173    |            -0.980125    |  2.02185    |
| 13 | ar_ban            | Guns           |             1.74822    |            -0.214919    |  1.96314    |
|  4 | paid_leave        | Labor          |             1.16775    |            -0.727646    |  1.89539    |
| 43 | ft_trans          | LGBTQ          |             1.77168    |             0.076265    |  1.69542    |
| 11 | felon_vote        | Elections      |             0.47408    |            -0.487246    |  0.961326   |
|  2 | illeg_child       | Immigration    |             0.482985   |            -0.19867     |  0.681655   |
| 42 | intl_trade_job    | Trade          |            -1.3216     |            -1.99379     |  0.672184   |
| 32 | trans_military    | LGBTQ          |             1.01512    |             0.383524    |  0.631597   |
|  0 | imm_unauth        | Immigration    |             0.561993   |            -0.0637384   |  0.625732   |
| 27 | millionaire_tax   | Redistribution |             0.249016   |            -0.265877    |  0.514893   |
| 40 | mil_force         | ForeignPolicy  |            -1.10943    |            -1.54962     |  0.440196   |
| 31 | trans_bath        | LGBTQ          |             0.977253   |             0.54203     |  0.435222   |
| 22 | vax_school        | Health         |            -1.16097    |            -1.42545     |  0.264479   |
| 35 | lg_refuse_service | LGBTQ          |             0.723607   |             0.467393    |  0.256214   |
| 41 | free_trade        | Trade          |            -1.44968    |            -1.69735     |  0.247675   |
| 30 | diversity         | Race           |            -0.220218   |            -0.400534    |  0.180317   |
| 38 | ghg_emiss         | Climate        |             0.439988   |             0.3009      |  0.139088   |
|  7 | ft_union          | Labor          |            -0.0269698  |            -0.164887    |  0.137917   |
|  6 | min_wage          | Labor          |            -0.0527032  |            -0.0615044   |  0.00880118 |
| 28 | assist_black      | Race           |             1.26944    |             1.32564     | -0.056209   |
|  1 | birthright        | Immigration    |            -0.216277   |             0.000452874 | -0.21673    |
| 18 | abortion          | Abortion       |             0.220404   |             0.443563    | -0.22316    |
| 36 | clim_imp          | Climate        |             0.882089   |             1.19525     | -0.313157   |
| 45 | ft_sci            | Institutions   |            -0.581807   |            -0.257402    | -0.324404   |
| 25 | spend_poor        | Redistribution |            -0.0231407  |             0.317823    | -0.340964   |
| 23 | spend_school      | Education      |            -0.760431   |            -0.350141    | -0.41029    |
| 29 | black_favor       | Race           |             0.222414   |             0.69613     | -0.473715   |
| 10 | voter_id          | Elections      |            -0.166908   |             0.349741    | -0.516649   |
| 17 | ft_police         | Policing       |            -0.376912   |             0.158338    | -0.53525    |
| 19 | scotus_abort      | Abortion       |             0.315689   |             0.851785    | -0.536096   |
| 44 | ft_fem            | Gender         |             0.0805169  |             0.721157    | -0.64064    |
|  8 | journ_access      | Institutions   |            -1.19346    |            -0.456061    | -0.737398   |
| 15 | death_pen         | Crime          |            -0.845763   |            -0.0827108   | -0.763052   |
| 24 | spend_welfare     | Redistribution |            -0.288807   |             0.539046    | -0.827853   |
| 16 | police_force      | Policing       |            -0.992657   |            -0.0674592   | -0.925198   |
|  9 | checks_power      | Institutions   |            -2.79469    |            -1.82913     | -0.965559   |
| 20 | govt_health       | Health         |            -0.00286823 |             1.17433     | -1.1772     |
|  5 | job_gov_guar      | Labor          |            -0.378772   |             0.999925    | -1.3787     |
| 39 | def_spend         | Defense        |            -1.5514     |             0.0548644   | -1.60627    |
|  3 | spend_border      | Immigration    |            -0.78498    |             1.16221     | -1.94719    |
| 37 | env_bus           | Climate        |            -0.74874    |             1.27206     | -2.0208     |
| 26 | svc_spend         | Redistribution |            -1.14438    |             1.05947     | -2.20386    |
| 21 | obamacare         | Health         |             0.826176   |             3.09837     | -2.27219    |

In [54]:
# restrict area to some areas
df_subset = df_merged[df_merged['area'].isin(['Institutions', 'Policing', 'Labor', 'Race', "Immigration", "Abortion", "Education"])]
pearson_corr_subset = df_subset["Avg_Mahalanobis"].corr(
    df_subset["ANES_Mahalanobis"],
    method="pearson"
)
print(f"\nSubset Pearson correlation: {pearson_corr_subset:.3f}")
spearman_corr_subset = df_subset["Avg_Mahalanobis"].corr(
    df_subset["ANES_Mahalanobis"],
    method="spearman"
)
print(f"Subset Spearman correlation: {spearman_corr_subset:.3f}")

Subset Pearson correlation: 0.518
Subset Spearman correlation: 0.305

## Comparing Total Variance between ANES and LLM

In [40]:

pearson_corr = df_merged["Avg_Total_Dispersion"].corr(
    df_merged["ANES_Variance"],
    method="pearson"
)

print(f"Pearson correlation: {pearson_corr:.3f}")
spearman_corr = df_merged["Avg_Total_Dispersion"].corr(
    df_merged["ANES_Variance"],
    method="spearman"
)

print(f"Spearman correlation: {spearman_corr:.3f}")
df_merged["LLM_rank"] = df_merged["Avg_Total_Dispersion"].rank(ascending=False)
df_merged["ANES_rank"] = df_merged["ANES_Variance"].rank(ascending=False)

df_merged.sort_values("Avg_Total_Dispersion", ascending=False)

Pearson correlation: 0.023
Spearman correlation: 0.126

,Topic,Avg_Mahalanobis,Avg_Total_Dispersion,ANES_Mahalanobis,ANES_Variance,area,explanation,LLM_rank,ANES_rank,Avg_Mahalanobis_norm,ANES_Mahalanobis_norm,diff,Avg_Total_Dispersion_norm,ANES_Variance_norm
44,ft_fem,1.797567,0.041223,1.355457,0.071815,Gender,Feeling thermometer rating toward feminists.,1.0,35.0,0.080517,0.721157,3.348773,2.612767,-0.736006
43,ft_trans,1.877632,0.040814,1.069882,0.076328,LGBTQ,Feeling thermometer rating toward transgender ...,2.0,31.0,1.771682,0.076265,3.137853,2.537358,-0.600496
33,lg_job,1.883839,0.038472,0.602085,0.088672,LGBTQ,Views on legal protections against job discrim...,3.0,24.5,1.902781,-0.980125,2.335274,2.105366,-0.229908
32,trans_military,1.841814,0.037917,1.205945,0.104121,LGBTQ,Views on transgender people serving in the U.S...,4.0,19.0,1.015122,0.383524,1.769062,2.002983,0.233921
42,intl_trade_job,1.731186,0.034337,0.153209,0.065719,Trade,Beliefs about international trade’s impact on ...,5.0,38.0,-1.321603,-1.993787,2.261803,1.342776,-0.919027
18,abortion,1.804190,0.032865,1.232532,0.132176,Abortion,Attitudes toward abortion legality and access.,6.0,8.0,0.220404,0.443563,-0.004925,1.071264,1.076189
34,lg_marry,1.843074,0.032455,0.602085,0.088672,LGBTQ,Support for same-sex marriage / marriage right...,7.0,24.5,1.041728,-0.980125,1.225455,0.995547,-0.229908
28,assist_black,1.853854,0.032139,1.623140,0.112476,Race,Support for government assistance to Black Ame...,8.0,14.0,1.269436,1.325645,0.452574,0.937311,0.484737
35,lg_refuse_service,1.828013,0.032093,1.243084,0.165661,LGBTQ,Views on refusing service to same-sex couples.,9.0,1.0,0.723607,0.467393,-1.152795,0.928706,2.081502
36,clim_imp,1.835516,0.032024,1.565396,0.114112,Climate,Importance assigned to climate change as an is...,10.0,12.0,0.882089,1.195245,0.382277,0.916135,0.533858
45,ft_sci,1.766211,0.031472,0.922126,0.040673,Institutions,Feeling thermometer rating toward scientists.,11.0,46.0,-0.581807,-0.257402,2.485185,0.814224,-1.670960
2,illeg_child,1.816621,0.029972,0.948134,0.075581,Immigration,Views on how the U.S. should handle children o...,12.0,32.0,0.482985,-0.198670,1.160448,0.537514,-0.622934
40,mil_force,1.741231,0.029667,0.349896,0.049060,ForeignPolicy,Support for the use of U.S. military force int...,13.0,44.0,-1.109428,-1.549624,1.900527,0.481363,-1.419164
29,black_favor,1.804285,0.029204,1.344375,0.135618,Race,Attitudes toward whether Black people should r...,14.0,7.0,0.222414,0.696130,-0.783584,0.395966,1.179549
19,scotus_abort,1.808701,0.028969,1.413303,0.120520,Abortion,Views on Supreme Court decisions and judicial ...,15.0,11.0,0.315689,0.851785,-0.373667,0.352577,0.726245
31,trans_bath,1.840021,0.028208,1.276135,0.161220,LGBTQ,Views on transgender bathroom access policies.,16.0,2.0,0.977253,0.542030,-1.735966,0.212199,1.948165
20,govt_health,1.793619,0.027320,1.556133,0.124644,Health,Support for government-provided health insuran...,17.0,10.0,-0.002868,1.174327,-0.801669,0.048400,0.850068
17,ft_police,1.775911,0.027261,1.106227,0.063131,Policing,Feeling thermometer rating toward police.,18.0,39.0,-0.376912,0.158338,1.034241,0.037527,-0.996715
11,felon_vote,1.816200,0.026053,0.820345,0.106281,Elections,Support for restoring or extending voting righ...,19.0,16.0,0.474080,-0.487246,-0.484098,-0.185350,0.298748
5,job_gov_guar,1.775823,0.025874,1.478903,0.105467,Labor,Support for a government-guaranteed job progra...,20.0,17.0,-0.378772,0.999925,-0.492597,-0.218261,0.274336
38,ghg_emiss,1.814586,0.025755,1.169356,0.097797,Climate,Support for regulating greenhouse gas emission...,21.0,21.0,0.439988,0.300900,-0.284266,-0.240215,0.044051
7,ft_union,1.792478,0.025730,0.963094,0.057614,Labor,Feeling thermometer rating toward labor unions.,22.0,41.0,-0.026970,-0.164887,0.917521,-0.244830,-1.162351
26,svc_spend,1.739577,0.025716,1.505273,0.089223,Redistribution,Preferences for government spending on service...,23.0,23.0,-1.144381,1.059475,-0.034045,-0.247398,-0.213353
37,env_bus,1.758308,0.025421,1.599410,0.109050,Climate,Tradeoff between environmental protection and ...,24.0,15.0,-0.748740,1.272056,-0.683706,-0.301812,0.381894
0,imm_unauth,1.820362,0.025412,1.007885,0.087450,Immigration,Policy preferences regarding unauthorized/undo...,25.0,26.0,0.561993,-0.063738,-0.036866,-0.303458,-0.266591
1,birthright,1.783516,0.025352,1.036311,0.129074,Immigration,Support for birthright citizenship for childre...,26.0,9.0,-0.216277,0.000453,-1.297700,-0.314646,0.983053
8,journ_access,1.737253,0.024609,0.834154,0.104073,Institutions,Support for press/journalist access to governm...,27.0,20.0,-1.193459,-0.456061,-0.684150,-0.451676,0.232474
14,gun_imp,1.811032,0.024582,0.274799,0.069836,Guns,Importance placed on gun regulation as a polit...,28.0,37.0,0.364932,-1.719209,0.338772,-0.456641,-0.795413
30,diversity,1.783329,0.024302,0.858743,0.075308,Race,Attitudes toward diversity initiatives and/or ...,29.0,33.0,-0.220218,-0.400534,0.122895,-0.508243,-0.631138
41,free_trade,1.725123,0.024190,0.284479,0.059593,Trade,Support for free trade policies and reducing t...,30.0,40.0,-1.449676,-1.697350,0.573915,-0.529007,-1.102922
15,death_pen,1.753714,0.024079,0.999484,0.147272,Crime,Support for the death penalty/capital punishme...,31.0,6.0,-0.845763,-0.082711,-2.078883,-0.549455,1.529428
13,ar_ban,1.876521,0.024071,0.940938,0.157338,Guns,Support for banning assault rifles/assault wea...,32.0,3.0,1.748223,-0.214919,-2.382462,-0.550850,1.831611
3,spend_border,1.756592,0.023667,1.550767,0.113009,Immigration,Preferences for federal spending levels on bor...,33.0,13.0,-0.784980,1.162209,-1.126172,-0.625413,0.500759
24,spend_welfare,1.780082,0.023418,1.274814,0.094927,Redistribution,Preferences for federal spending on welfare pr...,34.0,22.0,-0.288807,0.539046,-0.629230,-0.671332,-0.042101
21,obamacare,1.832869,0.023027,2.408148,0.151637,Health,Attitudes toward the Affordable Care Act (ACA/...,35.0,5.0,0.826176,3.098367,-2.403996,-0.743520,1.660476
16,police_force,1.746760,0.022871,1.006237,0.055553,Policing,Support for police use of force / policing pra...,36.0,42.0,-0.992657,-0.067459,0.452089,-0.772149,-1.224239
39,def_spend,1.720307,0.022673,1.060406,0.084489,Defense,Preferences for government spending on nationa...,37.0,28.0,-1.551405,0.054864,-0.453176,-0.808677,-0.355501
25,spend_poor,1.792660,0.022631,1.176851,0.077242,Redistribution,Preferences for federal spending to aid the po...,38.0,29.0,-0.023141,0.317823,-0.243460,-0.816531,-0.573071
27,millionaire_tax,1.805544,0.022429,0.918373,0.156521,Redistribution,Support for taxes targeting millionaires.,39.0,4.0,0.249016,-0.265877,-2.660859,-0.853767,1.807093
9,checks_power,1.661446,0.021717,0.226124,0.048869,Institutions,Views on checks and balances and whether branc...,40.0,45.0,-2.794687,-1.829129,0.439857,-0.985039,-1.424896
23,spend_school,1.757754,0.021460,0.881059,0.077125,Education,Preferences for federal spending on public sch...,41.0,30.0,-0.760431,-0.350141,-0.455930,-1.032518,-0.576588
6,min_wage,1.791260,0.021385,1.008874,0.071326,Labor,Support for raising the minimum wage / minimum...,42.0,36.0,-0.052703,-0.061504,-0.295647,-1.046316,-0.750670
12,gun_bkg_chk,1.862673,0.021121,0.497340,0.050344,Guns,Support for background checks on gun purchases...,43.0,43.0,1.455706,-1.216663,0.285608,-1.094996,-1.380604
10,voter_id,1.785853,0.020934,1.190985,0.104792,Elections,Support for voter identification requirements ...,44.0,18.0,-0.166908,0.349741,-1.383645,-1.129597,0.254048
22,vax_school,1.738791,0.020081,0.404883,0.087412,Health,Support for school vaccination requirements fo...,45.0,27.0,-1.160973,-1.425452,-1.019169,-1.286894,-0.267725
4,paid_leave,1.849040,0.019677,0.713889,0.072350,Labor,Support for paid parental/family leave policie...,46.0,34.0,1.167748,-0.727646,-0.641467,-1.361389,-0.719922

In [37]:
df_merged = compare_standardized_columns(df_merged, 'Avg_Total_Dispersion', 'ANES_Variance')

Standardized Differences by area:
                mean_diff  n_topics
area
Gender             3.3488         1
ForeignPolicy      1.9005         1
Trade              1.4179         2
LGBTQ              0.9298         6
Institutions       0.7470         3
Policing           0.7432         2
Race              -0.0694         3
Labor             -0.1280         4
Abortion          -0.1893         2
Climate           -0.1952         3
Immigration       -0.3251         4
Defense           -0.4532         1
Education         -0.4559         1
Guns              -0.5860         3
Redistribution    -0.8919         4
Elections         -0.9339         2
Health            -1.4083         3
Crime             -2.0789         1

Detailed breakdown:
|    | Topic             | area           |   Avg_Total_Dispersion_norm |   ANES_Variance_norm |        diff |
|---:|:------------------|:---------------|----------------------------:|---------------------:|------------:|
| 44 | ft_fem            | Gender         |                   2.61277   |           -0.736006  |  3.34877    |
| 43 | ft_trans          | LGBTQ          |                   2.53736   |           -0.600496  |  3.13785    |
| 45 | ft_sci            | Institutions   |                   0.814224  |           -1.67096   |  2.48518    |
| 33 | lg_job            | LGBTQ          |                   2.10537   |           -0.229908  |  2.33527    |
| 42 | intl_trade_job    | Trade          |                   1.34278   |           -0.919027  |  2.2618     |
| 40 | mil_force         | ForeignPolicy  |                   0.481363  |           -1.41916   |  1.90053    |
| 32 | trans_military    | LGBTQ          |                   2.00298   |            0.233921  |  1.76906    |
| 34 | lg_marry          | LGBTQ          |                   0.995547  |           -0.229908  |  1.22546    |
|  2 | illeg_child       | Immigration    |                   0.537514  |           -0.622934  |  1.16045    |
| 17 | ft_police         | Policing       |                   0.0375266 |           -0.996715  |  1.03424    |
|  7 | ft_union          | Labor          |                  -0.24483   |           -1.16235   |  0.917521   |
| 41 | free_trade        | Trade          |                  -0.529007  |           -1.10292   |  0.573915   |
| 28 | assist_black      | Race           |                   0.937311  |            0.484737  |  0.452574   |
| 16 | police_force      | Policing       |                  -0.772149  |           -1.22424   |  0.452089   |
|  9 | checks_power      | Institutions   |                  -0.985039  |           -1.4249    |  0.439857   |
| 36 | clim_imp          | Climate        |                   0.916135  |            0.533858  |  0.382277   |
| 14 | gun_imp           | Guns           |                  -0.456641  |           -0.795413  |  0.338772   |
| 12 | gun_bkg_chk       | Guns           |                  -1.095     |           -1.3806    |  0.285608   |
| 30 | diversity         | Race           |                  -0.508243  |           -0.631138  |  0.122895   |
| 18 | abortion          | Abortion       |                   1.07126   |            1.07619   | -0.00492495 |
| 26 | svc_spend         | Redistribution |                  -0.247398  |           -0.213353  | -0.0340453  |
|  0 | imm_unauth        | Immigration    |                  -0.303458  |           -0.266591  | -0.0368661  |
| 25 | spend_poor        | Redistribution |                  -0.816531  |           -0.573071  | -0.24346    |
| 38 | ghg_emiss         | Climate        |                  -0.240215  |            0.0440512 | -0.284266   |
|  6 | min_wage          | Labor          |                  -1.04632   |           -0.75067   | -0.295647   |
| 19 | scotus_abort      | Abortion       |                   0.352577  |            0.726245  | -0.373667   |
| 39 | def_spend         | Defense        |                  -0.808677  |           -0.355501  | -0.453176   |
| 23 | spend_school      | Education      |                  -1.03252   |           -0.576588  | -0.45593    |
| 11 | felon_vote        | Elections      |                  -0.18535   |            0.298748  | -0.484098   |
|  5 | job_gov_guar      | Labor          |                  -0.218261  |            0.274336  | -0.492597   |
| 24 | spend_welfare     | Redistribution |                  -0.671332  |           -0.0421012 | -0.62923    |
|  4 | paid_leave        | Labor          |                  -1.36139   |           -0.719922  | -0.641467   |
| 37 | env_bus           | Climate        |                  -0.301812  |            0.381894  | -0.683706   |
|  8 | journ_access      | Institutions   |                  -0.451676  |            0.232474  | -0.68415    |
| 29 | black_favor       | Race           |                   0.395966  |            1.17955   | -0.783584   |
| 20 | govt_health       | Health         |                   0.0483998 |            0.850068  | -0.801669   |
| 22 | vax_school        | Health         |                  -1.28689   |           -0.267725  | -1.01917    |
|  3 | spend_border      | Immigration    |                  -0.625413  |            0.500759  | -1.12617    |
| 35 | lg_refuse_service | LGBTQ          |                   0.928706  |            2.0815    | -1.1528     |
|  1 | birthright        | Immigration    |                  -0.314646  |            0.983053  | -1.2977     |
| 10 | voter_id          | Elections      |                  -1.1296    |            0.254048  | -1.38364    |
| 31 | trans_bath        | LGBTQ          |                   0.212199  |            1.94817   | -1.73597    |
| 15 | death_pen         | Crime          |                  -0.549455  |            1.52943   | -2.07888    |
| 13 | ar_ban            | Guns           |                  -0.55085   |            1.83161   | -2.38246    |
| 21 | obamacare         | Health         |                  -0.74352   |            1.66048   | -2.404      |
| 27 | millionaire_tax   | Redistribution |                  -0.853767  |            1.80709   | -2.66086    |

Subset Pearson correlation: 0.641
Subset Spearman correlation: 0.434