In [ ]:
import torch
import numpy as np
import pandas as pd
import plotly.express as px
from transformers import AutoTokenizer, AutoModelForCausalLM
from scipy.spatial.distance import mahalanobis
from scipy.linalg import inv, LinAlgError
from sklearn.decomposition import PCA
from sklearn.metrics import davies_bouldin_score
from joblib import Parallel, delayed
import os
import time
TOPICS = {
    "Baseline": None,

    # =========================
    # IMMIGRATION
    # =========================
    "imm_unauth": "unauthorized and undocumented immigrants",
    "birthright": "birthright citizenship",
    "illeg_child": "children of undocumented immigrants",
    "border_wall": "a wall along the U.S.–Mexico border",
    "spend_border": "whether to increase or decrease funding for border security",
    "immig_levels": "the level of immigration into the United States",

    # =========================
    # LABOR / FAMILY POLICY
    # =========================
    "paid_leave": "paid parental or family leave",
    "job_gov_guar": "whether the government should guarantee a job to everyone",
    "min_wage": "whether to change the minimum wage",
    "ft_union": "labor unions",

    # =========================
    # INSTITUTIONS / ACCOUNTABILITY / MEDIA
    # =========================
    "trump_corr": "whether Donald Trump was involved in political corruption",
    "journ_access": "whether journalists should have broad access to government officials and information",
    "checks_power": "to what degree the branches of government should limit each other’s power",
    "rus_interf": "how serious a problem Russian interference in U.S. elections is",
    "ft_sci": "scientists",

    # =========================
    # ELECTIONS / DEMOCRACY
    # =========================
    "voter_id": "whether voters should be required to show identification to vote",
    "felon_vote": "whether people with felony convictions should have the right to vote",
    "vote_denied": "how often people are denied the right to vote",

    # =========================
    # ECONOMY (RETROSPECTIVE)
    # =========================
    "econ_now": "how good or bad the current national economy is",

    # =========================
    # GUNS
    # =========================
    "gun_bkg_chk": "whether background checks should be required for gun purchases",
    "ar_ban": "whether assault weapons should be banned",
    "gun_imp": "to what degree gun regulation is an important political issue",

    # =========================
    # CRIME / POLICING / ORDER
    # =========================
    "death_pen": "whether the death penalty should be used for serious crimes",
    "police_force": "to what degree police should be allowed to use force",
    "urban_unrest": "how serious a problem urban unrest and protests are",
    "ft_police": "the police",
    "biden_crime": "Joe Biden’s handling of crime",
    "crime_spend": "to what degree the government should spend money on dealing with crime",

    # =========================
    # ABORTION / COURTS
    # =========================
    "abortion": "whether abortion should be legal",
    "scotus_abort": "the Supreme Court decisions related to abortion",

    # =========================
    # HEALTH
    # =========================
    "govt_health": "whether the government should provide health insurance",
    "obamacare": "whether the Affordable Care Act should be kept, expanded, or repealed",
    "vax_school": "whether children should be required to be vaccinated to attend school",
    "health_spend": "to what degree the government should spend money to help people pay for health insurance",

    # =========================
    # EDUCATION / SPENDING
    # =========================
    "spend_school": "to what degree the government should spend money on public schools",
    "dei_college": "diversity, equity, and inclusion (DEI) policies on college campuses",
    "affirm_action": "affirmative action in university admissions",

    # =========================
    # REDISTRIBUTION / WELFARE / TAX
    # =========================
    "spend_welfare": "to what degree the government should spend money on welfare programs",
    "spend_poor": "to what degree the government should spend money to help the poor",
    "svc_spend": "to what degree the government should spend money on public services",
    "millionaire_tax": "whether to tax on millionaires",

    # =========================
    # DIVERSITY (formerly Race)
    # =========================
    "assist_black": "to what degree the government should help Black Americans",
    "black_favor": "whether Black people should get special favor",
    "diversity": "to what degree diversity benefits the country",
    "ft_asian": "Asian-Americans",
    "discuss_race": "how often racial issues should be discussed with children",

    # =========================
    # TRANSGENDER
    # =========================
    "trans_bath": "whether transgender people should use bathrooms matching their gender identity",
    "trans_military": "whether transgender people should serve in the U.S. military",
    "ft_trans": "transgender people",

    # =========================
    # LESBIAN / GAY
    # =========================
    "lg_job": "protection for gay and lesbian people from job discrimination",
    "lg_marry": "legal marriage for same-sex couples",
    "lg_refuse_service": "whether businesses should be allowed to refuse service to same-sex couples",

    # =========================
    # GENDER
    # =========================
    "ft_fem": "feminists",

    # =========================
    # CLIMATE / ENVIRONMENT
    # =========================
    "clim_imp": "how important climate change is as an issue",
    "env_bus": "the tradeoff between environmental protection and business interests",
    "ghg_emiss": "whether to regulate greenhouse gas emissions",

    # =========================
    # DEFENSE / FOREIGN POLICY
    # =========================
    "def_spend": "to what degree the government should spend money on national defense",
    "mil_force": "whether the United States should use military force in foreign countries",
    "biden_foreign": "Joe Biden’s handling of foreign relations",
    "israel_aid": "U.S. military assistance to Israel",

    # =========================
    # TRADE
    # =========================
    "free_trade": "free trade agreements with other countries",
    "intl_trade_job": "whether international trade helps or hurts jobs in the United States",
    "limit_imports": "placing new limits on imports",
}







SYSTEM_MSG = (
    "You are simulating the public stance of U.S. politicians.\n\n"
)

# ==========================================
# 1. CONFIGURATION
# ==========================================
# A100 40GB can handle large batches for 8B models
BATCH_SIZE = 128
MODEL_PATH = "/project/jevans/maxzhuyt/models/Meta-Llama-3.1-8B-Instruct"
NOMINATE_CSV = "/project/jevans/maxzhuyt/gss_polarization/data/politicians.csv"

# Topics: Core + Bipartisan/Horseshoe Candidates

# ==========================================
# 2. MODEL LOADER & EXTRACTION (GPU)
# ==========================================
def load_model(path):
    print(f"Loading model from: {path}...")
    dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    tokenizer = AutoTokenizer.from_pretrained(path, use_fast=True, local_files_only=True)
    
    # CRITICAL: Left padding allows batching without destroying the last token position
    tokenizer.padding_side = 'left' 
    tokenizer.truncation_side = "left"

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        tokenizer.pad_token_id = tokenizer.eos_token_id
    
    model = AutoModelForCausalLM.from_pretrained(
        path, dtype=dtype, device_map="auto", local_files_only=True, attn_implementation="eager"
    )
    model.generation_config.pad_token_id = tokenizer.pad_token_id
    return model, tokenizer

@torch.no_grad()
def extract_heads_batched(model, tokenizer, texts, batch_size=32):
    """
    Optimized extraction for A100.
    """
    model.eval()
    L = model.config.num_hidden_layers
    H = model.config.num_attention_heads
    D_head = model.config.hidden_size // H
    
    activations = []
    
    # Pre-allocate hook containers
    layer_outputs = [None] * L
    
    def get_hook(layer_idx):
        def hook(module, input, output):
            # Input[0] shape: [Batch, Seq, Hidden]
            # Reshape to [Batch, Seq, Heads, Head_Dim]
            # We immediately move to CPU to free VRAM for the next batch
            reshaped = input[0].detach().view(input[0].shape[0], input[0].shape[1], H, D_head)
            layer_outputs[layer_idx] = reshaped[:, -1, :, :].float().cpu().numpy()
        return hook

    # Register hooks once
    hooks = []
    for li in range(L):
        hooks.append(model.model.layers[li].self_attn.o_proj.register_forward_hook(get_hook(li)))

    print(f"  > Extracting with Batch Size {batch_size}...")
    
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        
        # Fast Tokenization
        formatted_batch = [
            tokenizer.apply_chat_template([{"role": "system", "content": SYSTEM_MSG}, {"role": "user", "content": t}], tokenize=False, add_generation_prompt=True)
            for t in batch
        ]
        
        enc = tokenizer(
            formatted_batch, return_tensors="pt", padding=True, truncation=True, max_length=128
        ).to(model.device)
        
        # Forward pass triggers hooks
        model(**enc)
        
        # Stack layers: [Batch, Layers, Heads, Dim]
        batch_acts = np.stack(layer_outputs, axis=1)
        activations.append(batch_acts)

    for h in hooks: h.remove()
    return np.concatenate(activations, axis=0)

# ==========================================
# 3. PARALLEL METRICS ENGINE (CPU)
# ==========================================
def calculate_metrics_for_single_head(head_data, party_labels):
    """
    Calculates all 5 metrics for a SINGLE head.
    This function will be mapped across 1024 heads in parallel.
    """
    # Filter Valid Data
    valid_mask = np.isin(party_labels, [100, 200])
    X = head_data[valid_mask]
    y = party_labels[valid_mask]
    
    # Centering for PCA/Covariance
    X_centered = X - np.mean(X, axis=0)
    
    results = {}
    
    # --- BLOCK A: PCA BASED METRICS (3 in 1) ---
    # We run PCA once to get eigenvalues, used for Dispersion, PC1, and Intrinsic Dim
    try:
        pca = PCA(n_components=10) # We only need top eigenvalues
        pca.fit(X_centered)
        evals = pca.explained_variance_
        
        # 3. Total Dispersion (Sum of variance/eigenvalues)
        results['Total_Dispersion'] = np.sum(evals)
        
        # 4. Explained Variance Ratio of PC1
        results['PC1_Ratio'] = pca.explained_variance_ratio_[0]
        
        # 5. Intrinsic Dimensionality (Participation Ratio)
        sum_evals = np.sum(evals)
        sum_sq_evals = np.sum(evals**2)
        if sum_sq_evals > 0:
            results['Intrinsic_Dim'] = (sum_evals**2) / sum_sq_evals
        else:
            results['Intrinsic_Dim'] = 0.0
            
    except Exception:
        results['Total_Dispersion'] = 0.0
        results['PC1_Ratio'] = 0.0
        results['Intrinsic_Dim'] = 0.0

    # --- BLOCK B: CLUSTER METRICS ---
    
    # 2. Davies-Bouldin Index
    # (Lower is better separation, so higher polarization means LOWER score usually)
    try:
        if len(np.unique(y)) > 1:
            results['Davies_Bouldin'] = davies_bouldin_score(X, y)
        else:
            results['Davies_Bouldin'] = 10.0 # Bad score
    except:
        results['Davies_Bouldin'] = 10.0

    # 1. Mahalanobis Distance
    try:
        dems = X[y == 100]
        reps = X[y == 200]
        
        if len(dems) > 5 and len(reps) > 5:
            # Pooled Covariance with regularization
            cov_pool = (np.cov(dems, rowvar=False) + np.cov(reps, rowvar=False)) / 2
            cov_pool += np.eye(cov_pool.shape[0]) * 1e-6 # Regularize
            
            inv_cov = inv(cov_pool)
            mu_d, mu_r = np.mean(dems, axis=0), np.mean(reps, axis=0)
            results['Mahalanobis'] = mahalanobis(mu_d, mu_r, inv_cov)
        else:
            results['Mahalanobis'] = 0.0
    except (LinAlgError, ValueError):
        results['Mahalanobis'] = 0.0
        
    return results

# ==========================================
# 4. MAIN EXECUTION LOOP
# ==========================================

# Setup
model, tokenizer = load_model(MODEL_PATH)

df_nom = pd.read_csv(NOMINATE_CSV)
df_nom = df_nom[df_nom['party_code'].isin([100, 200])].dropna(subset=['bioname'])
party_labels = df_nom['party_code'].values

full_results = []

print(f"\nStarting Optimized Pipeline on A100 (Batch Size {BATCH_SIZE})")
print(f"Parallel processing enabled for metrics calculation.")

for topic_name, topic_desc in TOPICS.items():
    t0 = time.time()
    print(f"\n--- Topic: {topic_name} ---")
    
    # 1. Generate Prompts
    prompts = []
    for name in df_nom['bioname']:
        if topic_desc:
            user_msg = (
                f"Generate a statement by {name} on {topic_desc}."
            )
        else:
            user_msg = (
                f"Generate a statement by {name}."
            )
        prompts.append(user_msg)
        
    # 2. Extract Heads (GPU Bound)
    # Shape: [N, 32, 32, 128]
    X_heads = extract_heads_batched(model, tokenizer, prompts, batch_size=BATCH_SIZE)
    
    # 3. Parallel Metrics (CPU Bound)
    # Flatten L and H to iterate easily: List of (1024) arrays of shape (N, 128)
    N, L, H, D = X_heads.shape
    flat_heads = [X_heads[:, l, h, :] for l in range(L) for h in range(H)]
    
    print("  > Computing metrics for 1024 heads (Parallel)...")
    
    # Uses all available CPU cores
    metrics_flat = Parallel(n_jobs=-1)(
        delayed(calculate_metrics_for_single_head)(head_data, party_labels) 
        for head_data in flat_heads
    )
    
    # 4. Aggregation & Storage
    # Reshape back to (32, 32) grids for visualization
    metric_grids = {k: np.zeros((L, H)) for k in metrics_flat[0].keys()}
    
    idx = 0
    for l in range(L):
        for h in range(H):
            m = metrics_flat[idx]
            for key in m:
                metric_grids[key][l, h] = m[key]
            idx += 1
            
    # Calculate Averages/Max for Summary
    summary = {"Topic": topic_name}
    for key, grid in metric_grids.items():
        summary[f"Avg_{key}"] = np.mean(grid)
        summary[f"Max_{key}"] = np.max(grid)
        # Store the full grid for heatmaps later
        summary[f"Grid_{key}"] = grid
        
    full_results.append(summary)
    print(f"  > Done in {time.time() - t0:.1f}s. Avg Mahalanobis: {summary['Avg_Mahalanobis']:.4f}")

/project/jevans/maxzhuyt/honest_llama_env/lib/python3.10/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/project/jevans/maxzhuyt/honest_llama_env/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Loading model from: /project/jevans/maxzhuyt/models/Meta-Llama-3.1-8B-Instruct...

Loading checkpoint shards: 100%|██████████| 4/4 [00:05<00:00,  1.48s/it]

Starting Optimized Pipeline on A100 (Batch Size 128)
Parallel processing enabled for metrics calculation.

--- Topic: Baseline ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.6s. Avg Mahalanobis: 1.7533

--- Topic: imm_unauth ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.8213

--- Topic: birthright ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.7965

--- Topic: illeg_child ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.8425

--- Topic: border_wall ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.7573

--- Topic: spend_border ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.7635

--- Topic: immig_levels ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.7s. Avg Mahalanobis: 1.7845

--- Topic: paid_leave ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.8520

--- Topic: job_gov_guar ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.7274

--- Topic: min_wage ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.7941

--- Topic: ft_union ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.4s. Avg Mahalanobis: 1.8229

--- Topic: trump_corr ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.7s. Avg Mahalanobis: 1.7727

--- Topic: journ_access ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.1s. Avg Mahalanobis: 1.6910

--- Topic: checks_power ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.1s. Avg Mahalanobis: 1.6811

--- Topic: rus_interf ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.1s. Avg Mahalanobis: 1.7272

--- Topic: ft_sci ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.2s. Avg Mahalanobis: 1.7724

--- Topic: voter_id ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7320

--- Topic: felon_vote ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7206

--- Topic: vote_denied ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.7174

--- Topic: econ_now ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.7481

--- Topic: gun_bkg_chk ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7440

--- Topic: ar_ban ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.8242

--- Topic: gun_imp ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.0s. Avg Mahalanobis: 1.7536

--- Topic: death_pen ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.0s. Avg Mahalanobis: 1.7240

--- Topic: police_force ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.0s. Avg Mahalanobis: 1.6968

--- Topic: urban_unrest ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.7480

--- Topic: ft_police ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.7574

--- Topic: biden_crime ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.8325

--- Topic: crime_spend ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.0s. Avg Mahalanobis: 1.7209

--- Topic: abortion ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.8143

--- Topic: scotus_abort ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.8086

--- Topic: govt_health ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.7s. Avg Mahalanobis: 1.7897

--- Topic: obamacare ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.1s. Avg Mahalanobis: 1.8071

--- Topic: vax_school ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7077

--- Topic: health_spend ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.3s. Avg Mahalanobis: 1.7268

--- Topic: spend_school ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7437

--- Topic: dei_college ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.3s. Avg Mahalanobis: 1.7702

--- Topic: affirm_action ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.8111

--- Topic: spend_welfare ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7784

--- Topic: spend_poor ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.0s. Avg Mahalanobis: 1.7607

--- Topic: svc_spend ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7248

--- Topic: millionaire_tax ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.7s. Avg Mahalanobis: 1.8070

--- Topic: assist_black ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.8021

--- Topic: black_favor ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.7732

--- Topic: diversity ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.7071

--- Topic: ft_asian ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.4s. Avg Mahalanobis: 1.7989

--- Topic: discuss_race ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7093

--- Topic: trans_bath ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.8848

--- Topic: trans_military ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7983

--- Topic: ft_trans ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.4s. Avg Mahalanobis: 1.8971

--- Topic: lg_job ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.8417

--- Topic: lg_marry ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.8270

--- Topic: lg_refuse_service ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.1s. Avg Mahalanobis: 1.7967

--- Topic: ft_fem ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.3s. Avg Mahalanobis: 1.8112

--- Topic: clim_imp ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.8s. Avg Mahalanobis: 1.8332

--- Topic: env_bus ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7631

--- Topic: ghg_emiss ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.8098

--- Topic: def_spend ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 8.0s. Avg Mahalanobis: 1.7111

--- Topic: mil_force ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7474

--- Topic: biden_foreign ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.6s. Avg Mahalanobis: 1.8183

--- Topic: israel_aid ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.7s. Avg Mahalanobis: 1.7653

--- Topic: free_trade ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.7s. Avg Mahalanobis: 1.7511

--- Topic: intl_trade_job ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.9s. Avg Mahalanobis: 1.7465

--- Topic: limit_imports ---
  > Extracting with Batch Size 128...
  > Computing metrics for 1024 heads (Parallel)...
  > Done in 7.5s. Avg Mahalanobis: 1.7047

In [2]:

# ==========================================
# 5. VISUALIZATION
# ==========================================
df_res = pd.DataFrame(full_results)

In [3]:
from datetime import datetime

timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
df_res.to_pickle(f"df_llm_anes_res_{timestamp}.pkl")

In [4]:
def calc_center_of_gravity(grid):
    """
    Calculate the center of gravity (weighted average layer index) for a 2D grid.
    Assumes axis 0 is layer, axis 1 is head.
    Returns a float representing the average layer number (0-31).
    """
    # Handle invalid grids
    if not isinstance(grid, np.ndarray):
        return np.nan
    
    # Replace any inf or nan values with 0
    grid = np.nan_to_num(grid, nan=0.0, posinf=0.0, neginf=0.0)
    
    L, H = grid.shape
    # Layer indices (0 to L-1, e.g., 0-31 for 32 layers)
    layer_idx = np.arange(L)
    # Sum polarization for each layer (across heads)
    layer_sum = grid.sum(axis=1)
    total = layer_sum.sum()
    if total == 0:
        return np.nan
    cog = np.sum(layer_idx * layer_sum) / total
    return cog

def safe_reciprocal(grid):
    """Compute reciprocal only where values are valid, avoiding divide-by-zero warnings."""
    if not isinstance(grid, np.ndarray):
        return np.nan
    result = np.full_like(grid, np.nan, dtype=float)
    mask = np.isfinite(grid) & (grid > 1e-10)
    result[mask] = 1.0 / grid[mask]
    return result

# Safely compute reciprocal, replacing inf/nan with nan
df_res['Grid_Davies_Bouldin_Rev'] = df_res['Grid_Davies_Bouldin'].apply(safe_reciprocal)
df_res["Polarization_CoG"] = df_res["Grid_Davies_Bouldin_Rev"].apply(calc_center_of_gravity)

In [5]:
df_res

,Topic,Avg_Total_Dispersion,Max_Total_Dispersion,Grid_Total_Dispersion,Avg_PC1_Ratio,Max_PC1_Ratio,Grid_PC1_Ratio,Avg_Intrinsic_Dim,Max_Intrinsic_Dim,Grid_Intrinsic_Dim,Avg_Davies_Bouldin,Max_Davies_Bouldin,Grid_Davies_Bouldin,Avg_Mahalanobis,Max_Mahalanobis,Grid_Mahalanobis,Grid_Davies_Bouldin_Rev,Polarization_CoG
0,Baseline,0.045554,1.448281,"[[0.0006188098923303187, 1.9228991732234135e-0...",0.427635,0.962262,"[[0.10159828513860703, 0.13500182330608368, 0....",3.596877,9.162354,"[[8.114928245544434, 6.813268184661865, 1.0635...",9.528041,28.719542,"[[10.783429817301958, 10.35005957492913, 8.014...",1.753346,2.739318,"[[1.2788956213312561, 0.6757404399234126, 0.29...","[[0.09273487349966382, 0.09661780135278568, 0....",15.590125
1,imm_unauth,0.027519,1.026740,"[[6.882594607304782e-05, 1.67380985658383e-05,...",0.383584,0.928955,"[[0.08229353278875351, 0.3883313834667206, 0.9...",3.910840,9.644713,"[[8.500543594360352, 2.608874559402466, 1.1215...",7.896980,23.347598,"[[11.055586626642517, 10.549779921743776, 8.34...",1.821281,2.709131,"[[0.958553771951725, 0.5467635974007394, 0.210...","[[0.09045200709568237, 0.0947887071974777, 0.1...",16.267675
2,birthright,0.029259,1.234827,"[[0.0001090360528905876, 1.4733432180946693e-0...",0.390944,0.926908,"[[0.07973366975784302, 0.2834092378616333, 0.8...",3.863772,9.575510,"[[8.538965225219727, 3.732590675354004, 1.2968...",8.756335,37.282318,"[[11.324156914608434, 10.980920159543873, 12.7...",1.796550,2.706335,"[[1.0605913931239994, 0.5686916985976951, 0.19...","[[0.08830679471687433, 0.09106704952506806, 0....",15.710361
3,illeg_child,0.034320,1.387254,"[[7.273071969393641e-05, 1.6665640941937454e-0...",0.404816,0.930948,"[[0.08218064904212952, 0.3767225742340088, 0.9...",3.750405,9.438087,"[[8.50680160522461, 2.7016663551330566, 1.1262...",7.118723,24.685416,"[[11.063780075533678, 10.626437881151228, 8.32...",1.842531,2.718196,"[[0.9693479596408837, 0.5499641820532404, 0.21...","[[0.09038502150014614, 0.09410491184197878, 0....",17.001089
4,border_wall,0.051774,1.831442,"[[2.631974348332733e-05, 2.040410618064925e-05...",0.433771,0.953440,"[[0.10917602479457855, 0.5284090638160706, 0.9...",3.521596,9.403046,"[[7.660077095031738, 1.853047251701355, 1.0807...",10.258293,37.082162,"[[12.744264751844689, 10.183267611893983, 37.0...",1.757255,2.689631,"[[0.7421900881263355, 0.468451204289215, 0.144...","[[0.07846666869151894, 0.0982003064352357, 0.0...",14.996041
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,biden_foreign,0.035813,1.346578,"[[4.419283868628554e-05, 1.816969597712159e-05...",0.387266,0.971476,"[[0.09414758533239365, 0.4620116651058197, 0.9...",3.932977,9.573914,"[[8.15821647644043, 2.1666510105133057, 1.0467...",8.580616,27.501570,"[[12.620560758757476, 9.961463210670438, 11.19...",1.818323,2.674582,"[[0.8200106296627833, 0.5219610377511005, 0.17...","[[0.07923578192087025, 0.10038685872260496, 0....",15.887371
60,israel_aid,0.032180,1.328017,"[[4.4061423977836967e-05, 1.7841579392552376e-...",0.399717,0.971078,"[[0.09411658346652985, 0.44776538014411926, 0....",3.828523,9.500568,"[[8.139799118041992, 2.2474186420440674, 1.047...",9.307558,26.529658,"[[12.555241662979606, 9.974290823994302, 11.34...",1.765294,2.653067,"[[0.8146404586550455, 0.5226618302532186, 0.17...","[[0.07964800892272753, 0.10025775442544599, 0....",15.529058
61,free_trade,0.029859,1.243908,"[[5.35774597665295e-05, 1.7485601347289048e-05...",0.391001,0.968897,"[[0.09123347699642181, 0.42694491147994995, 0....",3.875265,9.580939,"[[8.300579071044922, 2.369307279586792, 1.0508...",9.279105,26.480586,"[[11.496728658127076, 9.958945437016306, 9.277...",1.751102,2.699998,"[[0.8851983268589544, 0.5343680944309094, 0.22...","[[0.08698126482206717, 0.10041223805515691, 0....",15.572021
62,intl_trade_job,0.028545,1.111888,"[[1.2261183655937202e-05, 2.7019261324312538e-...",0.377772,1.000001,"[[0.15799424052238464, 0.5999829769134521, 0.9...",3.962967,9.658922,"[[6.363614082336426, 1.658781886100769, 1.0472...",9.070360,25.286130,"[[9.900701971039217, 9.645289120018477, 8.8205...",1.746460,2.689392,"[[0.6333610983792899, 0.4706743463444534, 0.25...","[[0.10100293927896468, 0.10367755570172937, 0....",15.838817
63,limit_imports,0.023695,1.076336,"[[6.344600114971399e-05, 1.7219010260305367e-0...",0.384139,0.954350,"[[0.08876553922891617, 0.40739309787750244, 0....",3.927349,9.666462,"[[8.303349494934082, 2.4858908653259277, 1.080...",9.440043,26.024679,"[[10.774223093723174, 10.284397841535249, 8.74...",1.704713,2.654264,"[[0.9472487609359185, 0.5444100105304669, 0.21...","[[0.0928141167396634, 0.09723466705666849, 0.1...",15.570815

In [6]:
import plotly.graph_objects as go
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
def adjust_text_positions(x, y, text_list, max_iterations=100, step_size=0.01):
    """
    Iteratively moves text away from:
      1. Its own data point (repulsion)
      2. Other text labels (collision avoidance)
    Returns optimized x_text, y_text arrays.
    """
    n = len(x)
    # Start text positions exactly at data points
    tx = np.array(x, dtype=float)
    ty = np.array(y, dtype=float)
    
    # Normalize coordinates to 0-1 scale for consistent 'force' calculations
    # We will map them back later.
    x_min, x_max = np.min(x), np.max(x)
    y_min, y_max = np.min(y), np.max(y)
    x_range = x_max - x_min
    y_range = y_max - y_min
    
    # Avoid division by zero
    if x_range == 0: x_range = 1
    if y_range == 0: y_range = 1
    
    tx_norm = (tx - x_min) / x_range
    ty_norm = (ty - y_min) / y_range
    x_norm = (np.array(x) - x_min) / x_range
    y_norm = (np.array(y) - y_min) / y_range

    for _ in range(max_iterations):
        # Calculate forces
        grad_x = np.zeros(n)
        grad_y = np.zeros(n)
        
        for i in range(n):
            # 1. Force pushing text away from its own data point
            # We want it slightly offset, not ON TOP
            dist_self_x = tx_norm[i] - x_norm[i]
            dist_self_y = ty_norm[i] - y_norm[i]
            dist_sq = dist_self_x**2 + dist_self_y**2
            
            # If too close to dot, push away (standard radius)
            target_radius = 0.04 # 4% of plot width
            if dist_sq < target_radius**2:
                 # Push randomly if exactly on top, otherwise radially
                if dist_sq == 0:
                    grad_x[i] += (np.random.random() - 0.5) * 0.1
                    grad_y[i] += (np.random.random() - 0.5) * 0.1
                else:
                    force = (target_radius - np.sqrt(dist_sq)) 
                    grad_x[i] += force * (dist_self_x / np.sqrt(dist_sq))
                    grad_y[i] += force * (dist_self_y / np.sqrt(dist_sq))

            # 2. Force pushing text away from OTHER labels
            for j in range(n):
                if i == j: continue
                
                diff_x = tx_norm[i] - tx_norm[j]
                diff_y = ty_norm[i] - ty_norm[j]
                dist_sq = diff_x**2 + diff_y**2
                
                # Collision radius (approximate text box size)
                min_dist = 0.05 # 5% of plot width
                
                if dist_sq < min_dist**2:
                     if dist_sq == 0:
                        grad_x[i] += (np.random.random() - 0.5) * 0.1
                        grad_y[i] += (np.random.random() - 0.5) * 0.1
                     else:
                        force = (min_dist - np.sqrt(dist_sq)) * 2 # Stronger force for text collision
                        grad_x[i] += force * (diff_x / np.sqrt(dist_sq))
                        grad_y[i] += force * (diff_y / np.sqrt(dist_sq))
                        
        # Apply movements
        tx_norm += grad_x * step_size
        ty_norm += grad_y * step_size
        
        # Clamp to 0-1 to keep inside plot (optional)
        tx_norm = np.clip(tx_norm, 0, 1)
        ty_norm = np.clip(ty_norm, 0, 1)

    # Convert back to original scale
    final_tx = tx_norm * x_range + x_min
    final_ty = ty_norm * y_range + y_min
    
    return final_tx, final_ty

def plot(df_plot):
    # Run the physics engine to get new coordinates for the TEXT ONLY
    # (Assuming adjust_text_positions is defined in your environment)
    new_x, new_y = adjust_text_positions(
        df_plot["Avg_Mahalanobis"].values, 
        df_plot["Avg_Total_Dispersion"].values, 
        df_plot["Topic"].values,
        max_iterations=200, 
        step_size=0.5
    )

    df_plot['text_x'] = new_x
    df_plot['text_y'] = new_y

    # --- 3. PLOTTING (Using Graph Objects for Layering) ---

    fig = go.Figure()

    # Layer 1: The Dots (Markers)
    unique_topics = df_plot['Topic'].unique()
    colors = px.colors.qualitative.Plotly 

    for i, topic in enumerate(unique_topics):
        df_sub = df_plot[df_plot['Topic'] == topic]
        color = colors[i % len(colors)]
        
        fig.add_trace(go.Scatter(
            x=df_sub['Avg_Mahalanobis'],
            y=df_sub['Avg_Total_Dispersion'],
            mode='markers',
            name=topic,
            # Pass Intrinsic Dim as custom data for the hover
            customdata=df_sub['Avg_Intrinsic_Dim'], 
            marker=dict(
                size=14,  # FIXED SIZE for visualization
                color=color,
                opacity=0.85,
                line=dict(width=1, color='DarkSlateGrey')
            ),
            hovertemplate=(
                "<b>%{text}</b><br>" +
                "Polarization: %{x:.4f}<br>" +
                "Intensity: %{y:.2f}<br>" +
                "Intrinsic Dim: %{customdata:.2f}<br>" + # Added here
                "<extra></extra>" 
            ),
            text=df_sub['Topic']
        ))

    # Layer 2: The Lines (Connecting dots to labels)
    for i, row in df_plot.iterrows():
        fig.add_trace(go.Scatter(
            x=[row['Avg_Mahalanobis'], row['text_x']],
            y=[row['Avg_Total_Dispersion'], row['text_y']],
            mode='lines',
            line=dict(color='grey', width=0.3),
            showlegend=False,
            hoverinfo='skip'
        ))

    # Layer 3: The Text (at new optimized positions)
    fig.add_trace(go.Scatter(
        x=df_plot['text_x'],
        y=df_plot['text_y'],
        mode='text',
        text=df_plot['Topic'],
        textfont=dict(size=11, color='black'),
        showlegend=False,
        hoverinfo='skip'
    ))

    # --- 4. LAYOUT & ANNOTATIONS ---

    fig.update_layout(
        title="<b>What Politicans Say about Everyday Topics</b><br>X: Polarization | Y: Total Disagreement",
        template="plotly_white",
        height=800,
        width=1000,
        xaxis_title="Polarization (Mahalanobis Distance)",
        yaxis_title="Total Discourse Disagreement (Dispersion)",
        showlegend=True
    )

    # Add Quadrants
    mid_x = df_plot['Avg_Mahalanobis'].median()
    mid_y = df_plot['Avg_Total_Dispersion'].median()

    fig.add_hline(y=mid_y, line_dash="dot", line_color="grey", opacity=0.5)
    fig.add_vline(x=mid_x, line_dash="dot", line_color="grey", opacity=0.5)

    # Add Quadrant Labels (Watermarks)
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].max(), y=df_plot['Avg_Total_Dispersion'].max(),
                    text="<b>High Polarization<br>High Variance</b>", showarrow=False, align="right", opacity=0.3,
                    xref="x", yref="y", xanchor="right", yanchor="top")
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].min(), y=df_plot['Avg_Total_Dispersion'].max(),
                    text="<b>Low Polarization<br>High Variance</b>", showarrow=False, align="left", opacity=0.3,
                    xref="x", yref="y", xanchor="left", yanchor="top")
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].max(), y=df_plot['Avg_Total_Dispersion'].min(),
                    text="<b>High Polarization<br>Low Variance</b>", showarrow=False, align="right", opacity=0.3,
                    xref="x", yref="y", xanchor="right", yanchor="bottom")
    fig.add_annotation(x=df_plot['Avg_Mahalanobis'].min(), y=df_plot['Avg_Total_Dispersion'].min(),
                    text="<b>Low Polarization<br>Low Variance</b>", showarrow=False, align="left", opacity=0.3,
                    xref="x", yref="y", xanchor="left", yanchor="bottom")

    fig.show()
    fig.write_html("us_cultural_geometry_all.html", include_plotlyjs="cdn")

In [7]:
plot(df_res)

In [8]:
# Drop topics that are strongly related to the 2020 election cycle. 
DROP_TOPICS = {
    "rus_interf",
    "urban_unrest",
    "econ_now",
    "trump_corr",
    "border_wall"
}

df_res = df_res[~df_res["Topic"].isin(DROP_TOPICS)]
# delete all topics with "ft" in the name

In [9]:
anes_path = "policy_polarization.csv"

df_anes = pd.read_csv(anes_path)
df_anes = df_anes.rename(columns={"issue": "Topic", "mahalanobis_distance": "ANES_Mahalanobis", "variance": "ANES_Variance"})

## Comparing Party Polarization between LLM and ANES

In [10]:

# Keep only Topic + Avg_Mahalanobis from LLM results
# rename columns

df_llm = df_res[["Topic", "Avg_Mahalanobis", "Avg_Total_Dispersion", "Polarization_CoG"]].copy()

# Inner join ensures exact key matching
df_merged = df_llm.merge(
    df_anes,
    left_on="Topic",
    right_on="Topic",
    how="inner"
)

pearson_corr = df_merged["Avg_Mahalanobis"].corr(
    df_merged["ANES_Mahalanobis"],
    method="pearson"
)

print(f"Pearson correlation: {pearson_corr:.3f}")
spearman_corr = df_merged["Avg_Mahalanobis"].corr(
    df_merged["ANES_Mahalanobis"],
    method="spearman"
)

print(f"Spearman correlation: {spearman_corr:.3f}")
df_merged["LLM_rank"] = df_merged["Avg_Mahalanobis"].rank(ascending=False)
df_merged["ANES_rank"] = df_merged["ANES_Mahalanobis"].rank(ascending=False)

df_merged.sort_values("Avg_Mahalanobis", ascending=False)

Pearson correlation: 0.325
Spearman correlation: 0.344

,Topic,Avg_Mahalanobis,Avg_Total_Dispersion,Polarization_CoG,ANES_Mahalanobis,ANES_Variance,area,explanation,LLM_rank,ANES_rank
43,ft_trans,1.897050,0.042290,18.264347,1.069882,0.076328,Transgender,Feeling thermometer rating toward transgender ...,1.0,26.0
41,trans_bath,1.884847,0.033458,18.921809,1.276135,0.161220,Transgender,Views on transgender bathroom access policies.,2.0,15.0
5,paid_leave,1.851979,0.025422,16.712534,0.713889,0.072350,Labor,Support for paid parental/family leave policie...,3.0,43.0
2,illeg_child,1.842531,0.034320,17.001089,0.948134,0.075581,Immigration,Views on how the U.S. should handle children o...,4.0,34.0
44,lg_job,1.841690,0.036985,17.579029,0.602085,0.088672,Lesbian/Gay,Views on legal protections against job discrim...,5.0,46.5
48,clim_imp,1.833248,0.037742,16.992993,1.565396,0.114112,Climate,Importance assigned to climate change as an is...,6.0,6.0
21,biden_crime,1.832470,0.032374,16.263938,1.923465,0.160533,CrimeAndPolicing,Approval of Joe Biden's handling of crime.,7.0,2.0
45,lg_marry,1.827036,0.034325,16.754018,0.602085,0.088672,Lesbian/Gay,Support for same-sex marriage / marriage right...,8.0,46.5
16,ar_ban,1.824237,0.024441,16.684285,0.940938,0.157338,Guns,Support for banning assault rifles/assault wea...,9.0,35.0
8,ft_union,1.822874,0.034088,16.232798,0.963094,0.057614,Labor,Feeling thermometer rating toward labor unions.,10.0,33.0
0,imm_unauth,1.821281,0.027519,16.267675,1.007885,0.087450,Immigration,Policy preferences regarding unauthorized/undo...,11.0,30.0
53,biden_foreign,1.818323,0.035813,15.887371,1.700641,0.173603,ForeignPolicy,Approval of Joe Biden's handling of foreign re...,12.0,3.0
23,abortion,1.814286,0.033471,16.196626,1.232532,0.132176,Abortion,Attitudes toward abortion legality and access.,13.0,18.0
47,ft_fem,1.811181,0.046814,16.600159,1.355457,0.071815,Gender,Feeling thermometer rating toward feminists.,14.0,12.0
31,affirm_action,1.811137,0.026710,16.047997,1.082133,0.090213,Education,Favor or oppose affirmative action in universi...,15.0,25.0
50,ghg_emiss,1.809828,0.030766,16.380480,1.169356,0.097797,Climate,Support for regulating greenhouse gas emission...,16.0,22.0
24,scotus_abort,1.808586,0.029181,16.343610,1.413303,0.120520,Abortion,Views on Supreme Court decisions and judicial ...,17.0,11.0
26,obamacare,1.807128,0.026574,16.529290,2.408148,0.151637,Health,Attitudes toward the Affordable Care Act (ACA/...,18.0,1.0
35,millionaire_tax,1.807000,0.028034,16.306700,0.918373,0.156521,Redistribution,Support for taxes targeting millionaires.,19.0,38.0
36,assist_black,1.802129,0.031556,17.116644,1.623140,0.112476,Diversity,Support for government assistance to Black Ame...,20.0,4.0
39,ft_asian,1.798940,0.045398,17.394634,0.222862,0.043342,Diversity,Feeling thermometer rating toward Asian-Americ...,21.0,57.0
42,trans_military,1.798262,0.033186,17.560136,1.205945,0.104121,Transgender,Views on transgender people serving in the U.S...,22.0,19.0
46,lg_refuse_service,1.796700,0.028567,17.944174,1.243084,0.165661,Lesbian/Gay,Views on refusing service to same-sex couples.,23.0,17.0
1,birthright,1.796550,0.029259,15.710361,1.036311,0.129074,Immigration,Support for birthright citizenship for childre...,24.0,28.0
7,min_wage,1.794113,0.028318,15.996795,1.008874,0.071326,Labor,Support for raising the minimum wage / minimum...,25.0,29.0
25,govt_health,1.789673,0.033200,16.227595,1.556133,0.124644,Health,Support for government-provided health insuran...,26.0,7.0
4,immig_levels,1.784536,0.033639,15.687273,0.699658,0.088596,Immigration,Opinion on whether the number of immigrants pe...,27.0,44.0
32,spend_welfare,1.778385,0.025325,16.109501,1.274814,0.094927,Redistribution,Preferences for federal spending on welfare pr...,28.0,16.0
37,black_favor,1.773193,0.028001,17.540172,1.344375,0.135618,Diversity,Attitudes toward whether Black people should r...,29.0,13.0
11,ft_sci,1.772369,0.040353,15.896984,0.922126,0.040673,Institutions,Feeling thermometer rating toward scientists.,30.0,37.0
30,dei_college,1.770178,0.019877,16.934594,1.340520,0.107085,Education,"Views on Diversity, Equity, and Inclusion (DEI...",31.0,14.0
54,israel_aid,1.765294,0.032180,15.529058,0.606856,0.117042,ForeignPolicy,Favor or oppose the U.S. providing military as...,32.0,45.0
3,spend_border,1.763452,0.024095,15.967041,1.550767,0.113009,Immigration,Preferences for federal spending levels on bor...,33.0,8.0
49,env_bus,1.763111,0.026302,16.202407,1.599410,0.109050,Climate,Tradeoff between environmental protection and ...,34.0,5.0
33,spend_poor,1.760746,0.025154,16.368206,1.176851,0.077242,Redistribution,Preferences for federal spending to aid the po...,35.0,21.0
20,ft_police,1.757427,0.040563,15.527693,1.106227,0.063131,CrimeAndPolicing,Feeling thermometer rating toward police.,36.0,24.0
17,gun_imp,1.753602,0.023168,16.588037,0.274799,0.069836,Guns,Importance placed on gun regulation as a polit...,37.0,55.0
55,free_trade,1.751102,0.029859,15.572021,0.284479,0.059593,Trade,Support for free trade policies and reducing t...,38.0,54.0
52,mil_force,1.747367,0.034053,15.489691,0.349896,0.049060,ForeignPolicy,Support for the use of U.S. military force int...,39.0,53.0
56,intl_trade_job,1.746460,0.028545,15.838817,0.153209,0.065719,Trade,Beliefs about international trade’s impact on ...,40.0,58.0
15,gun_bkg_chk,1.743964,0.022274,16.599967,0.497340,0.050344,Guns,Support for background checks on gun purchases...,41.0,50.0
29,spend_school,1.743724,0.023652,16.130591,0.881059,0.077125,Education,Preferences for federal spending on public sch...,42.0,39.0
12,voter_id,1.731982,0.019938,16.070586,1.190985,0.104792,Elections,Support for voter identification requirements ...,43.0,20.0
6,job_gov_guar,1.727385,0.023750,16.172051,1.478903,0.105467,Labor,Support for a government-guaranteed job progra...,44.0,10.0
28,health_spend,1.726808,0.021059,16.494714,0.937116,0.084546,Health,Preference for government spending to help peo...,45.0,36.0
34,svc_spend,1.724792,0.026692,16.052298,1.505273,0.089223,Redistribution,Preferences for government spending on service...,46.0,9.0
18,death_pen,1.724011,0.025835,15.911207,0.999484,0.147272,CrimeAndPolicing,Support for the death penalty/capital punishme...,47.0,32.0
22,crime_spend,1.720885,0.024039,15.962290,0.450729,0.203621,CrimeAndPolicing,Preference for federal spending levels on deal...,48.0,51.0
13,felon_vote,1.720570,0.022434,16.721662,0.820345,0.106281,Elections,Support for restoring or extending voting righ...,49.0,42.0
14,vote_denied,1.717381,0.026822,16.719000,0.534624,0.057321,Elections,Perceived frequency of how often people are de...,50.0,48.0
51,def_spend,1.711116,0.023910,15.828613,1.060406,0.084489,ForeignPolicy,Preferences for government spending on nationa...,51.0,27.0
40,discuss_race,1.709259,0.028054,16.424009,0.516994,0.081306,Diversity,Frequency of discussing race or racial issues ...,52.0,49.0
27,vax_school,1.707693,0.022586,16.323804,0.404883,0.087412,Health,Support for school vaccination requirements fo...,53.0,52.0
38,diversity,1.707128,0.026936,16.127492,0.858743,0.075308,Diversity,Attitudes toward diversity initiatives and/or ...,54.0,40.0
57,limit_imports,1.704713,0.023695,15.570815,1.164392,0.145641,Trade,Support for placing new limits on imports from...,55.0,23.0
19,police_force,1.696776,0.022284,16.067234,1.006237,0.055553,CrimeAndPolicing,Support for police use of force / policing pra...,56.0,31.0
9,journ_access,1.690958,0.022178,16.240637,0.834154,0.104073,Institutions,Support for press/journalist access to governm...,57.0,41.0
10,checks_power,1.681064,0.023061,16.032167,0.226124,0.048869,Institutions,Views on checks and balances and whether branc...,58.0,56.0

In [11]:
unique_areas = df_merged['area'].unique()
unique_areas

array(['Immigration', 'Labor', 'Institutions', 'Elections', 'Guns',
       'CrimeAndPolicing', 'Abortion', 'Health', 'Education',
       'Redistribution', 'Diversity', 'Transgender', 'Lesbian/Gay',
       'Gender', 'Climate', 'ForeignPolicy', 'Trade'], dtype=object)

### Can we look at what subset correlate well and try to reverse engineer what might be the issue ...?

In [ ]:
# Sample subsets and find best correlations
import random
random.seed(42)
np.random.seed(42)

n_iterations = 1000000
results = []
import numpy as np
import pandas as pd
from itertools import product

# Calculate total possible combinations
counts = df_merged.groupby('area')['Topic'].nunique().values
total_possible = np.prod(counts)

print(f"Total possible unique combinations: {total_possible:,}")
print(f"Sampling {n_iterations:,} iterations represents {(n_iterations/total_possible)*100:.4f}% of the search space.")
import random

# 1. Pre-process data for speed
# Create a list of (Avg_Mahalanobis, ANES_Mahalanobis) arrays, one per area
area_data = []
area_topic_names = []
for area in df_merged['area'].unique():
    subset = df_merged[df_merged['area'] == area]
    # We store the values as a numpy array for fast indexing
    area_data.append(subset[["Avg_Mahalanobis", "ANES_Mahalanobis"]].values)
    area_topic_names.append(subset["Topic"].values)

n_areas = len(area_data)

# 2. Pre-generate all random selections (Vectorized sampling)
# This creates a matrix of shape (n_iterations, n_areas)
random_indices = [np.random.randint(0, len(data), n_iterations) for data in area_data]

results = []

# 3. Optimized Loop
for i in range(n_iterations):
    # Extract the pre-selected values for this iteration
    current_sample = np.array([area_data[j][random_indices[j][i]] for j in range(n_areas)])
    
    # current_sample is now (n_areas, 2)
    x = current_sample[:, 0]
    y = current_sample[:, 1]
    
    # Fast correlation (Series objects have overhead, numpy is faster)
    pearson = np.corrcoef(x, y)[0, 1]
    
    # For Spearman, we still use pandas or scipy as numpy doesn't have a direct equivalent
    # But we only do it if we need it to save time
    results.append({
        'iteration': i,
        'pearson': pearson,
        'indices': [random_indices[j][i] for j in range(n_areas)] 
    })

# 4. Post-process top results to get names
df_results = pd.DataFrame(results).sort_values('pearson', ascending=False)

In [20]:
top_10 = df_results.head(30).copy()

# Recover topic names only for the top 10 to save computation
final_output = []
for _, row in top_10.iterrows():
    topics = [area_topic_names[j][row['indices'][j]] for j in range(n_areas)]
    final_output.append({
        'iteration': row['iteration'],
        'pearson': row['pearson'],
        'topics': topics
    })

# Print results
for res in final_output:
    print(f"Iteration {res['iteration']}: Pearson={res['pearson']:.3f}")
    print(f"Topics: {', '.join(res['topics'])}\n")

Iteration 608647: Pearson=0.897
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, crime_spend, scotus_abort, vax_school, affirm_action, spend_welfare, assist_black, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, intl_trade_job

Iteration 508401: Pearson=0.892
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, biden_crime, scotus_abort, vax_school, affirm_action, spend_welfare, discuss_race, trans_military, lg_refuse_service, ft_fem, ghg_emiss, biden_foreign, intl_trade_job

Iteration 325892: Pearson=0.884
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, biden_crime, abortion, vax_school, spend_school, spend_poor, assist_black, trans_military, lg_refuse_service, ft_fem, ghg_emiss, biden_foreign, free_trade

Iteration 138975: Pearson=0.872
Topics: birthright, min_wage, ft_sci, vote_denied, gun_bkg_chk, biden_crime, scotus_abort, vax_school, spend_school, spend_welfare, black_favor, trans_military, lg_refuse_service, ft_fem, clim_imp, israel_aid, free_trade

Iteration 910324: Pearson=0.871
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, biden_crime, abortion, vax_school, spend_school, spend_poor, diversity, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, free_trade

Iteration 981138: Pearson=0.871
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, biden_crime, scotus_abort, govt_health, spend_school, spend_poor, assist_black, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, free_trade

Iteration 428511: Pearson=0.869
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, crime_spend, scotus_abort, health_spend, spend_school, spend_welfare, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, israel_aid, free_trade

Iteration 450774: Pearson=0.865
Topics: birthright, min_wage, checks_power, felon_vote, gun_bkg_chk, crime_spend, scotus_abort, vax_school, spend_school, millionaire_tax, assist_black, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, intl_trade_job

Iteration 548453: Pearson=0.863
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, crime_spend, abortion, vax_school, dei_college, spend_welfare, diversity, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, free_trade

Iteration 49881: Pearson=0.863
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, biden_crime, abortion, vax_school, dei_college, spend_welfare, assist_black, trans_military, lg_refuse_service, ft_fem, ghg_emiss, israel_aid, free_trade

Iteration 669267: Pearson=0.863
Topics: birthright, min_wage, ft_sci, vote_denied, gun_imp, crime_spend, abortion, vax_school, spend_school, millionaire_tax, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, free_trade

Iteration 446263: Pearson=0.862
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, crime_spend, abortion, vax_school, affirm_action, spend_welfare, discuss_race, trans_bath, lg_refuse_service, ft_fem, ghg_emiss, mil_force, free_trade

Iteration 285463: Pearson=0.861
Topics: immig_levels, min_wage, ft_sci, vote_denied, gun_bkg_chk, biden_crime, scotus_abort, vax_school, affirm_action, spend_welfare, assist_black, trans_military, lg_refuse_service, ft_fem, ghg_emiss, biden_foreign, free_trade

Iteration 499783: Pearson=0.860
Topics: birthright, min_wage, ft_sci, felon_vote, gun_bkg_chk, crime_spend, abortion, vax_school, affirm_action, millionaire_tax, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, free_trade

Iteration 21787: Pearson=0.860
Topics: birthright, min_wage, ft_sci, vote_denied, gun_bkg_chk, biden_crime, scotus_abort, vax_school, dei_college, millionaire_tax, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, intl_trade_job

Iteration 220454: Pearson=0.859
Topics: birthright, min_wage, checks_power, vote_denied, gun_bkg_chk, crime_spend, scotus_abort, health_spend, affirm_action, spend_poor, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, israel_aid, free_trade

Iteration 197842: Pearson=0.859
Topics: birthright, min_wage, checks_power, vote_denied, ar_ban, crime_spend, abortion, vax_school, spend_school, spend_poor, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, free_trade

Iteration 272398: Pearson=0.859
Topics: birthright, min_wage, checks_power, vote_denied, gun_imp, ft_police, abortion, vax_school, spend_school, spend_welfare, assist_black, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, free_trade

Iteration 587898: Pearson=0.859
Topics: birthright, min_wage, checks_power, felon_vote, gun_bkg_chk, biden_crime, scotus_abort, vax_school, affirm_action, spend_poor, black_favor, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, intl_trade_job

Iteration 673822: Pearson=0.859
Topics: birthright, min_wage, ft_sci, vote_denied, gun_bkg_chk, crime_spend, scotus_abort, govt_health, spend_school, spend_welfare, discuss_race, trans_military, lg_refuse_service, ft_fem, ghg_emiss, biden_foreign, free_trade

Iteration 578287: Pearson=0.857
Topics: birthright, min_wage, checks_power, vote_denied, gun_imp, biden_crime, scotus_abort, govt_health, spend_school, spend_welfare, assist_black, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, intl_trade_job

Iteration 467118: Pearson=0.856
Topics: immig_levels, min_wage, checks_power, vote_denied, gun_imp, crime_spend, scotus_abort, vax_school, affirm_action, spend_poor, assist_black, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, intl_trade_job

Iteration 804029: Pearson=0.855
Topics: birthright, min_wage, ft_sci, vote_denied, gun_imp, crime_spend, abortion, vax_school, spend_school, spend_poor, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, intl_trade_job

Iteration 199989: Pearson=0.854
Topics: immig_levels, ft_union, checks_power, vote_denied, gun_bkg_chk, crime_spend, scotus_abort, vax_school, affirm_action, millionaire_tax, discuss_race, trans_military, lg_refuse_service, ft_fem, ghg_emiss, israel_aid, intl_trade_job

Iteration 925683: Pearson=0.854
Topics: imm_unauth, min_wage, checks_power, felon_vote, gun_bkg_chk, biden_crime, scotus_abort, vax_school, affirm_action, spend_welfare, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, intl_trade_job

Iteration 121691: Pearson=0.853
Topics: imm_unauth, ft_union, checks_power, vote_denied, gun_bkg_chk, biden_crime, abortion, vax_school, affirm_action, spend_welfare, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, intl_trade_job

Iteration 888245: Pearson=0.853
Topics: birthright, ft_union, ft_sci, vote_denied, gun_bkg_chk, biden_crime, abortion, vax_school, affirm_action, spend_welfare, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, mil_force, intl_trade_job

Iteration 670854: Pearson=0.853
Topics: imm_unauth, min_wage, checks_power, felon_vote, gun_bkg_chk, biden_crime, abortion, vax_school, dei_college, spend_poor, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, biden_foreign, free_trade

Iteration 85922: Pearson=0.852
Topics: immig_levels, min_wage, checks_power, vote_denied, gun_imp, biden_crime, abortion, vax_school, spend_school, spend_poor, discuss_race, trans_military, lg_refuse_service, ft_fem, clim_imp, israel_aid, free_trade

Iteration 784764: Pearson=0.852
Topics: birthright, min_wage, checks_power, felon_vote, gun_bkg_chk, crime_spend, abortion, vax_school, affirm_action, millionaire_tax, assist_black, trans_military, lg_refuse_service, ft_fem, clim_imp, israel_aid, intl_trade_job

In [13]:
df_merged

,Topic,Avg_Mahalanobis,Avg_Total_Dispersion,Polarization_CoG,ANES_Mahalanobis,ANES_Variance,area,explanation,LLM_rank,ANES_rank
0,imm_unauth,1.821281,0.027519,16.267675,1.007885,0.087450,Immigration,Policy preferences regarding unauthorized/undo...,11.0,30.0
1,birthright,1.796550,0.029259,15.710361,1.036311,0.129074,Immigration,Support for birthright citizenship for childre...,24.0,28.0
2,illeg_child,1.842531,0.034320,17.001089,0.948134,0.075581,Immigration,Views on how the U.S. should handle children o...,4.0,34.0
3,spend_border,1.763452,0.024095,15.967041,1.550767,0.113009,Immigration,Preferences for federal spending levels on bor...,33.0,8.0
4,immig_levels,1.784536,0.033639,15.687273,0.699658,0.088596,Immigration,Opinion on whether the number of immigrants pe...,27.0,44.0
5,paid_leave,1.851979,0.025422,16.712534,0.713889,0.072350,Labor,Support for paid parental/family leave policie...,3.0,43.0
6,job_gov_guar,1.727385,0.023750,16.172051,1.478903,0.105467,Labor,Support for a government-guaranteed job progra...,44.0,10.0
7,min_wage,1.794113,0.028318,15.996795,1.008874,0.071326,Labor,Support for raising the minimum wage / minimum...,25.0,29.0
8,ft_union,1.822874,0.034088,16.232798,0.963094,0.057614,Labor,Feeling thermometer rating toward labor unions.,10.0,33.0
9,journ_access,1.690958,0.022178,16.240637,0.834154,0.104073,Institutions,Support for press/journalist access to governm...,57.0,41.0
10,checks_power,1.681064,0.023061,16.032167,0.226124,0.048869,Institutions,Views on checks and balances and whether branc...,58.0,56.0
11,ft_sci,1.772369,0.040353,15.896984,0.922126,0.040673,Institutions,Feeling thermometer rating toward scientists.,30.0,37.0
12,voter_id,1.731982,0.019938,16.070586,1.190985,0.104792,Elections,Support for voter identification requirements ...,43.0,20.0
13,felon_vote,1.720570,0.022434,16.721662,0.820345,0.106281,Elections,Support for restoring or extending voting righ...,49.0,42.0
14,vote_denied,1.717381,0.026822,16.719000,0.534624,0.057321,Elections,Perceived frequency of how often people are de...,50.0,48.0
15,gun_bkg_chk,1.743964,0.022274,16.599967,0.497340,0.050344,Guns,Support for background checks on gun purchases...,41.0,50.0
16,ar_ban,1.824237,0.024441,16.684285,0.940938,0.157338,Guns,Support for banning assault rifles/assault wea...,9.0,35.0
17,gun_imp,1.753602,0.023168,16.588037,0.274799,0.069836,Guns,Importance placed on gun regulation as a polit...,37.0,55.0
18,death_pen,1.724011,0.025835,15.911207,0.999484,0.147272,CrimeAndPolicing,Support for the death penalty/capital punishme...,47.0,32.0
19,police_force,1.696776,0.022284,16.067234,1.006237,0.055553,CrimeAndPolicing,Support for police use of force / policing pra...,56.0,31.0
20,ft_police,1.757427,0.040563,15.527693,1.106227,0.063131,CrimeAndPolicing,Feeling thermometer rating toward police.,36.0,24.0
21,biden_crime,1.832470,0.032374,16.263938,1.923465,0.160533,CrimeAndPolicing,Approval of Joe Biden's handling of crime.,7.0,2.0
22,crime_spend,1.720885,0.024039,15.962290,0.450729,0.203621,CrimeAndPolicing,Preference for federal spending levels on deal...,48.0,51.0
23,abortion,1.814286,0.033471,16.196626,1.232532,0.132176,Abortion,Attitudes toward abortion legality and access.,13.0,18.0
24,scotus_abort,1.808586,0.029181,16.343610,1.413303,0.120520,Abortion,Views on Supreme Court decisions and judicial ...,17.0,11.0
25,govt_health,1.789673,0.033200,16.227595,1.556133,0.124644,Health,Support for government-provided health insuran...,26.0,7.0
26,obamacare,1.807128,0.026574,16.529290,2.408148,0.151637,Health,Attitudes toward the Affordable Care Act (ACA/...,18.0,1.0
27,vax_school,1.707693,0.022586,16.323804,0.404883,0.087412,Health,Support for school vaccination requirements fo...,53.0,52.0
28,health_spend,1.726808,0.021059,16.494714,0.937116,0.084546,Health,Preference for government spending to help peo...,45.0,36.0
29,spend_school,1.743724,0.023652,16.130591,0.881059,0.077125,Education,Preferences for federal spending on public sch...,42.0,39.0
30,dei_college,1.770178,0.019877,16.934594,1.340520,0.107085,Education,"Views on Diversity, Equity, and Inclusion (DEI...",31.0,14.0
31,affirm_action,1.811137,0.026710,16.047997,1.082133,0.090213,Education,Favor or oppose affirmative action in universi...,15.0,25.0
32,spend_welfare,1.778385,0.025325,16.109501,1.274814,0.094927,Redistribution,Preferences for federal spending on welfare pr...,28.0,16.0
33,spend_poor,1.760746,0.025154,16.368206,1.176851,0.077242,Redistribution,Preferences for federal spending to aid the po...,35.0,21.0
34,svc_spend,1.724792,0.026692,16.052298,1.505273,0.089223,Redistribution,Preferences for government spending on service...,46.0,9.0
35,millionaire_tax,1.807000,0.028034,16.306700,0.918373,0.156521,Redistribution,Support for taxes targeting millionaires.,19.0,38.0
36,assist_black,1.802129,0.031556,17.116644,1.623140,0.112476,Diversity,Support for government assistance to Black Ame...,20.0,4.0
37,black_favor,1.773193,0.028001,17.540172,1.344375,0.135618,Diversity,Attitudes toward whether Black people should r...,29.0,13.0
38,diversity,1.707128,0.026936,16.127492,0.858743,0.075308,Diversity,Attitudes toward diversity initiatives and/or ...,54.0,40.0
39,ft_asian,1.798940,0.045398,17.394634,0.222862,0.043342,Diversity,Feeling thermometer rating toward Asian-Americ...,21.0,57.0
40,discuss_race,1.709259,0.028054,16.424009,0.516994,0.081306,Diversity,Frequency of discussing race or racial issues ...,52.0,49.0
41,trans_bath,1.884847,0.033458,18.921809,1.276135,0.161220,Transgender,Views on transgender bathroom access policies.,2.0,15.0
42,trans_military,1.798262,0.033186,17.560136,1.205945,0.104121,Transgender,Views on transgender people serving in the U.S...,22.0,19.0
43,ft_trans,1.897050,0.042290,18.264347,1.069882,0.076328,Transgender,Feeling thermometer rating toward transgender ...,1.0,26.0
44,lg_job,1.841690,0.036985,17.579029,0.602085,0.088672,Lesbian/Gay,Views on legal protections against job discrim...,5.0,46.5
45,lg_marry,1.827036,0.034325,16.754018,0.602085,0.088672,Lesbian/Gay,Support for same-sex marriage / marriage right...,8.0,46.5
46,lg_refuse_service,1.796700,0.028567,17.944174,1.243084,0.165661,Lesbian/Gay,Views on refusing service to same-sex couples.,23.0,17.0
47,ft_fem,1.811181,0.046814,16.600159,1.355457,0.071815,Gender,Feeling thermometer rating toward feminists.,14.0,12.0
48,clim_imp,1.833248,0.037742,16.992993,1.565396,0.114112,Climate,Importance assigned to climate change as an is...,6.0,6.0
49,env_bus,1.763111,0.026302,16.202407,1.599410,0.109050,Climate,Tradeoff between environmental protection and ...,34.0,5.0
50,ghg_emiss,1.809828,0.030766,16.380480,1.169356,0.097797,Climate,Support for regulating greenhouse gas emission...,16.0,22.0
51,def_spend,1.711116,0.023910,15.828613,1.060406,0.084489,ForeignPolicy,Preferences for government spending on nationa...,51.0,27.0
52,mil_force,1.747367,0.034053,15.489691,0.349896,0.049060,ForeignPolicy,Support for the use of U.S. military force int...,39.0,53.0
53,biden_foreign,1.818323,0.035813,15.887371,1.700641,0.173603,ForeignPolicy,Approval of Joe Biden's handling of foreign re...,12.0,3.0
54,israel_aid,1.765294,0.032180,15.529058,0.606856,0.117042,ForeignPolicy,Favor or oppose the U.S. providing military as...,32.0,45.0
55,free_trade,1.751102,0.029859,15.572021,0.284479,0.059593,Trade,Support for free trade policies and reducing t...,38.0,54.0
56,intl_trade_job,1.746460,0.028545,15.838817,0.153209,0.065719,Trade,Beliefs about international trade’s impact on ...,40.0,58.0
57,limit_imports,1.704713,0.023695,15.570815,1.164392,0.145641,Trade,Support for placing new limits on imports from...,55.0,23.0

In [14]:
def compare_standardized_columns(df, col1, col2, group_by='area'):
    """
    Demean and standardize two columns separately, calculate their difference,
    and group by specified column.
    
    Parameters:
    - df: DataFrame containing the data
    - col1: First column name to standardize
    - col2: Second column name to standardize
    - group_by: Column name to group results by (default 'area')
    
    Returns:
    - Modified DataFrame with normalized columns and difference
    """
    # Create a copy to avoid modifying original
    df_work = df.copy()
    
    # Demean and standardize each column separately
    mean1 = df_work[col1].mean()
    std1 = df_work[col1].std()
    mean2 = df_work[col2].mean()
    std2 = df_work[col2].std()
    
    col1_norm = col1 + '_norm'
    col2_norm = col2 + '_norm'
    
    df_work[col1_norm] = (df_work[col1] - mean1) / std1
    df_work[col2_norm] = (df_work[col2] - mean2) / std2
    
    # Calculate difference between standardized columns
    df_work['diff'] = df_work[col1_norm] - df_work[col2_norm]
    
    # Calculate mean differences by group
    group_diff = df_work.groupby(group_by).agg({
        'diff': ['mean', 'count']
    }).round(4)
    
    group_diff.columns = ['mean_diff', 'n_topics']
    group_diff = group_diff.sort_values('mean_diff', ascending=False)
    
    print(f"Standardized Differences by {group_by}:")
    print(group_diff)
    
    print("\nDetailed breakdown:")
    print(df_work[['Topic', group_by, col1_norm, col2_norm, 'diff', "Polarization_CoG"]].sort_values('diff', ascending=False).to_markdown())
    
    return df_work

# Compare Avg_Total_Dispersion (LLM) with ANES_Variance
df_diff = compare_standardized_columns(df_merged, 'Avg_Mahalanobis', 'ANES_Mahalanobis', group_by='area')

Standardized Differences by area:
                  mean_diff  n_topics
area
Lesbian/Gay          1.3792         3
Transgender          1.3398         3
Guns                 0.9566         3
Immigration          0.4688         5
Labor                0.4332         4
Trade                0.2412         3
Abortion             0.0652         2
Gender              -0.0109         1
ForeignPolicy       -0.0935         4
Diversity           -0.1059         5
Education           -0.1789         3
Climate             -0.3879         3
Institutions        -0.4209         3
Redistribution      -0.5810         4
Elections           -0.6607         3
CrimeAndPolicing    -0.7436         5
Health              -1.0140         4

Detailed breakdown:
|    | Topic             | area             |   Avg_Mahalanobis_norm |   ANES_Mahalanobis_norm |        diff |   Polarization_CoG |
|---:|:------------------|:-----------------|-----------------------:|------------------------:|------------:|-------------------:|
| 43 | ft_trans          | Transgender      |              2.4489    |               0.120853  |  2.32805    |            18.2643 |
| 44 | lg_job            | Lesbian/Gay      |              1.34273   |              -0.899976  |  2.24271    |            17.579  |
| 39 | ft_asian          | Diversity        |              0.488516  |              -1.72752   |  2.21603    |            17.3946 |
|  5 | paid_leave        | Labor            |              1.54831   |              -0.655997  |  2.2043     |            16.7125 |
| 45 | lg_marry          | Lesbian/Gay      |              1.04991   |              -0.899976  |  1.94988    |            16.754  |
| 41 | trans_bath        | Transgender      |              2.20507   |               0.57094   |  1.63412    |            18.9218 |
|  2 | illeg_child       | Immigration      |              1.35952   |              -0.144827  |  1.50435    |            17.0011 |
| 56 | intl_trade_job    | Trade            |             -0.560118  |              -1.87952   |  1.3194     |            15.8388 |
| 17 | gun_imp           | Guns             |             -0.417394  |              -1.61418   |  1.19679    |            16.588  |
| 16 | ar_ban            | Guns             |              0.993994  |              -0.160529  |  1.15452    |            16.6843 |
| 55 | free_trade        | Trade            |             -0.467362  |              -1.59306   |  1.1257     |            15.572  |
|  8 | ft_union          | Labor            |              0.966757  |              -0.112181  |  1.07894    |            16.2328 |
|  0 | imm_unauth        | Immigration      |              0.934921  |              -0.0144371 |  0.949358   |            16.2677 |
| 52 | mil_force         | ForeignPolicy    |             -0.541987  |              -1.4503    |  0.908317   |            15.4897 |
|  4 | immig_levels      | Immigration      |              0.200695  |              -0.687053  |  0.887748   |            15.6873 |
| 35 | millionaire_tax   | Redistribution   |              0.649572  |              -0.209771  |  0.859344   |            16.3067 |
| 54 | israel_aid        | ForeignPolicy    |             -0.183786  |              -0.889565  |  0.705779   |            15.5291 |
| 31 | affirm_action     | Education        |              0.732225  |               0.147586  |  0.584639   |            16.048  |
| 15 | gun_bkg_chk       | Guns             |             -0.609979  |              -1.12855   |  0.518573   |            16.6    |
|  7 | min_wage          | Labor            |              0.392065  |              -0.0122783 |  0.404344   |            15.9968 |
|  1 | birthright        | Immigration      |              0.440756  |               0.0475933 |  0.393163   |            15.7104 |
| 50 | ghg_emiss         | Climate          |              0.706077  |               0.337926  |  0.368151   |            16.3805 |
| 23 | abortion          | Abortion         |              0.795147  |               0.475788  |  0.319359   |            16.1966 |
| 11 | ft_sci            | Institutions     |             -0.0424166 |              -0.201582  |  0.159165   |            15.897  |
| 22 | crime_spend       | CrimeAndPolicing |             -1.07113   |              -1.23027   |  0.159134   |            15.9623 |
| 42 | trans_military    | Transgender      |              0.47497   |               0.41777   |  0.0571998  |            17.5601 |
| 27 | vax_school        | Health           |             -1.33474   |              -1.33031   | -0.00442252 |            16.3238 |
| 47 | ft_fem            | Gender           |              0.733111  |               0.744037  | -0.0109259  |            16.6002 |
| 48 | clim_imp          | Climate          |              1.17403   |               1.20217   | -0.0281368  |            16.993  |
| 46 | lg_refuse_service | Lesbian/Gay      |              0.443755  |               0.498815  | -0.0550603  |            17.9442 |
| 14 | vote_denied       | Elections        |             -1.14115   |              -1.04719   | -0.0939606  |            16.719  |
| 10 | checks_power      | Institutions     |             -1.86682   |              -1.7204    | -0.146422   |            16.0322 |
| 24 | scotus_abort      | Abortion         |              0.681252  |               0.870267  | -0.189016   |            16.3436 |
| 40 | discuss_race      | Diversity        |             -1.30343   |              -1.08566   | -0.217772   |            16.424  |
| 29 | spend_school      | Education        |             -0.614783  |              -0.291199  | -0.323585   |            16.1306 |
| 32 | spend_welfare     | Redistribution   |              0.077807  |               0.568056  | -0.490249   |            16.1095 |
| 20 | ft_police         | CrimeAndPolicing |             -0.340972  |               0.200164  | -0.541136   |            15.5277 |
| 53 | biden_foreign     | ForeignPolicy    |              0.87581   |               1.4973    | -0.621488   |            15.8874 |
| 33 | spend_poor        | Redistribution   |             -0.27466   |               0.35428   | -0.62894    |            16.3682 |
| 13 | felon_vote        | Elections        |             -1.07743   |              -0.423688  | -0.653738   |            16.7217 |
| 37 | black_favor       | Diversity        |             -0.0259491 |               0.719852  | -0.745801   |            17.5402 |
| 36 | assist_black      | Diversity        |              0.552233  |               1.32818   | -0.775944   |            17.1166 |
| 28 | health_spend      | Health           |             -0.952786  |              -0.168871  | -0.783915   |            16.4947 |
| 30 | dei_college       | Education        |             -0.0861856 |               0.71144   | -0.797625   |            16.9346 |
| 21 | biden_crime       | CrimeAndPolicing |              1.1585    |               1.98355   | -0.825045   |            16.2639 |
| 25 | govt_health       | Health           |              0.303339  |               1.18195   | -0.878614   |            16.2276 |
| 18 | death_pen         | CrimeAndPolicing |             -1.00868   |              -0.0327709 | -0.975912   |            15.9112 |
| 38 | diversity         | Diversity        |             -1.34603   |              -0.339896  | -1.00613    |            16.1275 |
| 12 | voter_id          | Elections        |             -0.849391  |               0.385124  | -1.23452    |            16.0706 |
|  9 | journ_access      | Institutions     |             -1.66911   |              -0.393553  | -1.27556    |            16.2406 |
| 51 | def_spend         | ForeignPolicy    |             -1.26632   |               0.100173  | -1.3665     |            15.8286 |
|  3 | spend_border      | Immigration      |             -0.220584  |               1.17024   | -1.39083    |            15.967  |
| 49 | env_bus           | Climate          |             -0.227409  |               1.27639   | -1.5038     |            16.2024 |
| 19 | police_force      | CrimeAndPolicing |             -1.55287   |              -0.0180327 | -1.53484    |            16.0672 |
| 57 | limit_imports     | Trade            |             -1.39428   |               0.327093  | -1.72137    |            15.5708 |
|  6 | job_gov_guar      | Labor            |             -0.941256  |               1.01342   | -1.95468    |            16.1721 |
| 34 | svc_spend         | Redistribution   |             -0.993068  |               1.07097   | -2.06403    |            16.0523 |
| 26 | obamacare         | Health           |              0.652122  |               3.04122   | -2.3891     |            16.5293 |

In [15]:
corr = df_diff['diff'].corr(df_diff['Polarization_CoG'], method='pearson')
print(f"Pearson correlation between standardized difference and Polarization_CoG: {corr:.3f}")

Pearson correlation between standardized difference and Polarization_CoG: 0.356

In [16]:
# restrict area to some areas
df_subset = df_merged[df_merged['area'].isin(['Policing', 'Labor', "Immigration", "Education", "Redistribution"])]
pearson_corr_subset = df_subset["Avg_Mahalanobis"].corr(
    df_subset["ANES_Mahalanobis"],
    method="pearson"
)
print(f"\nSubset Pearson correlation: {pearson_corr_subset:.3f}")
spearman_corr_subset = df_subset["Avg_Mahalanobis"].corr(
    df_subset["ANES_Mahalanobis"],
    method="spearman"
)
print(f"Subset Spearman correlation: {spearman_corr_subset:.3f}")

Subset Pearson correlation: -0.674
Subset Spearman correlation: -0.594

## Comparing Total Variance between ANES and LLM

In [17]:

pearson_corr = df_merged["Avg_Total_Dispersion"].corr(
    df_merged["ANES_Variance"],
    method="pearson"
)

print(f"Pearson correlation: {pearson_corr:.3f}")
spearman_corr = df_merged["Avg_Total_Dispersion"].corr(
    df_merged["ANES_Variance"],
    method="spearman"
)

print(f"Spearman correlation: {spearman_corr:.3f}")
df_merged["LLM_rank"] = df_merged["Avg_Total_Dispersion"].rank(ascending=False)
df_merged["ANES_rank"] = df_merged["ANES_Variance"].rank(ascending=False)

df_merged.sort_values("Avg_Total_Dispersion", ascending=False)

Pearson correlation: -0.147
Spearman correlation: -0.056

,Topic,Avg_Mahalanobis,Avg_Total_Dispersion,Polarization_CoG,ANES_Mahalanobis,ANES_Variance,area,explanation,LLM_rank,ANES_rank
47,ft_fem,1.811181,0.046814,16.600159,1.355457,0.071815,Gender,Feeling thermometer rating toward feminists.,1.0,45.0
39,ft_asian,1.798940,0.045398,17.394634,0.222862,0.043342,Diversity,Feeling thermometer rating toward Asian-Americ...,2.0,57.0
43,ft_trans,1.897050,0.042290,18.264347,1.069882,0.076328,Transgender,Feeling thermometer rating toward transgender ...,3.0,41.0
20,ft_police,1.757427,0.040563,15.527693,1.106227,0.063131,CrimeAndPolicing,Feeling thermometer rating toward police.,4.0,49.0
11,ft_sci,1.772369,0.040353,15.896984,0.922126,0.040673,Institutions,Feeling thermometer rating toward scientists.,5.0,58.0
48,clim_imp,1.833248,0.037742,16.992993,1.565396,0.114112,Climate,Importance assigned to climate change as an is...,6.0,17.0
44,lg_job,1.841690,0.036985,17.579029,0.602085,0.088672,Lesbian/Gay,Views on legal protections against job discrim...,7.0,31.5
53,biden_foreign,1.818323,0.035813,15.887371,1.700641,0.173603,ForeignPolicy,Approval of Joe Biden's handling of foreign re...,8.0,2.0
45,lg_marry,1.827036,0.034325,16.754018,0.602085,0.088672,Lesbian/Gay,Support for same-sex marriage / marriage right...,9.0,31.5
2,illeg_child,1.842531,0.034320,17.001089,0.948134,0.075581,Immigration,Views on how the U.S. should handle children o...,10.0,42.0
8,ft_union,1.822874,0.034088,16.232798,0.963094,0.057614,Labor,Feeling thermometer rating toward labor unions.,11.0,51.0
52,mil_force,1.747367,0.034053,15.489691,0.349896,0.049060,ForeignPolicy,Support for the use of U.S. military force int...,12.0,55.0
4,immig_levels,1.784536,0.033639,15.687273,0.699658,0.088596,Immigration,Opinion on whether the number of immigrants pe...,13.0,33.0
23,abortion,1.814286,0.033471,16.196626,1.232532,0.132176,Abortion,Attitudes toward abortion legality and access.,14.0,12.0
41,trans_bath,1.884847,0.033458,18.921809,1.276135,0.161220,Transgender,Views on transgender bathroom access policies.,15.0,4.0
25,govt_health,1.789673,0.033200,16.227595,1.556133,0.124644,Health,Support for government-provided health insuran...,16.0,14.0
42,trans_military,1.798262,0.033186,17.560136,1.205945,0.104121,Transgender,Views on transgender people serving in the U.S...,17.0,25.0
21,biden_crime,1.832470,0.032374,16.263938,1.923465,0.160533,CrimeAndPolicing,Approval of Joe Biden's handling of crime.,18.0,5.0
54,israel_aid,1.765294,0.032180,15.529058,0.606856,0.117042,ForeignPolicy,Favor or oppose the U.S. providing military as...,19.0,16.0
36,assist_black,1.802129,0.031556,17.116644,1.623140,0.112476,Diversity,Support for government assistance to Black Ame...,20.0,19.0
50,ghg_emiss,1.809828,0.030766,16.380480,1.169356,0.097797,Climate,Support for regulating greenhouse gas emission...,21.0,27.0
55,free_trade,1.751102,0.029859,15.572021,0.284479,0.059593,Trade,Support for free trade policies and reducing t...,22.0,50.0
1,birthright,1.796550,0.029259,15.710361,1.036311,0.129074,Immigration,Support for birthright citizenship for childre...,23.0,13.0
24,scotus_abort,1.808586,0.029181,16.343610,1.413303,0.120520,Abortion,Views on Supreme Court decisions and judicial ...,24.0,15.0
46,lg_refuse_service,1.796700,0.028567,17.944174,1.243084,0.165661,Lesbian/Gay,Views on refusing service to same-sex couples.,25.0,3.0
56,intl_trade_job,1.746460,0.028545,15.838817,0.153209,0.065719,Trade,Beliefs about international trade’s impact on ...,26.0,48.0
7,min_wage,1.794113,0.028318,15.996795,1.008874,0.071326,Labor,Support for raising the minimum wage / minimum...,27.0,46.0
40,discuss_race,1.709259,0.028054,16.424009,0.516994,0.081306,Diversity,Frequency of discussing race or racial issues ...,28.0,38.0
35,millionaire_tax,1.807000,0.028034,16.306700,0.918373,0.156521,Redistribution,Support for taxes targeting millionaires.,29.0,7.0
37,black_favor,1.773193,0.028001,17.540172,1.344375,0.135618,Diversity,Attitudes toward whether Black people should r...,30.0,11.0
0,imm_unauth,1.821281,0.027519,16.267675,1.007885,0.087450,Immigration,Policy preferences regarding unauthorized/undo...,31.0,34.0
38,diversity,1.707128,0.026936,16.127492,0.858743,0.075308,Diversity,Attitudes toward diversity initiatives and/or ...,32.0,43.0
14,vote_denied,1.717381,0.026822,16.719000,0.534624,0.057321,Elections,Perceived frequency of how often people are de...,33.0,52.0
31,affirm_action,1.811137,0.026710,16.047997,1.082133,0.090213,Education,Favor or oppose affirmative action in universi...,34.0,29.0
34,svc_spend,1.724792,0.026692,16.052298,1.505273,0.089223,Redistribution,Preferences for government spending on service...,35.0,30.0
26,obamacare,1.807128,0.026574,16.529290,2.408148,0.151637,Health,Attitudes toward the Affordable Care Act (ACA/...,36.0,8.0
49,env_bus,1.763111,0.026302,16.202407,1.599410,0.109050,Climate,Tradeoff between environmental protection and ...,37.0,20.0
18,death_pen,1.724011,0.025835,15.911207,0.999484,0.147272,CrimeAndPolicing,Support for the death penalty/capital punishme...,38.0,9.0
5,paid_leave,1.851979,0.025422,16.712534,0.713889,0.072350,Labor,Support for paid parental/family leave policie...,39.0,44.0
32,spend_welfare,1.778385,0.025325,16.109501,1.274814,0.094927,Redistribution,Preferences for federal spending on welfare pr...,40.0,28.0
33,spend_poor,1.760746,0.025154,16.368206,1.176851,0.077242,Redistribution,Preferences for federal spending to aid the po...,41.0,39.0
16,ar_ban,1.824237,0.024441,16.684285,0.940938,0.157338,Guns,Support for banning assault rifles/assault wea...,42.0,6.0
3,spend_border,1.763452,0.024095,15.967041,1.550767,0.113009,Immigration,Preferences for federal spending levels on bor...,43.0,18.0
22,crime_spend,1.720885,0.024039,15.962290,0.450729,0.203621,CrimeAndPolicing,Preference for federal spending levels on deal...,44.0,1.0
51,def_spend,1.711116,0.023910,15.828613,1.060406,0.084489,ForeignPolicy,Preferences for government spending on nationa...,45.0,37.0
6,job_gov_guar,1.727385,0.023750,16.172051,1.478903,0.105467,Labor,Support for a government-guaranteed job progra...,46.0,23.0
57,limit_imports,1.704713,0.023695,15.570815,1.164392,0.145641,Trade,Support for placing new limits on imports from...,47.0,10.0
29,spend_school,1.743724,0.023652,16.130591,0.881059,0.077125,Education,Preferences for federal spending on public sch...,48.0,40.0
17,gun_imp,1.753602,0.023168,16.588037,0.274799,0.069836,Guns,Importance placed on gun regulation as a polit...,49.0,47.0
10,checks_power,1.681064,0.023061,16.032167,0.226124,0.048869,Institutions,Views on checks and balances and whether branc...,50.0,56.0
27,vax_school,1.707693,0.022586,16.323804,0.404883,0.087412,Health,Support for school vaccination requirements fo...,51.0,35.0
13,felon_vote,1.720570,0.022434,16.721662,0.820345,0.106281,Elections,Support for restoring or extending voting righ...,52.0,22.0
19,police_force,1.696776,0.022284,16.067234,1.006237,0.055553,CrimeAndPolicing,Support for police use of force / policing pra...,53.0,53.0
15,gun_bkg_chk,1.743964,0.022274,16.599967,0.497340,0.050344,Guns,Support for background checks on gun purchases...,54.0,54.0
9,journ_access,1.690958,0.022178,16.240637,0.834154,0.104073,Institutions,Support for press/journalist access to governm...,55.0,26.0
28,health_spend,1.726808,0.021059,16.494714,0.937116,0.084546,Health,Preference for government spending to help peo...,56.0,36.0
12,voter_id,1.731982,0.019938,16.070586,1.190985,0.104792,Elections,Support for voter identification requirements ...,57.0,24.0
30,dei_college,1.770178,0.019877,16.934594,1.340520,0.107085,Education,"Views on Diversity, Equity, and Inclusion (DEI...",58.0,21.0

In [18]:
df_merged = compare_standardized_columns(df_merged, 'Avg_Total_Dispersion', 'ANES_Variance')

Standardized Differences by area:
                  mean_diff  n_topics
area
Gender               3.5735         1
Institutions         0.8501         3
Transgender          0.7636         3
Diversity            0.7272         5
Labor                0.4213         4
Lesbian/Gay          0.2696         3
ForeignPolicy        0.2048         4
Climate              0.1978         3
Immigration          0.1265         5
Trade               -0.0300         3
Abortion            -0.3677         2
Redistribution      -0.5813         4
Education           -0.6923         3
Elections           -0.6938         3
CrimeAndPolicing    -0.7274         5
Guns                -0.7390         3
Health              -0.8567         4

Detailed breakdown:
|    | Topic             | area             |   Avg_Total_Dispersion_norm |   ANES_Variance_norm |       diff |   Polarization_CoG |
|---:|:------------------|:-----------------|----------------------------:|---------------------:|-----------:|-------------------:|
| 39 | ft_asian          | Diversity        |                  2.59593    |           -1.51808   |  4.11401   |            17.3946 |
| 47 | ft_fem            | Gender           |                  2.82205    |           -0.751456  |  3.5735    |            16.6002 |
| 11 | ft_sci            | Institutions     |                  1.79036    |           -1.58993   |  3.38029   |            15.897  |
| 20 | ft_police         | CrimeAndPolicing |                  1.82384    |           -0.985262  |  2.80911   |            15.5277 |
| 43 | ft_trans          | Transgender      |                  2.09972    |           -0.62993   |  2.72965   |            18.2643 |
| 52 | mil_force         | ForeignPolicy    |                  0.784444   |           -1.36412   |  2.14856   |            15.4897 |
|  8 | ft_union          | Labor            |                  0.790053   |           -1.13381   |  1.92386   |            16.2328 |
| 44 | lg_job            | Lesbian/Gay      |                  1.25266    |           -0.297585  |  1.55025   |            17.579  |
|  2 | illeg_child       | Immigration      |                  0.827067   |           -0.650053  |  1.47712   |            17.0011 |
| 55 | free_trade        | Trade            |                  0.1148     |           -1.08051   |  1.19531   |            15.572  |
| 45 | lg_marry          | Lesbian/Gay      |                  0.827821   |           -0.297585  |  1.12541   |            16.754  |
|  4 | immig_levels      | Immigration      |                  0.718384   |           -0.299616  |  1.018     |            15.6873 |
| 48 | clim_imp          | Climate          |                  1.3735     |            0.387366  |  0.98613   |            16.993  |
| 56 | intl_trade_job    | Trade            |                 -0.0950823  |           -0.915591  |  0.820509  |            15.8388 |
| 14 | vote_denied       | Elections        |                 -0.370109   |           -1.14168   |  0.77157   |            16.719  |
|  7 | min_wage          | Labor            |                 -0.131324   |           -0.764607  |  0.633284  |            15.9968 |
| 42 | trans_military    | Transgender      |                  0.645941   |            0.118381  |  0.52756   |            17.5601 |
| 10 | checks_power      | Institutions     |                 -0.970608   |           -1.36926   |  0.39865   |            16.0322 |
| 40 | discuss_race      | Diversity        |                 -0.173433   |           -0.495897  |  0.322464  |            16.424  |
| 50 | ghg_emiss         | Climate          |                  0.25959    |           -0.0518959 |  0.311486  |            16.3805 |
| 38 | diversity         | Diversity        |                 -0.351892   |           -0.65741   |  0.305519  |            16.1275 |
| 15 | gun_bkg_chk       | Guns             |                 -1.09632    |           -1.32954   |  0.233218  |            16.6    |
|  5 | paid_leave        | Labor            |                 -0.593697   |           -0.737032  |  0.143335  |            16.7125 |
| 19 | police_force      | CrimeAndPolicing |                 -1.09465    |           -1.18931   |  0.0946597 |            16.0672 |
|  0 | imm_unauth        | Immigration      |                 -0.258871   |           -0.330482  |  0.0716118 |            16.2677 |
| 36 | assist_black      | Diversity        |                  0.385723   |            0.343314  |  0.042409  |            17.1166 |
| 54 | israel_aid        | ForeignPolicy    |                  0.485426   |            0.466256  |  0.0191698 |            15.5291 |
| 25 | govt_health       | Health           |                  0.648283   |            0.670946  | -0.0226633 |            16.2276 |
| 33 | spend_poor        | Redistribution   |                 -0.636398   |           -0.605336  | -0.0310625 |            16.3682 |
| 34 | svc_spend         | Redistribution   |                 -0.390843   |           -0.282738  | -0.108106  |            16.0523 |
| 31 | affirm_action     | Education        |                 -0.388009   |           -0.256087  | -0.131922  |            16.048  |
| 17 | gun_imp           | Guns             |                 -0.953514   |           -0.804733  | -0.148781  |            16.588  |
| 23 | abortion          | Abortion         |                  0.691594   |            0.873732  | -0.182138  |            16.1966 |
| 29 | spend_school      | Education        |                 -0.876209   |           -0.60849   | -0.267719  |            16.1306 |
| 51 | def_spend         | ForeignPolicy    |                 -0.835112   |           -0.410217  | -0.424894  |            15.8286 |
| 32 | spend_welfare     | Redistribution   |                 -0.609223   |           -0.129158  | -0.480065  |            16.1095 |
| 24 | scotus_abort      | Abortion         |                  0.00658911 |            0.5599    | -0.553311  |            16.3436 |
| 49 | env_bus           | Climate          |                 -0.453145   |            0.251084  | -0.704229  |            16.2024 |
| 27 | vax_school        | Health           |                 -1.04651    |           -0.331499  | -0.71501   |            16.3238 |
|  1 | birthright        | Immigration      |                  0.0190516  |            0.790208  | -0.771156  |            15.7104 |
| 28 | health_spend      | Health           |                 -1.29023    |           -0.408668  | -0.881562  |            16.4947 |
| 53 | biden_foreign     | ForeignPolicy    |                  1.06547    |            1.98914   | -0.923668  |            15.8874 |
| 41 | trans_bath        | Transgender      |                  0.689372   |            1.65573   | -0.966354  |            18.9218 |
|  6 | job_gov_guar      | Labor            |                 -0.86063    |            0.154625  | -1.01525   |            16.1721 |
| 21 | biden_crime       | CrimeAndPolicing |                  0.516383   |            1.63725   | -1.12087   |            16.2639 |
| 37 | black_favor       | Diversity        |                 -0.181951   |            0.966427  | -1.14838   |            17.5402 |
|  3 | spend_border      | Immigration      |                 -0.805605   |            0.357683  | -1.16329   |            15.967  |
|  9 | journ_access      | Institutions     |                 -1.11156    |            0.117083  | -1.22864   |            16.2406 |
| 13 | felon_vote        | Elections        |                 -1.07078    |            0.176518  | -1.2473    |            16.7217 |
| 12 | voter_id          | Elections        |                 -1.46927    |            0.136431  | -1.6057    |            16.0706 |
| 30 | dei_college       | Education        |                 -1.47906    |            0.19818   | -1.67724   |            16.9346 |
| 35 | millionaire_tax   | Redistribution   |                 -0.176671   |            1.52921   | -1.70588   |            16.3067 |
| 26 | obamacare         | Health           |                 -0.409667   |            1.39772   | -1.80739   |            16.5293 |
| 18 | death_pen         | CrimeAndPolicing |                 -0.527781   |            1.2802    | -1.80798   |            15.9112 |
| 46 | lg_refuse_service | Lesbian/Gay      |                 -0.0915607  |            1.7753    | -1.86686   |            17.9442 |
| 57 | limit_imports     | Trade            |                 -0.869443   |            1.23629   | -2.10573   |            15.5708 |
| 16 | ar_ban            | Guns             |                 -0.750342   |            1.5512    | -2.30154   |            16.6843 |
| 22 | crime_spend       | CrimeAndPolicing |                 -0.814555   |            2.79737   | -3.61192   |            15.9623 |